/* Masters: items, vendors, customers, locations, exhibitions, users */
(function(){
const $=V.$;
V.need=(v,keys)=>{const bad=keys.filter(k=>!String(v[k]||'').trim());if(bad.length){V.toast('Please fill: '+bad.join(', '),'bad');return false}return true};
const stockOf=sku=>V.db.pieces.filter(p=>p.sku===sku&&p.status==='in_stock').reduce((s,p)=>s+p.qty,0);

// ---------------- ITEMS ----------------
V.page('items',{title:'Item Master',crumb:'Masters',
render(){const d=V.db;const rows=d.items.map(i=>Object.assign({},i,{stock:stockOf(i.sku),wn:i.weave?V.m.weave[i.weave].name:'—'}));
 return V.head('Item Master','Designs / SKUs. Every saree is tracked as a unique <b>serial</b> by default — each saree gets its own serial number at GRN.',`<button class="btn primary" data-act="itemNew">${V.ic('plus')} New Design</button>`)
 +`<div class="g ${V.basic?'g3':'g4'}" style="margin-bottom:18px">${V.kpi({l:'Designs',n:d.items.filter(i=>i.cat==='Saree').length,ic:'tag',c:V.brand.primary,sub:'saree SKUs'})}${V.kpi({l:'Weaves / Clusters',n:V.WEAVES.length,ic:'loom',c:'#1E2A5E',sub:'GI-tagged regions'})}${V.kpi({l:'Serial-tracked',n:d.items.filter(i=>i.trk==='serial').length,ic:'qr',c:'#0F6B6B',sub:'one piece = one serial'})}${V.basic?'':V.kpi({l:'Batch-tracked',n:d.items.filter(i=>i.trk==='batch').length,ic:'layers',c:V.brand.accent,sub:'accessories'})}</div>`
 +V.table('items',{rows,ph:'Search design, weave, colour…',cols:[{k:'sku',l:'',f:r=>`<span style="display:block;width:38px">${V.sw(r,38,46)}</span>`,nosort:true},{k:'sku',l:'SKU',f:r=>`<b>${r.sku}</b>`},{k:'name',l:'Design'},{k:'wn',l:'Weave'},{k:'colour',l:'Colour'},{k:'fabric',l:'Fabric'},{k:'trk',l:'Tracking',f:r=>V.badge(r.trk==='serial'?'Serial':'Batch',r.trk==='serial'?'info':'gold')},{k:'gst',l:'GST',fmt:'pct'},{k:'mrp',l:'MRP',fmt:'inr'},{k:'cost',l:'Std Cost',fmt:'inr'},{k:'stock',l:'In Stock',fmt:'num'}].concat(V.basic?[]:[{k:'shopify',l:'Shopify',f:r=>V.badge(r.shopify?'Mapped':'Unmapped',r.shopify?'ok':'bad'),v:r=>r.shopify?'Mapped':'Unmapped'}]),onRow:r=>V.acts.itemView(r.sku)})},
mount(){}});
V.acts.itemView=sku=>{const it=V.m.item[sku],ps=V.db.pieces.filter(p=>p.sku===sku&&p.status==='in_stock').slice(0,12);
 V.modal({title:V.esc(it.name),wide:true,body:`<div class="g" style="grid-template-columns:200px 1fr;gap:22px"><div>${V.sw(Object.assign({cn:it.name},it),200,240)}</div><div><dl class="kv"><dt>SKU</dt><dd>${it.sku}</dd><dt>Weave / Region</dt><dd>${it.weave?V.m.weave[it.weave].name+' · '+it.region:'—'}</dd><dt>Fabric · Zari</dt><dd>${it.fabric} · ${it.zari||'—'}</dd><dt>Colour</dt><dd>${it.colour}</dd><dt>HSN · GST</dt><dd>${it.hsn} · ${it.gst}%</dd><dt>MRP · Std cost</dt><dd>${V.inr(it.mrp)} · ${V.inr(it.cost)}</dd><dt>Certification</dt><dd>${it.cert||'—'}</dd><dt>Tracking</dt><dd>${it.trk==='serial'?'Unique serial per piece':'Batch number with quantity'}</dd>${V.basic?'':`<dt>Shopify handle</dt><dd>${it.handle} ${it.shopify?V.badge('Mapped','ok'):V.badge('Unmapped','bad')}</dd>`}</dl>
 ${V.imgCtl(it)}<h4 style="margin:16px 0 8px">In stock (${stockOf(sku)})</h4><div class="chips">${ps.map(p=>`<a class="chip" href="#/trace/${p.no}" data-act="closeModal">${p.no} · ${V.short(p.mrp)}</a>`).join('')||'<span class="mute">None</span>'}</div></div></div>`})};
V.acts.itemNew=()=>{V.modal({title:'New Design / SKU',wide:true,body:`<div class="frm">${V.field('Design name *','<input name="name" placeholder="e.g. Kanjivaram Temple Border Peacock">')}${V.imgOn()?V.field('Photo','<input type="file" id="nimg" accept="image/*">','Optional — you can also add it later'):''}${V.field('Weave',`<select name="weave">${V.opts(V.WEAVES,'',{v:w=>w.code,l:w=>w.name})}<option value="">Accessory / none</option></select>`)}${V.field('Colour',`<select name="colour">${V.opts(V.COLOURS,'',{v:c=>c[0],l:c=>c[0]})}</select>`)}${V.basic?'':V.field('Tracking','<select name="trk"><option value="serial">Serial (default — 1 piece = 1 serial)</option><option value="batch">Batch (quantity under batch no.)</option></select>','Generated automatically at GRN')}${V.field('MRP (₹, GST inclusive) *','<input name="mrp" type="number" min="1" placeholder="e.g. 85000">')}${V.field('Standard cost (₹)','<input name="cost" type="number" min="0">')}${V.field('GST %','<input name="gst" type="number" value="5">')}${V.field('HSN','<input name="hsn" value="5007">')}</div>`,
  foot:[{l:'Cancel'},{l:'Create design',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['name','mrp']))return false;const w=V.m.weave[v.weave],c=V.COLOURS.find(x=>x[0]===v.colour);const code=v.weave||'ACC';const n=V.db.items.filter(i=>i.sku.startsWith(code+'-')).length+1;
   const it={sku:code+'-'+String(n).padStart(2,'0'),name:v.name,weave:v.weave,colour:v.colour,body:c[1],bord:c[2],cat:v.weave?'Saree':'Accessory',fabric:w?w.fabric:'—',zari:w?w.zari:'',hsn:v.hsn,gst:+v.gst,mrp:+v.mrp,cost:+v.cost||Math.round(v.mrp*.62),trk:v.trk||'serial',len:'6.3 m',cert:w?w.cert:'',pat:w?w.pat:'butta',region:w?w.region:'',shopify:false,active:true,handle:v.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')};
   V.db.items.push(it);{const pf=$('#nimg')&&$('#nimg').files[0];if(pf)V.imgResize(pf).then(d=>{it.img=d;V.save();V.refresh()})}V.L.audit('Item created',it.sku);V.save();V.toast('Design '+it.sku+' created');V.refresh()}}]})};

// ---------------- VENDORS ----------------
V.page('vendors',{title:'Vendors & Weavers',crumb:'Masters',
render(){const d=V.db;const rows=d.vendors.map(v=>Object.assign({},v,{bal:V.vendorBal(v.id),pur:V.sum(d.grns.filter(g=>g.vendor===v.id),g=>g.value)}));
 return V.head('Vendors & Weavers','Cooperatives, master weavers and artisan trusts — with GSTIN / registration status, payment terms.',`<button class="btn primary" data-act="vendorNew">${V.ic('plus')} New Vendor</button>`)
 +V.table('vendors',{rows,cols:[{k:'code',l:'Code',f:r=>`<b>${r.code}</b>`},{k:'name',l:'Vendor'},{k:'type',l:'Type'},{k:'city',l:'Place',f:r=>`${r.city}, ${r.state}`,v:r=>r.city+' '+r.state},{k:'gstin',l:'GSTIN',f:r=>r.gstin||'<span class="mute">Unregistered</span>',v:r=>r.gstin},{k:'terms',l:'Terms'},{k:'pur',l:'Purchases',fmt:'inr'}].concat(V.basic?[]:[{k:'rating',l:'Rating',f:r=>`<span class="gold">★</span> ${r.rating}`,v:r=>r.rating},{k:'bal',l:'Payable',fmt:'inr'}]),onRow:V.basic?undefined:r=>V.go('#/vledger/'+r.id)})}});
V.acts.vendorNew=()=>V.modal({title:'New Vendor / Weaver',wide:true,body:`<div class="frm">${V.field('Name *','<input name="name">')}${V.field('Type','<select name="type"><option>Cooperative</option><option>Master Weaver</option><option>Artisan Trust</option><option>Local Supplier</option></select>')}${V.field('Weave cluster',`<select name="weave"><option value="">—</option>${V.opts(V.WEAVES,'',{v:w=>w.code,l:w=>w.name})}</select>`)}${V.field('City','<input name="city">')}${V.field('State',`<select name="state">${V.opts(Object.keys(V.STATES),'Tamil Nadu')}</select>`)}${V.field('GSTIN','<input name="gstin" placeholder="Leave blank if unregistered (RCM)">')}${V.field('Phone','<input name="phone">')}${V.field('Payment terms','<input name="terms" value="Net 30">')}</div>`,
 foot:[{l:'Cancel'},{l:'Save vendor',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['name']))return false;V.db.vendors.push(Object.assign(v,{id:'V'+String(V.db.vendors.length+1).padStart(2,'0'),code:'V-'+(v.weave||'LOC'+V.db.vendors.length),pan:'',bank:'',rating:4,since:V.db.today,reg:v.gstin?'Regular':'Unregistered (RCM)'}));V.save();V.toast('Vendor added');V.refresh()}}]});

// ---------------- CUSTOMERS ----------------
const tierBadge=t=>V.badge(t,'gold');
V.page('customers',{title:a=>a?'Customer Profile':'Customer Master (CRM)',crumb:'Masters',
render(id){const d=V.db;if(id)return V.custDetail(id);
 const rows=d.customers.map(c=>Object.assign({},c,{bills:d.invoices.filter(i=>i.cust===c.id).length}));
 return V.head('Customer Master','Single customer record used by POS billing, returns and the Shopify customer export.',`<button class="btn primary" data-act="custNew">${V.ic('plus')} New Customer</button>`)
 +(V.basic?'':`<div class="g g4" style="margin-bottom:18px">${['Maharani','Rani','Gold','Silver'].map((t,i)=>V.kpi({l:t+' tier',n:d.customers.filter(c=>c.tier===t).length,ic:'star',c:[V.brand.primary,'#B0245F',V.brand.accent,'#5B7DB1'][i],sub:['₹6 L+ lifetime','₹2.5 L+','₹1 L+','new & occasional'][i]})).join('')}</div>`)
 +V.table('cust',{rows,ph:'Search name, phone, city…',cols:[{k:'name',l:'Customer',f:r=>`<b>${V.esc(r.name)}</b>${r.company?`<div class="xs mute">${V.esc(r.company)}</div>`:''}`,v:r=>r.name},{k:'phone',l:'Phone'},{k:'city',l:'City',f:r=>r.city+', '+r.state.slice(0,2),v:r=>r.city},{k:'bills',l:'Bills',fmt:'num'},{k:'spend',l:'Lifetime Spend',fmt:'inr'}].concat(V.basic?[]:[{k:'tier',l:'Tier',f:r=>tierBadge(r.tier),v:r=>r.tier},{k:'loyalty',l:'Points',fmt:'num'},{k:'credit',l:'Store Credit',fmt:'inr'}]).concat([{k:'gstin',l:'B2B',f:r=>r.gstin?V.badge('GSTIN','info'):'',v:r=>r.gstin?'B2B':''}]),onRow:r=>V.go('#/customers/'+r.id)})}});
V.custDetail=id=>{const c=V.m.cust[id],d=V.db,inv=d.invoices.filter(i=>i.cust===id).reverse();if(!c)return '<div class="card">Customer not found</div>';
 const wl=d.wishlist.filter(w=>w.cust===id);
 return V.head(V.esc(c.name),`${c.city}, ${c.state} · ${c.phone} · ${c.email}`,`<a class="btn" href="#/customers">‹ All customers</a><a class="btn primary" href="#/pos" data-act="posCust" data-id="${id}">${V.ic('cart')} Bill this customer</a>`)
 +`<div class="g ${V.basic?'g2':'g4'}">${V.kpi({l:'Lifetime spend',n:c.spend||0,f:'short',ic:'coins',c:V.brand.primary,sub:V.basic?'all bills':tierBadge(c.tier)})}${V.kpi({l:'Bills',n:inv.length,ic:'receipt',c:'#1E2A5E',sub:inv[0]?'last '+V.fd(inv[0].date):'—'})}${V.basic?'':V.kpi({l:'Loyalty points',n:c.loyalty||0,ic:'star',c:V.brand.accent,sub:'1 pt per ₹100'})}${V.basic?'':V.kpi({l:'Store credit',n:c.credit||0,f:'inr',ic:'wallet',c:'#0F6B6B',sub:'credit notes'})}</div>
 <div class="g g21 mt">${V.card('Purchase history','Click an invoice to open',V.table('custinv',{rows:inv,search:false,cols:[{k:'no',l:'Invoice',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'loc',l:'Location',f:r=>V.esc(V.m.loc[r.loc].city),v:r=>V.m.loc[r.loc].city},{k:'items',l:'Items',f:r=>r.lines.map(l=>V.esc(l.name)).join(', '),v:r=>r.lines.length},{k:'net',l:'Amount',fmt:'inr'}],onRow:r=>V.go('#/invoices/'+encodeURIComponent(r.no)),pageSize:8}))}
 ${V.card(V.basic?'Contact':'Profile & preferences',V.basic?'':'Used for personalised outreach',`<dl class="kv">${V.basic?'':`<dt>Birthday</dt><dd>${V.fd(c.dob)}</dd><dt>Anniversary</dt><dd>${V.fd(c.anniv)}</dd><dt>Prefers</dt><dd>${c.prefs.weaves.map(w=>V.badge(V.m.weave[w].name,'gold')).join(' ')}</dd><dt>Colour</dt><dd>${c.prefs.colour}</dd><dt>Budget</dt><dd>${V.short(c.prefs.budget[0])} – ${V.short(c.prefs.budget[1])}</dd>`}<dt>GSTIN</dt><dd>${c.gstin||'—'}</dd><dt>Customer since</dt><dd>${V.fd(c.since)}</dd><dt>Notes</dt><dd>${V.esc(c.notes||'—')}</dd></dl>${wl.length&&!V.basic?`<h4 style="margin:14px 0 6px">Wishlist</h4>${wl.map(w=>`<div class="badge info">${V.m.weave[w.weave].name} · ${w.colour} · up to ${V.short(w.budget)}</div>`).join(' ')}`:''}`)}</div>`};
V.acts.posCust=el=>{V.S.posCust=el.dataset.id};
V.acts.custNew=()=>V.modal({title:'New Customer',wide:true,body:`<div class="frm">${V.field('Full name *','<input name="name">')}${V.field('Mobile *','<input name="phone" type="tel" inputmode="numeric" maxlength="10">')}${V.field('Email','<input name="email" type="email">')}${V.field('City','<input name="city" value="Chennai">')}${V.field('State',`<select name="state">${V.opts(Object.keys(V.STATES),'Tamil Nadu')}</select>`)}${V.field('GSTIN (B2B)','<input name="gstin">','IGST applies when GSTIN state differs from selling plant')}${V.basic?'':V.field('Birthday','<input name="dob" type="date">')+V.field('Anniversary','<input name="anniv" type="date">')+V.field('Preferred weave',`<select name="weave">${V.opts(V.WEAVES,'',{v:w=>w.code,l:w=>w.name})}</select>`)+V.field('Preferred colour',`<select name="colour">${V.opts(V.COLOURS,'',{v:c=>c[0],l:c=>c[0]})}</select>`)}</div>`,
 foot:[{l:'Cancel'},{l:'Save customer',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['name','phone']))return false;if(!/^\d{10}$/.test(v.phone)){V.toast('Mobile must be 10 digits','bad');return false}
  const c={id:'C'+String(V.db.customers.length+1).padStart(4,'0'),name:v.name,phone:v.phone,email:v.email,city:v.city,state:v.state,gstin:v.gstin,company:'',dob:v.dob,anniv:v.anniv,prefs:{weaves:[v.weave||'KJV'],colour:v.colour||'Temple Maroon',budget:[50000,200000]},since:V.db.today,tier:'Silver',credit:0,loyalty:0,spend:0,notes:'',consent:true};V.db.customers.push(c);V.L.syncAdd('Customer',c.id,V.S.loc,0);V.L.audit('Customer created',c.id);V.save();V.toast('Customer '+c.name+' added');V.refresh()}}]});

// ---------------- LOCATIONS ----------------
V.page('locations',{title:'Locations & Plants',crumb:'Masters',
render(){const d=V.db;
 return V.head('Locations & Plants','Main showroom, vault and a <b>separate plant per exhibition</b> — each with its own state GSTIN registration, bins, cash drawer and Shopify location mapping.',`<button class="btn primary" data-act="locNew">${V.ic('plus')} New Location</button>`)
 +`<div class="g g3">${d.locations.map(l=>{const st=d.pieces.filter(p=>p.loc===l.id&&p.status==='in_stock'),u=V.sum(st,p=>p.qty),val=V.sum(st,p=>p.cost*p.qty);
  return `<div class="card motif-edge" style="padding-bottom:26px"><div class="row between"><span class="badge ${l.type==='Exhibition'?'gold':l.type==='Warehouse'?'info':'ok'}">${V.ic(l.type==='Exhibition'?'flag':l.type==='Warehouse'?'box':'store')} ${l.type}</span>${V.badge(l.status)}</div><h3 style="margin-top:10px">${V.esc(l.name)}</h3><div class="sub">${l.city}, ${l.state} · code ${l.code}</div>
  <dl class="kv"><dt>GSTIN</dt><dd>${l.gstin}</dd><dt>Shopify location</dt><dd>${l.shopifyLoc?V.esc(l.shopifyLoc):'<span class="badge bad">Not mapped</span>'}</dd><dt>Bins</dt><dd>${l.bins.join(' · ')}</dd><dt>Stock</dt><dd><b>${u}</b> units · ${V.short(val)} at cost</dd>${l.exh?`<dt>Exhibition</dt><dd><a href="#/exhibitions/${l.exh}">${l.exh}</a></dd>`:''}</dl></div>`}).join('')}</div>`}});
V.acts.locNew=()=>V.modal({title:'New Location',body:`<div class="frm">${V.field('Name *','<input name="name">','Exhibition plants are created automatically from Exhibition Master','full')}${V.field('Type','<select name="type"><option>Showroom</option><option>Warehouse</option></select>')}${V.field('City','<input name="city">')}${V.field('State',`<select name="state">${V.opts(Object.keys(V.STATES),'Tamil Nadu')}</select>`)}${V.field('GSTIN','<input name="gstin">')}</div>`,
 foot:[{l:'Cancel'},{l:'Create',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['name','city']))return false;const id='L'+(V.db.locations.length+1);V.db.locations.push({id,code:v.city.slice(0,3).toUpperCase(),name:v.name,type:v.type,city:v.city,state:v.state,gstin:v.gstin||'—',shopifyLoc:'',status:'Active',bins:['Rack 1']});V.save();V.toast('Location created');V.refresh()}}]});

// ---------------- EXHIBITIONS ----------------
const exStatusAct=e=>e.status==='Planned'?`<button class="btn sm primary" data-act="exGoLive" data-code="${e.code}">${V.ic('flag')} Go live</button>`:e.status==='Live'?`<button class="btn sm" data-act="exClose" data-code="${e.code}">${V.ic('check')} Close exhibition</button>`:e.status==='Closed'?`<a class="btn sm primary" href="#/recon/${e.code}">${V.ic('layers')} Reconcile</a>`:'';
V.page('exhibitions',{title:a=>a?'Exhibition':'Exhibition Master',crumb:'Masters',
render(code){const d=V.db;if(code)return V.exhDetail(code);
 return V.head('Exhibition Master','One exhibition — <b>one unique code</b>, one plant, one reconciliation. Stays on record forever for future reference.',`<button class="btn primary" data-act="exNew">${V.ic('plus')} New Exhibition</button>`)
 +`<div class="g g3">${d.exhibitions.map(e=>{const s=V.L.exhStats(e.code);return `<a class="card motif-edge fam" style="padding-bottom:26px" href="#/exhibitions/${e.code}"><div class="row between"><span class="badge gold" style="font-family:monospace">${e.code}</span>${V.badge(e.status)}</div><h3 style="margin-top:10px">${V.esc(e.name)}</h3><div class="sub">${e.venue} · ${e.city}, ${e.state}</div><div class="row sm mute">${V.ic('cal')} ${V.fd(e.start)} → ${V.fd(e.end)}</div>
  ${e.status==='Planned'?(V.basic?'':`<div class="mt mute sm">Target ${V.short(e.target)} · Stall cost ${V.short(e.stall)}</div>`):`<div class="g g3 mt" style="gap:8px"><div><div class="xs mute">Sales</div><b>${V.short(s.sales)}</b></div><div><div class="xs mute">Sold</div><b>${s.sold}/${s.opening}</b></div>${V.basic?`<div><div class="xs mute">Balance</div><b>${s.balance}</b></div>`:`<div><div class="xs mute">P&L</div><b style="color:${s.profit>=0?'var(--ok)':'var(--bad)'}">${V.short(s.profit)}</b></div>`}</div>`}</a>`}).join('')}</div>`}});
V.exhDetail=code=>{const e=V.m.exh[code];if(!e)return '<div class="card">Not found</div>';const s=V.L.exhStats(code),d=V.db;
 const tr=d.transfers.filter(t=>t.exh===code),rec=d.recons.find(r=>r.exh===code);
 return V.head(V.esc(e.name),`<span class="badge gold" style="font-family:monospace">${e.code}</span> ${V.badge(e.status)} · ${e.venue}, ${e.city}`,`<a class="btn" href="#/exhibitions">‹ All</a>${exStatusAct(e)}${e.status!=='Reconciled'?`<a class="btn sm" href="#/transfer" data-act="trfTo" data-plant="${e.plant}">${V.ic('swap')} Transfer stock</a>`:''}`)
 +`<div class="g ${V.basic?'g4':'g5'}">${V.kpi({l:'Net sales',n:s.sales,f:'short',ic:'cash',c:V.brand.primary,sub:`${s.invoices} bills`})}${V.kpi({l:'Dispatched',n:s.opening,ic:'truck',c:'#1E2A5E',sub:'units from Main'})}${V.kpi({l:V.basic?'Sold':'Sell-through',n:V.basic?s.sold:s.sell,f:V.basic?'num':'pct',ic:'target',c:'#0F6B6B',sub:`${s.sold} sold · ${s.balance} balance`})}${V.basic?V.kpi({l:'Balance at plant',n:s.balance,ic:'box',c:V.brand.accent,sub:'units still on hand'}):V.kpi({l:'Expenses',n:s.exp,f:'short',ic:'wallet',c:V.brand.accent,sub:`stall ${V.short(e.stall)} + petty`})}${V.basic?'':V.kpi({l:'Exhibition P&L',n:s.profit,f:'short',ic:'coins',c:s.profit>=0?'#2E8B57':'#B3261E',sub:'sales − COGS − costs'})}</div>
 <div class="g ${V.basic?'':'g21 '}mt">${V.basic?'':V.card('Daily sales','Net sales by day','<div class="cw sm"><canvas id="c-ex" role="img" aria-label="Daily sales at exhibition"></canvas></div>')}${V.card('Details','',`<dl class="kv"><dt>Plant</dt><dd>${V.m.loc[e.plant].name}</dd><dt>GSTIN (${e.state})</dt><dd>${V.m.loc[e.plant].gstin}</dd><dt>Dates</dt><dd>${V.fd(e.start)} → ${V.fd(e.end)}</dd><dt>In-charge</dt><dd>${V.L.userName(e.incharge)}</dd><dt>Staff</dt><dd>${e.staff.map(V.L.userName).join(', ')}</dd>${V.basic?'':`<dt>Target</dt><dd>${V.short(e.target)} (${V.pct(s.sales,e.target)}%)</dd>`}</dl>${rec?`<div class="login-note mt">Reconciled ${V.fd(rec.date)} — ${rec.returned} returned to Main, ${rec.damaged} damaged, ${rec.missing} missing.</div>`:''}`)}</div>
 ${V.card('Stock transfers','Main ↔ exhibition plant',V.table('extr',{rows:tr,search:false,cols:[{k:'no',l:'Transfer',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'route',l:'Route',f:r=>V.esc(V.m.loc[r.from].city+' → '+V.m.loc[r.to].city),v:r=>r.from+r.to},{k:'n',l:'Units',f:r=>V.sum(r.lines,l=>l.qty),v:r=>V.sum(r.lines,l=>l.qty)},{k:'value',l:'Value (MRP)',fmt:'inr'}].concat(V.basic?[]:[{k:'ewb',l:'E-way bill',f:r=>r.ewb||'—',v:r=>r.ewb}]).concat([{k:'status',l:'Status',fmt:'badge'}]),pageSize:6}),'mt')}`};
V.page('exhibitions').mount=code=>{if(!code||V.basic)return;const e=V.m.exh[code],inv=V.db.invoices.filter(i=>i.loc===e.plant),days=V.uniq(inv.map(i=>i.date)).sort();V.chart('c-ex',{labels:days.map(V.fds),data:[{label:'Net sales',data:days.map(x=>V.sum(inv.filter(i=>i.date===x),i=>i.net)),color:V.brand.accent}],fmt:V.short,legend:false})};
V.acts.trfTo=el=>{V.S.trfTo=el.dataset.plant};
V.acts.exGoLive=async el=>{const e=V.m.exh[el.dataset.code];if(await V.confirm(`Start <b>${V.esc(e.name)}</b>? The plant becomes active for stock transfer and billing.`,'Go live')){e.status='Live';const l=V.m.loc[e.plant];l.status='Active';l.shopifyLoc='Pop-up · '+e.city;V.L.audit('Exhibition live',e.code);V.save();V.toast(e.code+' is live');V.refresh()}};
V.acts.exClose=async el=>{const e=V.m.exh[el.dataset.code];if(await V.confirm(`Close <b>${V.esc(e.name)}</b>? Billing stops; you can then reconcile the remaining stock.`,'Close exhibition')){e.status='Closed';V.L.audit('Exhibition closed',e.code);V.save();V.toast('Exhibition closed — reconcile next');V.go('#/recon/'+e.code)}};
V.acts.exNew=()=>V.modal({title:'New Exhibition',wide:true,body:`<div class="frm">${V.field('Exhibition name *','<input name="name" placeholder="e.g. Silk Utsav Coimbatore">')}${V.field('Venue','<input name="venue">')}${V.field('City *','<input name="city" id="exc">')}${V.field('State',`<select name="state">${V.opts(Object.keys(V.STATES),'Tamil Nadu')}</select>`,'Different state ⇒ separate GST registration, IGST on stock transfers')}${V.field('Start date *','<input name="start" type="date">')}${V.field('End date *','<input name="end" type="date">')}${V.basic?'':V.field('Stall cost (₹)','<input name="stall" type="number" value="90000">')+V.field('Sales target (₹)','<input name="target" type="number" value="2000000">')}${V.field('In-charge',`<select name="incharge">${V.opts(V.db.users.filter(u=>['Owner','Store Manager','Exhibition In-charge'].includes(u.role)),'U07',{v:u=>u.id,l:u=>u.name})}</select>`)}<div class="field"><label>Unique code</label><div class="badge gold" id="exCode" style="font-family:monospace;padding:10px 14px">Auto-generated</div></div></div>`,
 onOpen:r=>{const f=()=>{const c=$('#exc').value.trim().toUpperCase().replace(/[^A-Z]/g,'').slice(0,3);$('#exCode').textContent=c.length>1?`EXH-${new Date().getFullYear()}-${c}-${String(V.db.exhibitions.length+1).padStart(3,'0')}`:'Auto-generated'};$('#exc').addEventListener('input',f)},
 foot:[{l:'Cancel'},{l:'Create exhibition',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['name','city','start','end']))return false;if(v.end<v.start){V.toast('End date is before start date','bad');return false}
  const ab=v.city.toUpperCase().replace(/[^A-Z]/g,'').slice(0,3),code=`EXH-${v.start.slice(0,4)}-${ab}-${String(V.db.exhibitions.length+1).padStart(3,'0')}`;let pid='P-'+ab;while(V.m.loc[pid])pid+='X';
  V.db.exhibitions.push({code,name:v.name,venue:v.venue,city:v.city,state:v.state,start:v.start,end:v.end,plant:pid,incharge:v.incharge,staff:['U03','U04'],stall:+v.stall||0,target:+v.target||0,status:'Planned',notes:''});
  V.db.locations.push({id:pid,code:ab,name:'Exhibition Plant — '+v.city,type:'Exhibition',city:v.city,state:v.state,gstin:'— (register in '+v.state+')',shopifyLoc:'',status:'Planned',bins:['Stall Rack','Display Table'],exh:code});
  V.L.audit('Exhibition created',code);V.save();V.toast('Exhibition '+code+' created');V.go('#/exhibitions/'+code)}}]});

// ---------------- USERS ----------------
const PERMS=[['Billing (POS)',['Owner','Store Manager','Cashier','Exhibition In-charge']],['Discount > 10%',['Owner','Store Manager']],['Purchase orders',['Owner','Store Manager','Accountant']],['GRN / Inward',['Owner','Store Manager','Store Keeper']],['Stock transfer',['Owner','Store Manager','Store Keeper','Exhibition In-charge']],['Reconciliation',['Owner','Store Manager','Exhibition In-charge']],['Day-end close',['Owner','Store Manager']],['Reports',['Owner','Store Manager','Accountant']],['Shopify sync',['Owner','Accountant']],['Master data',['Owner','Store Manager']],['Approvals',['Owner']]];
V.page('users',{title:'Users & Roles',crumb:'Masters',
render(){const roles=['Owner','Store Manager','Cashier','Store Keeper','Accountant','Exhibition In-charge'];
 return V.head('Users & Roles',V.basic?'Staff who can use the system and their roles.':'Role-based access with discount limits and an approval matrix. Sensitive actions are logged in the audit trail.')
 +V.card('Users','',V.table('users',{rows:V.db.users,search:false,cols:[{k:'name',l:'Name',f:r=>`<b>${r.name}</b>`},{k:'role',l:'Role',fmt:'badge',v:r=>r.role},{k:'email',l:'Email'}].concat(V.basic?[]:[{k:'disc',l:'Max discount',f:r=>r.disc+'%',v:r=>r.disc}])}))
 +(V.basic?'':V.card('Permission matrix','What each role can do',`<div class="tscroll"><table class="t"><thead><tr><th>Capability</th>${roles.map(r=>`<th class="center">${r}</th>`).join('')}</tr></thead><tbody>${PERMS.map(p=>`<tr><td>${p[0]}</td>${roles.map(r=>`<td class="center">${p[1].includes(r)?'<span class="gold">●</span>':'<span class="mute">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,'mt'))}});
})();
