/* Cash drawer, day-end, petty cash, Shopify sync, GST, approvals, imports, audit, settings */
(function(){
const $=V.$;
const drawerArt=V.basic?'':`<svg viewBox="0 0 220 120" width="220" aria-hidden="true"><rect x="10" y="50" width="200" height="60" rx="8" fill="#3A1226"/><rect x="18" y="58" width="184" height="44" rx="5" fill="#27163F"/><g class="notes"><rect x="30" y="28" width="70" height="34" rx="3" fill="#2E8B57" transform="rotate(-6 65 45)"/><rect x="60" y="22" width="76" height="36" rx="3" fill="#B8893A" transform="rotate(3 98 40)"/><rect x="104" y="30" width="72" height="34" rx="3" fill="${V.brand.primary}" transform="rotate(8 140 47)"/></g><rect x="10" y="62" width="200" height="48" rx="8" fill="#5B1633"/><rect x="85" y="80" width="50" height="8" rx="4" fill="#E3C57A"/></svg>`;
const todayDr=(loc)=>V.L.drawer(loc,V.db.today,false);

// ================= CASH DRAWER =================
V.page('drawer',{title:'Cash Drawer',crumb:'POS & Cash',
render(){const d=V.db,loc=V.curLoc(),r=todayDr(loc.id);
 const hist=d.drawers.filter(x=>x.loc===loc.id&&x.status==='closed').slice(-30).reverse().map(x=>Object.assign({},x,{c:V.L.drawerCalc(x)}));
 let top;
 if(!r)top=`<div class="card center"><div style="display:flex;justify-content:center">${drawerArt}</div><h2>Drawer is closed</h2><p class="mute">Open the drawer with a starting float to begin billing at ${V.esc(loc.name)}.</p><div class="row" style="justify-content:center"><input id="fl" type="number" value="25000" style="max-width:180px" aria-label="Opening float"><button class="btn primary lg" data-act="drOpen">${V.ic('cash')} Open drawer</button></div></div>`;
 else{const c=V.L.drawerCalc(r);top=`<div class="g g21"><div class="g g3" style="gap:14px">${V.kpi({l:'Opening float',n:c.float,f:'inr',ic:'wallet',c:'#1E2A5E',sub:'opened '+r.opened+' by '+V.L.userName(r.openedBy)})}${V.kpi({l:'Cash sales',n:c.sales,f:'inr',ic:'cash',c:'#2E8B57',sub:d.invoices.filter(i=>i.loc===loc.id&&i.date===r.date&&i.pays.some(p=>p.mode==='Cash')).length+' cash bills'})}${V.kpi({l:'Cash in',n:c.cin,f:'inr',ic:'plus',c:'#0F6B6B',sub:'advances, other receipts'})}${V.kpi({l:'Cash out',n:c.cout,f:'inr',ic:'return',c:V.brand.accent,sub:'top-ups, payouts'})}${V.kpi({l:'Safe drops',n:c.drop,f:'inr',ic:'shield',c:'#6A4C93',sub:'moved to safe / bank'})}${V.kpi({l:'Expected in drawer',n:c.expected,f:'inr',ic:'target',c:V.brand.primary,sub:r.status==='closed'?'Closed':'live balance'})}</div><div class="card center" style="display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px">${drawerArt}<span class="badge ${r.status==='open'?'ok':''}">${r.status==='open'?'● Open':'Closed'}</span>${r.status==='open'?`<div class="row" style="justify-content:center"><button class="btn sm" data-act="drEntry" data-t="in">+ Cash in</button><button class="btn sm" data-act="drEntry" data-t="out">− Cash out</button><button class="btn sm" data-act="drEntry" data-t="drop">Safe drop</button></div><a class="btn primary" href="#/dayend">${V.ic('clock')} Go to Day End</a>`:''}</div></div>
  ${V.card('Today\'s drawer ledger',V.esc(loc.name)+' · '+V.fd(r.date),V.table('drl',{search:false,rows:V.drawerRows(r),cols:[{k:'time',l:'Time'},{k:'type',l:'Entry',fmt:'badge'},{k:'reason',l:'Reason / reference'},{k:'by',l:'By'},{k:'amt',l:'Amount',f:r=>`<b style="color:${r.sign>0?'var(--ok)':'var(--bad)'}">${r.sign>0?'+':'−'} ${V.inr(r.amt)}</b>`,v:r=>r.sign*r.amt}],pageSize:8}),'mt')}`}
 return V.head('Cash Drawer','Open with a float, record every cash-in / cash-out / safe drop, and watch the expected balance update live as cash bills are posted.')+top
  +(V.basic?'':V.card('Previous drawers','Closed days at this location',V.table('drh',{rows:hist,cols:[{k:'date',l:'Date',fmt:'date'},{k:'openedBy',l:'Cashier',f:r=>V.L.userName(r.openedBy),v:r=>r.openedBy},{k:'float',l:'Float',fmt:'inr'},{k:'sales',l:'Cash sales',f:r=>V.inr(r.c.sales),v:r=>r.c.sales,n:true},{k:'exp',l:'Expected',f:r=>V.inr(r.closing.expected),v:r=>r.closing.expected,n:true},{k:'cnt',l:'Counted',f:r=>V.inr(r.closing.counted),v:r=>r.closing.counted,n:true},{k:'var',l:'Variance',f:r=>V.badge((r.closing.variance>0?'+':'')+V.inr(r.closing.variance),r.closing.variance?'warn':'ok'),v:r=>r.closing.variance},{k:'dep',l:'Deposited',f:r=>V.inr(r.closing.deposit),v:r=>r.closing.deposit,n:true}],pageSize:8}),'mt'))}});
V.drawerRows=r=>{const d=V.db,rows=[{time:r.opened,type:'Opening float',reason:'Drawer opened',by:V.L.userName(r.openedBy),amt:r.float,sign:1}];
 d.invoices.filter(i=>i.loc===r.loc&&i.date===r.date&&i.pays.some(p=>p.mode==='Cash')).forEach(i=>rows.push({time:i.time,type:'Cash sale',reason:i.no,by:V.L.userName(i.cashier),amt:V.L.cashNet(i),sign:1}));
 r.entries.forEach(e=>rows.push({time:e.time,type:e.t==='in'?'Cash in':e.t==='out'?'Cash out':'Safe drop',reason:e.reason,by:V.L.userName(e.by),amt:e.amt,sign:e.t==='in'?1:-1}));
 d.salesReturns.filter(x=>x.loc===r.loc&&x.date===r.date&&x.refundMode==='Cash').forEach(x=>rows.push({time:'—',type:'Cash refund',reason:x.no,by:V.L.userName(x.by),amt:x.amt,sign:-1}));
 return rows.sort((a,b)=>a.time<b.time?-1:1)};
V.acts.drOpen=()=>{const loc=V.curLoc().id,r=V.L.drawer(loc,V.db.today);r.float=+$('#fl').value||0;r.opened=V.now();r.openedBy=V.S.user;V.L.audit('Drawer opened',r.id);V.save();V.toast('Drawer opened with float '+V.inr(r.float));V.refresh()};
V.acts.drEntry=el=>{const t=el.dataset.t,ttl={in:'Cash in',out:'Cash out',drop:'Safe drop / bank deposit'}[t];V.modal({title:ttl,body:`<div class="frm">${V.field('Amount (₹) *','<input id="dea" type="number" min="1">')}${V.field('Reason *',`<input id="der" placeholder="${t==='in'?'e.g. Customer advance, change float':t==='out'?'e.g. Courier payout, staff advance':'e.g. Evening bank deposit'}">`,'','full')}</div>`,foot:[{l:'Cancel'},{l:'Record',cls:'primary',fn:()=>{const a=+$('#dea').value,rs=$('#der').value.trim();if(!(a>0)||!rs){V.toast('Enter amount and reason','bad');return false}const r=todayDr(V.curLoc().id);if(t!=='in'&&a>V.L.drawerCalc(r).expected){V.toast('Amount exceeds cash in drawer','bad');return false}r.entries.push({t,amt:a,reason:rs,time:V.now(),by:V.S.user});V.L.audit(ttl,r.id);V.save();V.toast(ttl+' recorded');V.refresh()}}]})};

// ================= DAY END =================
V.zHtml=r=>{const d=V.db,c=V.L.drawerCalc(r),cl=r.closing,loc=V.m.loc[r.loc],inv=d.invoices.filter(i=>i.loc===r.loc&&i.date===r.date),modes={};inv.forEach(i=>i.pays.forEach(p=>modes[p.mode]=(modes[p.mode]||0)+(p.mode==='Cash'?V.L.cashNet(i):p.amt)));
 const pet=V.sum(d.petty.filter(p=>p.loc===r.loc&&p.date===r.date&&p.type==='expense'),p=>p.amt);
 return `<h2>Z-Report · Day End</h2><div class="temple"></div><p><b>${V.esc(loc.name)}</b> · ${V.fd(r.date)} · GSTIN ${loc.gstin}</p><table><tr><th>Sales summary</th><th class="r">Amount</th></tr><tr><td>Invoices</td><td class="r">${inv.length}</td></tr><tr><td>Gross sales (incl. GST)</td><td class="r">${V.inr(V.sum(inv,i=>i.net))}</td></tr>${Object.entries(modes).map(([k,v])=>`<tr><td>&nbsp;&nbsp;${k}</td><td class="r">${V.inr(v)}</td></tr>`).join('')}<tr><td>Petty expenses</td><td class="r">${V.inr(pet)}</td></tr></table><br><table><tr><th>Cash reconciliation</th><th class="r">Amount</th></tr><tr><td>Opening float</td><td class="r">${V.inr(c.float)}</td></tr><tr><td>+ Cash sales</td><td class="r">${V.inr(c.sales)}</td></tr><tr><td>+ Cash in</td><td class="r">${V.inr(c.cin)}</td></tr><tr><td>− Cash out</td><td class="r">${V.inr(c.cout)}</td></tr><tr><td>− Refunds</td><td class="r">${V.inr(c.refunds)}</td></tr><tr><td>− Safe drops</td><td class="r">${V.inr(c.drop)}</td></tr><tr><td><b>Expected in drawer</b></td><td class="r"><b>${V.inr(c.expected)}</b></td></tr><tr><td><b>Counted</b></td><td class="r"><b>${V.inr(cl.counted)}</b></td></tr><tr><td><b>Variance</b></td><td class="r"><b>${V.inr(cl.variance)}</b></td></tr></table><p>Closed by ${V.L.userName(cl.by)} at ${cl.time}. Cash to deposit: ${V.inr(cl.deposit)}.</p>`};
V.page('dayend',{title:'Day End',crumb:'POS & Cash',
render(){const d=V.db,loc=V.curLoc(),r=todayDr(loc.id);
 if(!r)return V.head('Day End','')+`<div class="card center"><div class="empty">${V.art.empty()}<p>No drawer opened today at ${V.esc(loc.name)}.</p><a class="btn primary" href="#/drawer">Open drawer</a></div></div>`;
 const c=V.L.drawerCalc(r),inv=d.invoices.filter(i=>i.loc===loc.id&&i.date===r.date),modes={};inv.forEach(i=>i.pays.forEach(p=>modes[p.mode]=(modes[p.mode]||0)+(p.mode==='Cash'?V.L.cashNet(i):p.amt)));
 const pet=V.sum(d.petty.filter(p=>p.loc===loc.id&&p.date===r.date&&p.type==='expense'),p=>p.amt);
 if(r.status==='closed'){const cl=r.closing;return V.head('Day End — closed','',`<button class="btn gold" data-act="zPrint">${V.ic('print')} Print Z-report</button>`)+`<div class="card center" style="margin-bottom:18px"><div style="width:70px;margin:auto;color:var(--ok)">${V.ic('check')}</div><h2>Day closed at ${cl.time}</h2><p class="mute">Variance ${V.inr(cl.variance)} · Cash to deposit ${V.inr(cl.deposit)} · ${V.basic?'Export today\'s orders from Shopify Sync → File export':'Orders queued for Shopify sync'}</p><a class="btn primary" href="#/shopify">${V.ic('sync')} ${V.basic?'Shopify file export':'Open Shopify console'}</a></div><div class="card">${V.zHtml(r)}</div>`}
 const st=V.S.de=V.S.de||{den:{},note:''};const counted=V.sum(V.DENOM,k=>k*(+st.den[k]||0)),varc=counted-c.expected;
 return V.head('Day End · '+V.fd(r.date),V.esc(loc.name)+' — reconcile the drawer, review collections, close the day'+(V.basic?'.':' and release the bills to Shopify.')+'')
 +`<div class="g g21"><div class="g" style="gap:18px">${V.card('1 · Collections today','Posted invoices by payment mode',`<div class="g g4" style="gap:10px">${Object.entries(modes).map(([k,v])=>`<div class="card flat" style="padding:12px"><div class="xs mute">${k}</div><b style="font-size:18px">${V.short(v)}</b></div>`).join('')||'<span class="mute">No sales yet</span>'}</div><div class="row between mt sm"><span>${inv.length} invoices · ${V.inr(V.sum(inv,i=>i.net))} gross</span><span>Petty expenses ${V.inr(pet)} (paid from imprest)</span></div>`)}
 ${V.card('2 · Count the cash','Enter notes & coins in the drawer',`<div class="g g4" style="gap:10px">${V.DENOM.map(k=>`<div class="field" style="margin:0"><label>₹${k} ×</label><input type="number" min="0" value="${st.den[k]||''}" data-st="de.den.${k}" data-re="1" placeholder="0"></div>`).join('')}</div><div class="row between mt"><div><div class="xs mute">Counted</div><b style="font-size:22px;font-family:var(--f-num);font-weight:700">${V.inr(counted)}</b></div><div><div class="xs mute">Expected</div><b style="font-size:22px;font-family:var(--f-num);font-weight:700">${V.inr(c.expected)}</b></div><div><div class="xs mute">Variance</div><b style="font-size:22px;font-family:var(--f-num);font-weight:700;color:${varc===0?'var(--ok)':'var(--bad)'}">${varc>0?'+':''}${V.inr(varc)}</b></div></div>`,'')}</div>
 <div class="g" style="gap:18px">${V.card('Expected cash',V.esc(loc.name),`<div class="tot"><div><span>Opening float</span><span>${V.inr(c.float)}</span></div><div><span>+ Cash sales</span><span>${V.inr(c.sales)}</span></div><div><span>+ Cash in</span><span>${V.inr(c.cin)}</span></div><div><span>− Cash out</span><span>${V.inr(c.cout)}</span></div><div><span>− Cash refunds</span><span>${V.inr(c.refunds)}</span></div><div><span>− Safe drops</span><span>${V.inr(c.drop)}</span></div><div class="grand"><span>Expected</span><span>${V.inr(c.expected)}</span></div></div>`)}
 ${V.card('3 · Sign-off','',`${V.field('Notes','<textarea data-st="de.note" placeholder="Explain any variance…">'+V.esc(st.note)+'</textarea>')}<button class="btn primary lg" style="width:100%" data-act="deClose" ${counted===0?'disabled':''}>${V.ic('check')} Close day${V.basic?'':' & release to Shopify'}</button><p class="xs mute" style="margin-bottom:0">Closing locks the drawer for ${V.fd(r.date)} and produces the Z-report.${V.basic?'':' Bills are queued for sync.'}</p>`)}</div></div>
 ${V.card('Previous day-ends','Last 10 at this location',V.table('dh',{search:false,rows:d.drawers.filter(x=>x.loc===loc.id&&x.status==='closed').slice(-10).reverse(),cols:[{k:'date',l:'Date',fmt:'date'},{k:'by',l:'Closed by',f:r=>V.L.userName(r.closing.by),v:r=>r.closing.by},{k:'exp',l:'Expected',f:r=>V.inr(r.closing.expected),v:r=>r.closing.expected,n:true},{k:'cnt',l:'Counted',f:r=>V.inr(r.closing.counted),v:r=>r.closing.counted,n:true},{k:'v',l:'Variance',f:r=>V.badge(V.inr(r.closing.variance),r.closing.variance?'warn':'ok'),v:r=>r.closing.variance}],onRow:r=>V.printHtml(V.zHtml(r),'Z-Report')}),'mt')}`}});
V.acts.zPrint=()=>V.printHtml(V.zHtml(todayDr(V.curLoc().id)),'Z-Report');
V.acts.deClose=async()=>{const loc=V.curLoc().id,r=todayDr(loc),st=V.S.de,counted=V.sum(V.DENOM,k=>k*(+st.den[k]||0)),c=V.L.drawerCalc(r),v=counted-c.expected;
 if(v!==0&&!st.note.trim()){V.toast('Please explain the variance in notes','bad');return}
 if(!await V.confirm(`Close the day at <b>${V.esc(V.curLoc().name)}</b>?<br>Counted ${V.inr(counted)} vs expected ${V.inr(c.expected)} (variance ${V.inr(v)}).`,'Close day'))return;
 const drop=Math.max(0,Math.floor(counted/1000)*1000-r.float);if(drop>0)r.entries.push({t:'drop',amt:drop,reason:'End-of-day safe drop',time:V.now(),by:r.openedBy});
 V.L.closeDrawer(r,{counted,denom:st.den,by:V.S.user,note:st.note});V.S.de=null;
 let ok=0;if(V.db.settings.autoSync&&!V.basic){V.db.sync.filter(s=>s.status==='Pending'&&s.loc===loc&&s.t.slice(0,10)<=V.db.today).forEach(s=>{if(V.L.syncRun(s))ok++})}
 const s=V.L.syncAdd('Inventory','Stock levels '+V.db.today,loc,V.db.pieces.filter(p=>p.loc===loc&&p.status==='in_stock').length);if(V.db.settings.autoSync&&!V.basic)V.L.syncRun(s);
 V.save();V.toast(V.basic?'Day closed — Z-report ready':`Day closed · ${ok} order(s) synced to Shopify`);V.refresh()};

// ================= PETTY CASH =================
V.page('petty',{title:'Petty Cash',crumb:'POS & Cash',
render(){const d=V.db,loc=V.curLoc(),rows=d.petty.filter(p=>p.loc===loc.id).slice().reverse(),bal=V.L.pettyBal(loc.id),exp=rows.filter(p=>p.type==='expense'),m30=exp.filter(p=>V.diff(d.today,p.date)<30);
 return V.head('Petty Cash & Expenses','Imprest-based petty cash per location. Every voucher carries a head and bill reference.',`<button class="btn" data-act="pcTop">${V.ic('plus')} Top-up float</button><button class="btn primary" data-act="pcNew">${V.ic('plus')} New expense</button>`)
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'Imprest balance',n:bal,f:'inr',ic:'wallet',c:bal<2000?'#B3261E':'#2E8B57',sub:bal<2000?'Low — top up':'in the petty cash box'})}${V.kpi({l:'Spent · last 30 days',n:V.sum(m30,p=>p.amt),f:'inr',ic:'cash',c:V.brand.primary,sub:m30.length+' vouchers'})}${V.kpi({l:'Largest head',n:Math.max(0,...Object.values(V.petHeads(exp)))||0,f:'inr',ic:'chart',c:'#1E2A5E',sub:(Object.entries(V.petHeads(exp)).sort((a,b)=>b[1]-a[1])[0]||['—'])[0]})}${V.kpi({l:'Top-ups',n:V.sum(rows.filter(p=>p.type==='topup'),p=>p.amt),f:'short',ic:'return',c:V.brand.accent,sub:'drawn from drawer'})}</div>
 ${V.basic?'':`<div class="g g21">${V.card('Expense by head',V.esc(loc.name),'<div class="cw sm"><canvas id="c-pc"></canvas></div>')}${V.card('Daily spend','Last 20 days','<div class="cw sm"><canvas id="c-pd"></canvas></div>')}</div>`}`
 +V.table('pc',{rows,cols:[{k:'id',l:'Voucher',f:r=>`<b>${r.id}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'head',l:'Head'},{k:'desc',l:'Description'},{k:'bill',l:'Bill',f:r=>r.bill||'<span class="mute">—</span>',v:r=>r.bill},{k:'by',l:'Spent by',f:r=>V.L.userName(r.by),v:r=>r.by},{k:'ap',l:'Approved',f:r=>r.approvedBy?V.L.userName(r.approvedBy):'—',v:r=>r.approvedBy},{k:'amt',l:'Amount',f:r=>`<b style="color:${r.type==='topup'?'var(--ok)':'var(--ink)'}">${r.type==='topup'?'+':'−'}${V.inr(r.amt)}</b>`,v:r=>r.type==='topup'?r.amt:-r.amt}]})},
mount(){const loc=V.curLoc().id,exp=V.db.petty.filter(p=>p.loc===loc&&p.type==='expense'),h=V.petHeads(exp),k=Object.keys(h);V.chart('c-pc',{type:'doughnut',labels:k,data:[{data:k.map(x=>h[x])}],tipFmt:V.inr});
 const days=Array.from({length:20},(_,i)=>V.addDays(V.db.today,i-19));V.chart('c-pd',{labels:days.map(V.fds),data:[{label:'Spend',data:days.map(x=>V.sum(exp.filter(p=>p.date===x),p=>p.amt)),color:V.brand.accent}],fmt:V.inr,legend:false})}});
V.petHeads=a=>{const m={};a.forEach(p=>m[p.head]=(m[p.head]||0)+p.amt);return m};
V.acts.pcNew=()=>V.modal({title:'New petty cash expense',wide:true,body:`<div class="frm">${V.field('Head',`<select name="head">${V.opts(V.HEADS,'')}</select>`)}${V.field('Amount (₹) *','<input name="amt" type="number" min="1">')}${V.field('Description *','<input name="desc">','','full')}${V.field('Bill / voucher no.','<input name="bill">')}${V.field('Receipt photo','<input type="file" accept="image/*,.pdf" name="file">','Attach bill image (demo — not uploaded)')}</div>`,
 foot:[{l:'Cancel'},{l:'Save expense',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['amt','desc']))return false;const a=+v.amt,loc=V.curLoc().id;if(a>V.L.pettyBal(loc)){V.toast('Insufficient imprest balance — top up first','bad');return false}
  const post=()=>{V.L.pettyAdd({loc,date:V.db.today,head:v.head,desc:v.desc,amt:a,by:V.S.user,bill:v.bill});V.save();V.toast('Expense recorded');V.refresh()};
  if(!V.basic&&a>2000){setTimeout(()=>V.pinGate(`Expense of ${V.inr(a)} exceeds ₹2,000 and needs approval.`,post),60)}else post()}}]});
V.acts.pcTop=()=>V.modal({title:'Top-up petty cash float',body:`<div class="frm">${V.field('Amount (₹) *','<input id="pta" type="number" min="1" value="10000">','Drawn from the cash drawer (cash-out entry created)','full')}</div>`,foot:[{l:'Cancel'},{l:'Top up',cls:'primary',fn:()=>{const a=+$('#pta').value,loc=V.curLoc().id,r=todayDr(loc);if(!r||r.status!=='open'){V.toast('Open the drawer first','bad');return false}if(!(a>0)||a>V.L.drawerCalc(r).expected){V.toast('Amount exceeds drawer cash','bad');return false}V.L.pettyAdd({loc,date:V.db.today,head:'Imprest top-up',desc:'Cash drawn from drawer',amt:a,type:'topup',by:V.S.user});V.save();V.toast('Float topped up');V.refresh()}}]});

// ================= SHOPIFY =================
const orderPayload=s=>{const inv=V.m.inv[s.ref];if(!inv)return {type:s.type,ref:s.ref,amount:s.amt};const c=inv.cust?V.m.cust[inv.cust]:null;
 return {order:{name:'#VK-'+(4000+V.hash(inv.no)%5000),source_name:V.slug()+'-pos',location:V.m.loc[inv.loc].shopifyLoc,created_at:inv.date+'T'+inv.time+':00+05:30',currency:'INR',financial_status:'paid',customer:c?{first_name:c.name.split(' ')[0],last_name:c.name.split(' ').slice(1).join(' '),phone:c.phone,email:c.email}:null,
  line_items:inv.lines.map(l=>({sku:l.sku,title:l.name,quantity:l.qty,price:l.mrp.toFixed(2),total_discount:l.disc.toFixed(2),properties:[{name:'Serial',value:l.no}],tax_lines:[{title:'GST',rate:l.gst/100,price:l.tax.toFixed(2)}]})),
  tax_lines:inv.inter?[{title:'IGST',price:inv.igst.toFixed(2)}]:[{title:'CGST',price:inv.cgst.toFixed(2)},{title:'SGST',price:inv.sgst.toFixed(2)}],transactions:inv.pays.map(p=>({kind:'sale',gateway:p.mode,amount:p.amt.toFixed(2),authorization:p.ref||null})),total_price:inv.net.toFixed(2),note:'Invoice '+inv.no}}};
V.page('shopify',{title:'Shopify Sync',crumb:'Integrations',
render(){const d=V.db,tab=V.basic?(V.S.shTab==='queue'?'queue':'files'):(V.S.shTab||'console'),S=d.settings,cnt=s=>d.sync.filter(x=>x.status===s).length;
 const tabs=`<div class="tabs" role="tablist">${[['console','Console'],['queue','Sync queue'],['mapping','Mapping'],['files','File export'],['setup','Connection']].filter(x=>!V.basic||['queue','files'].includes(x[0])).map(x=>`<button class="${tab===x[0]?'on':''}" data-act="shTab" data-t="${x[0]}" role="tab">${x[1]}</button>`).join('')}</div>`;
 let body='';
 if(tab==='console'){const days=Array.from({length:14},(_,i)=>V.addDays(d.today,i-13));
  body=`<div class="g g4">${V.kpi({l:'Synced',n:cnt('Synced'),ic:'check',c:'#2E8B57',sub:V.pct(cnt('Synced'),d.sync.length)+'% of records'})}${V.kpi({l:'Pending',n:cnt('Pending'),ic:'clock',c:V.brand.accent,sub:'waiting for sync / day-end'})}${V.kpi({l:'Failed',n:cnt('Failed'),ic:'alert',c:'#B3261E',sub:'need mapping or retry'})}${V.kpi({l:'Mode',n:0,ic:'link',c:'#1E2A5E',sub:S.shopifyMode==='api'?'Live API (auto)':'File upload'}).replace('>0<','>'+(S.shopifyMode==='api'?'API':'File')+'<')}</div>
  <div class="card mt"><div class="row between"><div><h3>Data flow</h3><div class="sub">Operational stock lives here; sales, customers and inventory levels are pushed to Shopify</div></div><div class="row"><div class="seg" role="group"><button class="${S.shopifyMode==='api'?'on':''}" data-act="shMode" data-m="api">${V.ic('link')} API integration</button><button class="${S.shopifyMode==='file'?'on':''}" data-act="shMode" data-m="file">${V.ic('file')} File upload</button></div><button class="btn primary" data-act="shSyncAll" ${cnt('Pending')+cnt('Failed')?'':'disabled'}>${V.ic('sync')} Sync ${cnt('Pending')+cnt('Failed')} now</button></div></div>
  <svg viewBox="0 0 900 150" width="100%" style="margin-top:10px" role="img" aria-label="Data flow from the app to Shopify"><defs><linearGradient id="gl" x1="0" x2="1"><stop offset="0" stop-color="#7A1F3D"/><stop offset="1" stop-color="#2E8B57"/></linearGradient></defs>
  <rect x="10" y="30" width="200" height="90" rx="16" fill="${V.brand.primary}"/><text x="110" y="70" text-anchor="middle" fill="#fff" font-family="Cormorant Garamond,serif" font-size="26" font-weight="700">${V.esc(V.brand.name)}</text><text x="110" y="94" text-anchor="middle" fill="#E3C57A" font-size="12">POS · Inventory · Exhibitions</text>
  <rect x="690" y="30" width="200" height="90" rx="16" fill="#2E8B57"/><text x="790" y="70" text-anchor="middle" fill="#fff" font-size="24" font-weight="700">Shopify</text><text x="790" y="94" text-anchor="middle" fill="#E6F6EC" font-size="12">Orders · Customers · Inventory</text>
  <path d="M215 60 C 330 20, 570 20, 685 60" stroke="url(#gl)" stroke-width="3" fill="none" stroke-dasharray="6 6"><animate attributeName="stroke-dashoffset" from="24" to="0" dur="1.2s" repeatCount="indefinite"/></path><path d="M215 92 C 330 132, 570 132, 685 92" stroke="url(#gl)" stroke-width="3" fill="none" stroke-dasharray="6 6"><animate attributeName="stroke-dashoffset" from="24" to="0" dur="1.6s" repeatCount="indefinite"/></path>
  <g font-size="12" fill="var(--ink2)" text-anchor="middle"><text x="450" y="22">Orders · Refunds · Customers</text><text x="450" y="146">Inventory levels by location</text></g><circle r="5" fill="#E3C57A"><animateMotion dur="3s" repeatCount="indefinite" path="M215 60 C 330 20, 570 20, 685 60"/></circle><circle r="5" fill="#E3C57A"><animateMotion dur="3.6s" repeatCount="indefinite" path="M215 92 C 330 132, 570 132, 685 92"/></circle></svg>
  <div class="login-note" id="shprog" hidden></div></div>
  <div class="g g21 mt">${V.card('Sync activity','Records processed per day','<div class="cw sm"><canvas id="c-sh"></canvas></div>')}${V.card('Needs attention','Latest failures',cnt('Failed')?d.sync.filter(s=>s.status==='Failed').slice(-5).reverse().map(s=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><div class="row between"><b class="sm">${s.ref}</b>${V.badge('Failed','bad')}</div><div class="xs" style="color:var(--bad)">${V.esc(s.err)}</div></div>`).join('')+`<button class="btn sm mt" data-act="shTab" data-t="mapping">Fix mapping →</button>`:'<p class="mute">No failures 🎉</p>')}</div>`}
 else if(tab==='queue'){const f=V.S.shF||'ALL';body=`<div class="row" style="margin-bottom:12px"><div class="seg">${['ALL','Pending','Failed','Synced'].filter(x=>!V.basic||x!=='Failed').map(x=>`<button class="${f===x?'on':''}" data-act="shF" data-f="${x}">${x==='ALL'?'All':x} ${x==='ALL'?'':'· '+cnt(x)}</button>`).join('')}</div>${cnt('Failed')&&!V.basic?`<button class="btn sm" data-act="shRetry">${V.ic('sync')} Retry all failed</button>`:''}</div>`
  +V.table('shq',{rows:d.sync.filter(s=>f==='ALL'||s.status===f).slice().reverse().map(s=>Object.assign({},s,{ln:V.m.loc[s.loc]?V.m.loc[s.loc].city:s.loc})),cols:[{k:'id',l:'ID',f:r=>`<b>${r.id}</b>`},{k:'t',l:'Created'},{k:'type',l:'Type',fmt:'badge'},{k:'ref',l:'Reference'},{k:'ln',l:'Location'},{k:'amt',l:'Amount',fmt:'inr'},{k:'shopifyRef',l:'Shopify ref',f:r=>r.shopifyRef||'—',v:r=>r.shopifyRef},{k:'status',l:'Status',fmt:'badge'}].concat(V.basic?[]:[{k:'err',l:'Error',f:r=>r.err?`<span style="color:var(--bad)" class="xs">${V.esc(r.err)}</span>`:''},{k:'a',l:'',nosort:true,f:r=>`<button class="btn sm" data-act="shView" data-id="${r.id}">Payload</button>${r.status!=='Synced'?` <button class="btn sm" data-act="shOne" data-id="${r.id}">Push</button>`:''}`}])})}
 else if(tab==='mapping'){const un=d.items.filter(i=>!i.shopify);body=`<div class="g g2">${V.card('Design → Shopify variant','Unmapped designs block order sync',V.table('shm',{rows:d.items,cols:[{k:'sku',l:'SKU',f:r=>`<b>${r.sku}</b>`},{k:'name',l:'Design'},{k:'handle',l:'Shopify handle'},{k:'shopify',l:'Status',f:r=>r.shopify?V.badge('Mapped','ok'):`<button class="btn sm primary" data-act="shMap" data-sku="${r.sku}">Create & map</button>`,v:r=>r.shopify?'Mapped':'Unmapped'}],pageSize:10}))}
  <div class="g" style="gap:18px">${V.card('Location → Shopify location','State-wise registrations map to separate Shopify locations',`<div class="tscroll"><table class="t"><tbody>${d.locations.map(l=>`<tr><td><b>${V.esc(l.name)}</b><div class="xs mute">${l.gstin}</div></td><td>${l.shopifyLoc?V.badge(l.shopifyLoc,'ok'):`<button class="btn sm primary" data-act="shLoc" data-id="${l.id}">Map location</button>`}</td></tr>`).join('')}</tbody></table></div>`)}
  ${V.card('Payment gateway mapping','',`<div class="tscroll"><table class="t"><tbody>${[['Cash','Cash on delivery (manual)'],['UPI','Razorpay UPI'],['Card','HDFC POS terminal'],['Bank Transfer','Bank deposit'],['EMI','Bajaj Finserv EMI'],['Cheque','Manual — cheque'],['Store Credit','Gift card / store credit']].map(r=>`<tr><td>${r[0]}</td><td>→ ${r[1]}</td></tr>`).join('')}</tbody></table></div>`)}</div></div>`}
 else if(tab==='files'){body=V.card('File-based sync','Download files in Shopify import format and upload them in Shopify Admin → Orders / Inventory / Customers.',`<div class="g ${V.basic?'g3':'g4'}">${[['orders','Orders','receipt','Sales with line items, taxes & payments'],['inventory','Inventory levels','box','On-hand by Shopify location'],['customers','Customers','users','New & updated customers'],['products','Products','tag','Designs with price & handle']].filter(x=>!V.basic||x[0]!=='products').map(x=>`<div class="card flat"><div class="kpi"><div class="ico">${V.ic(x[2])}</div></div><h4>${x[1]}</h4><p class="mute sm">${x[3]}</p><button class="btn primary sm" data-act="shExport" data-k="${x[0]}">${V.ic('download')} Download CSV</button></div>`).join('')}</div><div class="field mt"><label><input type="checkbox" id="shmark" checked> Mark exported orders as uploaded to Shopify</label></div>`)
  +(V.basic?'':V.card('Export history','',V.table('shx',{rows:d.exports.slice().reverse(),search:false,cols:[{k:'t',l:'When'},{k:'user',l:'By',f:r=>V.L.userName(r.user),v:r=>r.user},{k:'kind',l:'File'},{k:'rows',l:'Rows',fmt:'num'},{k:'file',l:'File name'}]}),'mt'))}
 else body=V.card('Connection','Shopify Admin API credentials (demo — nothing is sent)',`<div class="frm">${V.field('Store domain','<input data-st="x" value="'+V.esc(S.shopifyDomain)+'" disabled>')}${V.field('Status',`<div>${V.badge('Connected (demo)','ok')}</div>`)}${V.field('Admin API access token','<input type="password" value="shpat_••••••••••••••••" disabled>')}${V.field('API version','<input value="2025-01" disabled>')}</div><div class="login-note">In production this screen stores your private-app token and webhook secret. Scopes needed: <code>write_orders, write_customers, write_inventory, write_products, read_locations</code>.</div>
  <h4 style="margin:18px 0 8px">Invoice authority <span class="ribbon">Premium option</span></h4><div class="seg">${[['POS','POS issues GST invoice'],['Shopify','Shopify issues invoice'],['Both','Both (cross-referenced)']].map(x=>`<button class="${S.invoiceAuthority===x[0]?'on':''}" data-act="shAuth" data-a="${x[0]}">${x[1]}</button>`).join('')}</div><p class="mute sm">Decision can be finalised during the demo — the data model supports all three.</p>`);
 return V.head('Shopify Sync',''+(V.basic?'Download orders, inventory levels and customers in <b>Shopify import format</b> and upload them in Shopify Admin. Every bill is tracked as pending until exported.':'Push sales, refunds, customers and inventory levels to Shopify via <b>API</b> or <b>file upload</b>. Everything is queued, logged and retryable.'))+tabs+body},
mount(){if((V.S.shTab||'console')==='console'){const days=Array.from({length:14},(_,i)=>V.addDays(V.db.today,i-13)),ty=['Order','Refund','Customer','Inventory'];V.chart('c-sh',{type:'bar',stacked:true,labels:days.map(V.fds),data:ty.map((t,i)=>({label:t,data:days.map(x=>V.db.sync.filter(s=>s.type===t&&s.t.slice(0,10)===x).length),color:V.PAL[i]}))})}}});
V.acts.shTab=el=>{V.S.shTab=el.dataset.t;V.refresh()};V.acts.shF=el=>{V.S.shF=el.dataset.f;V.refresh()};
V.acts.shMode=el=>{V.db.settings.shopifyMode=el.dataset.m;V.save();V.toast('Sync mode: '+(el.dataset.m==='api'?'API':'File upload'));V.refresh()};
V.acts.shAuth=el=>{V.db.settings.invoiceAuthority=el.dataset.a;V.save();V.refresh()};
V.acts.shOne=el=>{const s=V.db.sync.find(x=>x.id===el.dataset.id);const ok=V.L.syncRun(s);V.save();V.toast(ok?s.id+' synced':s.err,ok?'ok':'bad');V.refresh()};
V.acts.shRetry=()=>{let ok=0,f=0;V.db.sync.filter(s=>s.status==='Failed').forEach(s=>V.L.syncRun(s)?ok++:f++);V.save();V.toast(`${ok} synced, ${f} still failing`,f?'bad':'ok');V.refresh()};
V.acts.shSyncAll=()=>{const q=V.db.sync.filter(s=>s.status!=='Synced'),box=$('#shprog');box.hidden=false;let i=0,ok=0,bad=0;const step=()=>{if(i>=q.length){V.save();V.toast(`Sync complete — ${ok} pushed, ${bad} failed`,bad?'bad':'ok');V.refresh();return}V.L.syncRun(q[i])?ok++:bad++;i++;box.innerHTML=`Syncing ${i}/${q.length}… <div class="bar" style="margin-top:6px"><i style="width:${i/q.length*100}%"></i></div>`;setTimeout(step,q.length>40?15:60)};step()};
V.acts.shView=el=>{const s=V.db.sync.find(x=>x.id===el.dataset.id);V.modal({title:'Payload · '+s.id,wide:true,body:`<p class="mute sm">${V.db.settings.shopifyMode==='api'?'POST /admin/api/2025-01/orders.json':'Row in orders CSV'}</p><pre style="background:#1d1620;color:#f3e7d6;padding:16px;border-radius:12px;overflow:auto;max-height:420px;font-size:12px">${V.esc(JSON.stringify(orderPayload(s),null,2))}</pre>${s.err?`<div class="login-note" style="border-color:var(--bad)">${V.esc(s.err)}</div>`:''}`})};
V.acts.shMap=el=>{const it=V.m.item[el.dataset.sku];it.shopify=true;V.toast(it.sku+' mapped to Shopify');V.save();V.refresh()};
V.acts.shLoc=el=>{const l=V.m.loc[el.dataset.id];l.shopifyLoc='Shopify · '+l.city;V.save();V.refresh()};
V.acts.shExport=el=>{const k=el.dataset.k,d=V.db,mark=$('#shmark')&&$('#shmark').checked;let cols,rows,name;
 if(k==='orders'){const pend=d.sync.filter(s=>s.type==='Order'&&s.status!=='Synced'),invs=pend.map(s=>V.m.inv[s.ref]).filter(Boolean);name='shopify_orders_'+d.today+'.csv';cols=['Name','Email','Financial Status','Paid at','Fulfillment Status','Currency','Subtotal','Taxes','Total','Discount Amount','Payment Method','Lineitem quantity','Lineitem name','Lineitem price','Lineitem sku','Lineitem discount','Billing Name','Billing Phone','Notes','Location','Tags'].map(l=>({l,k:l}));
  rows=invs.flatMap(i=>{const c=i.cust?V.m.cust[i.cust]:null;return i.lines.map((l,j)=>({'Name':'#VK-'+(4000+V.hash(i.no)%5000),'Email':c?c.email:'','Financial Status':'paid','Paid at':i.date+' '+i.time+' +0530','Fulfillment Status':'fulfilled','Currency':'INR','Subtotal':j?'':i.taxable.toFixed(2),'Taxes':j?'':(i.net-i.taxable).toFixed(2),'Total':j?'':i.net.toFixed(2),'Discount Amount':j?'':i.disc.toFixed(2),'Payment Method':j?'':i.pays.map(p=>p.mode).join(' + '),'Lineitem quantity':l.qty,'Lineitem name':l.name+' ['+l.no+']','Lineitem price':l.mrp.toFixed(2),'Lineitem sku':l.sku,'Lineitem discount':l.disc.toFixed(2),'Billing Name':c?c.name:'Walk-in','Billing Phone':c?c.phone:'','Notes':i.no,'Location':V.m.loc[i.loc].shopifyLoc,'Tags':'pos,'+V.m.loc[i.loc].code}))});
  if(mark)pend.forEach(s=>{s.status='Synced';s.shopifyRef='FILE';s.err='';if(V.m.inv[s.ref])V.m.inv[s.ref].sync='Synced'})}
 else if(k==='inventory'){name='shopify_inventory_'+d.today+'.csv';cols=['Handle','Title','Option1 Name','Option1 Value','SKU','HS Code','Location','On hand (new)'].map(l=>({l,k:l}));rows=[];d.items.forEach(it=>d.locations.forEach(l=>{if(!l.shopifyLoc)return;const n=d.pieces.filter(p=>p.sku===it.sku&&p.loc===l.id&&p.status==='in_stock').reduce((s,p)=>s+p.qty,0);if(n)rows.push({'Handle':it.handle,'Title':it.name,'Option1 Name':'Title','Option1 Value':'Default Title','SKU':it.sku,'HS Code':it.hsn,'Location':l.shopifyLoc,'On hand (new)':n})}))}
 else if(k==='customers'){name='shopify_customers_'+d.today+'.csv';cols=['First Name','Last Name','Email','Phone','Default Address City','Default Address Province Code','Default Address Country Code','Tags','Note','Accepts Email Marketing'].map(l=>({l,k:l}));rows=d.customers.map(c=>({'First Name':c.name.split(' ')[0],'Last Name':c.name.split(' ').slice(1).join(' '),'Email':c.email,'Phone':'+91'+c.phone,'Default Address City':c.city,'Default Address Province Code':V.STATES[c.state],'Default Address Country Code':'IN','Tags':c.tier+(c.gstin?',B2B':''),'Note':c.notes,'Accepts Email Marketing':'yes'}))}
 else{name='shopify_products_'+d.today+'.csv';cols=['Handle','Title','Body (HTML)','Vendor','Type','Tags','Published','Option1 Name','Option1 Value','Variant SKU','Variant Price','Variant Inventory Tracker','Variant Inventory Qty','Variant Taxable'].map(l=>({l,k:l}));rows=d.items.map(it=>({'Handle':it.handle,'Title':it.name,'Body (HTML)':`<p>${it.fabric}. ${it.zari}. ${it.cert}</p>`,'Vendor':it.region||'Meenakshi Heritage','Type':it.cat,'Tags':[it.weave&&V.m.weave[it.weave].name,it.colour].filter(Boolean).join(','),'Published':'true','Option1 Name':'Title','Option1 Value':'Default Title','Variant SKU':it.sku,'Variant Price':it.mrp.toFixed(2),'Variant Inventory Tracker':'shopify','Variant Inventory Qty':d.pieces.filter(p=>p.sku===it.sku&&p.status==='in_stock').reduce((s,p)=>s+p.qty,0),'Variant Taxable':'true'}))}
 if(mark&&(k==='inventory'||k==='customers'))d.sync.filter(s=>s.type===(k==='inventory'?'Inventory':'Customer')&&s.status!=='Synced').forEach(s=>{s.status='Synced';s.shopifyRef='FILE';s.err=''});V.dl(name,V.csvOf(cols,rows));d.exports.push({t:d.today+' '+V.now(),user:V.S.user,kind:k+' CSV (Shopify format)',rows:rows.length,file:name});V.save();V.toast(`${rows.length} rows exported`);V.refresh()};

// ================= GST =================
V.page('gst',{title:'GST & E-way',crumb:'Insights',
render(){const d=V.db,inv=d.invoices;const byLoc=V.group(inv,i=>V.m.loc[i.loc].gstin);
 const regs=[...byLoc].map(([g,a])=>({gstin:g,state:V.m.loc[a[0].loc].state,inv:a.length,taxable:V.sum(a,i=>i.taxable),cgst:V.sum(a,i=>i.cgst),sgst:V.sum(a,i=>i.sgst),igst:V.sum(a,i=>i.igst),total:V.sum(a,i=>i.net)}));
 const hsn=V.group(inv.flatMap(i=>i.lines),l=>l.hsn+'|'+l.gst);const hrows=[...hsn].map(([k,a])=>({hsn:k.split('|')[0],rate:+k.split('|')[1],qty:V.sum(a,l=>l.qty),taxable:V.sum(a,l=>l.taxable),tax:V.sum(a,l=>l.tax),total:V.sum(a,l=>l.net)}));
 const itc=V.sum(d.grns.filter(g=>V.m.vendor[g.vendor].gstin),g=>g.value*.05)+V.sum(d.localPurchases,l=>l.gst),out=V.sum(inv,i=>i.net-i.taxable);
 const ewb=d.transfers.filter(t=>t.ewb);
 return V.head('GST & E-way Bills','State-wise registrations: every plant bills under its own GSTIN. GSTR-1 ready data, HSN summary, ITC and e-way bill register.')
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'Output GST',n:out,f:'short',ic:'coins',c:V.brand.primary,sub:'collected on sales'})}${V.kpi({l:'Input tax credit',n:itc,f:'short',ic:'return',c:'#2E8B57',sub:'GRN + local purchases'})}${V.kpi({l:'Net payable',n:out-itc,f:'short',ic:'wallet',c:'#1E2A5E',sub:'before returns / RCM'})}${V.kpi({l:'E-way bills',n:ewb.length,ic:'truck',c:V.brand.accent,sub:'inter-state transfers'})}</div>`
 +`<div class="g g3">${regs.map(r=>`<div class="card motif-edge" style="padding-bottom:26px"><span class="badge gold">${V.ic('shield')} ${r.state}</span><h3 style="margin-top:8px;font-family:monospace;font-size:17px">${r.gstin}</h3><dl class="kv"><dt>Invoices</dt><dd>${r.inv}</dd><dt>Taxable</dt><dd>${V.inr(r.taxable)}</dd><dt>CGST + SGST</dt><dd>${V.inr(r.cgst)} + ${V.inr(r.sgst)}</dd><dt>IGST</dt><dd>${V.inr(r.igst)}</dd></dl></div>`).join('')}</div>`
 +V.card('HSN-wise summary','GSTR-1 table 12',V.table('hsn',{search:false,rows:hrows,cols:[{k:'hsn',l:'HSN'},{k:'rate',l:'Rate',fmt:'pct'},{k:'qty',l:'Qty',fmt:'num'},{k:'taxable',l:'Taxable value',fmt:'inr'},{k:'tax',l:'Tax',fmt:'inr'},{k:'total',l:'Invoice value',fmt:'inr'}],totals:['qty','taxable','tax','total']}),'mt')
 +V.card('E-way bill register','Inter-state stock transfers above ₹50,000',V.table('ewb',{search:false,rows:ewb.slice().reverse(),cols:[{k:'ewb',l:'E-way bill',f:r=>`<b style="font-family:monospace">${r.ewb}</b>`},{k:'no',l:'Transfer'},{k:'date',l:'Date',fmt:'date'},{k:'route',l:'Route',f:r=>V.esc(V.m.loc[r.from].state+' → '+V.m.loc[r.to].state),v:r=>r.from+r.to},{k:'value',l:'Value',fmt:'inr'},{k:'status',l:'Status',fmt:'badge'}],pageSize:6}),'mt')}});

// ================= APPROVALS =================
V.page('approvals',{title:'Approvals',crumb:'Admin',
render(){const d=V.db,pend=d.approvals.filter(a=>a.status==='Pending');
 return V.head('Approvals Inbox','Discount overrides, large write-offs, new POs and inter-state transfers waiting for a decision.')
 +(pend.length?`<div class="g g2">${pend.map(a=>`<div class="card"><div class="row between"><span class="badge gold">${a.type}</span><span class="xs mute">${V.fd(a.date)} · ${V.L.userName(a.by)}</span></div><h3 style="margin:8px 0 2px">${V.esc(a.ref)}</h3><p class="mute sm">${V.esc(a.note)}</p><div class="row between"><b style="font-size:20px">${V.inr(a.amt)}</b><div class="row"><button class="btn sm danger" data-act="apDo" data-id="${a.id}" data-r="Rejected">Reject</button><button class="btn sm primary" data-act="apDo" data-id="${a.id}" data-r="Approved">${V.ic('check')} Approve</button></div></div></div>`).join('')}</div>`:`<div class="card"><div class="empty">${V.art.empty()}<div>Inbox zero — nothing waiting.</div></div></div>`)
 +V.card('History','Past decisions',V.table('aph',{rows:d.approvals.filter(a=>a.status!=='Pending').slice().reverse(),cols:[{k:'id',l:'ID'},{k:'type',l:'Type'},{k:'ref',l:'Reference'},{k:'by',l:'Requested by',f:r=>V.L.userName(r.by),v:r=>r.by},{k:'amt',l:'Amount',fmt:'inr'},{k:'status',l:'Decision',fmt:'badge'},{k:'decidedBy',l:'By',f:r=>V.L.userName(r.decidedBy),v:r=>r.decidedBy}],pageSize:8}),'mt')}});
V.acts.apDo=el=>{const a=V.db.approvals.find(x=>x.id===el.dataset.id);a.status=el.dataset.r;a.decidedBy=V.S.user;a.decidedOn=V.db.today;if(a.type==='Purchase Order'&&a.status==='Approved'&&V.m.po[a.ref]){V.m.po[a.ref].status='Approved';V.m.po[a.ref].approvedBy=V.S.user}V.L.audit('Approval '+a.status,a.id);V.save();V.toast(a.id+' '+a.status.toLowerCase());V.refresh()};

// ================= IMPORT CENTRE =================
const IMPORTS={
 items:{t:'Item master',head:['Design Name','Weave Code','Colour','MRP','Std Cost','Tracking'],sample:[['Kanjivaram Mango Pallu Special','KJV','Wine',165000,102000,'serial'],['Banarasi Kadhua Bridal','BNR','Rani Pink',148000,92000,'serial'],['Silk Dupatta Zari','','Indigo',6800,3700,'batch'],['Bad row','XXX','Wine','',0,'serial']],
  check:r=>{const e=[];if(!r[0])e.push('Name missing');if(r[1]&&!V.m.weave[r[1]])e.push('Unknown weave code');if(!(+r[3]>0))e.push('MRP invalid');if(!V.COLOURS.find(c=>c[0]===r[2]))e.push('Unknown colour');return e},
  commit:r=>{const w=V.m.weave[r[1]],c=V.COLOURS.find(x=>x[0]===r[2]),code=r[1]||'ACC',n=V.db.items.filter(i=>i.sku.startsWith(code+'-')).length+1;V.db.items.push({sku:code+'-'+String(n).padStart(2,'0'),name:r[0],weave:r[1]||'',colour:r[2],body:c[1],bord:c[2],cat:r[1]?'Saree':'Accessory',fabric:w?w.fabric:'—',zari:w?w.zari:'',hsn:w?w.hsn:'6217',gst:w?5:12,mrp:+r[3],cost:+r[4]||Math.round(r[3]*.62),trk:r[5]||'serial',len:'6.3 m',cert:w?w.cert:'',pat:w?w.pat:'butta',region:w?w.region:'',shopify:false,active:true,handle:String(r[0]).toLowerCase().replace(/[^a-z0-9]+/g,'-')})}},
 customers:{t:'Customers',head:['Name','Mobile','Email','City','State'],sample:[['Harini Venkat','9876501234','harini@mail.in','Chennai','Tamil Nadu'],['Rukmini Bhat','9845012345','rukmini@mail.in','Bengaluru','Karnataka'],['Bad Mobile','12345','x@mail.in','Pune','Maharashtra']],
  check:r=>{const e=[];if(!r[0])e.push('Name missing');if(!/^\d{10}$/.test(String(r[1])))e.push('Mobile must be 10 digits');if(V.db.customers.some(c=>c.phone===String(r[1])))e.push('Duplicate mobile');if(!V.STATES[r[4]])e.push('Unknown state');return e},
  commit:r=>{V.db.customers.push({id:'C'+String(V.db.customers.length+1).padStart(4,'0'),name:r[0],phone:String(r[1]),email:r[2],city:r[3],state:r[4],gstin:'',company:'',dob:'',anniv:'',prefs:{weaves:['KJV'],colour:'Temple Maroon',budget:[50000,200000]},since:V.db.today,tier:'Silver',credit:0,loyalty:0,spend:0,notes:'',consent:true})}},
 opening:{t:'Opening stock',head:['Design SKU','Qty','Cost','MRP','Location'],sample:[['KJV-01',3,63000,98000,'MAIN'],['BNR-03',2,70000,112000,'MAIN'],['PTL-02',1,215000,320000,'VAULT'],['KJV-77',2,50000,80000,'MAIN']],
  check:r=>{const e=[];if(!V.m.item[r[0]])e.push('SKU not in Item Master');if(!(+r[1]>0))e.push('Qty invalid');if(!V.m.loc[r[4]])e.push('Unknown location');return e},
  commit:null}};
V.page('imports',{title:'Import Centre',crumb:'Admin',
render(){return V.head('Excel Import Centre','Bring in masters and opening balances from your existing Excel files. Every row is validated and errors are shown before anything is written.')
 +`<div class="g g3">${Object.entries(IMPORTS).map(([k,v])=>`<div class="card fam"><div class="fi" style="background:linear-gradient(135deg,#7A1F3D,#1E2A5E)">${V.ic(k==='items'?'tag':k==='customers'?'users':'box')}</div><h3>${v.t}</h3><p class="mute sm">Columns: ${v.head.join(' · ')}</p><div class="row"><button class="btn sm" data-act="imTpl" data-k="${k}">${V.ic('download')} Template</button><button class="btn sm primary" data-act="imGo" data-k="${k}">${V.ic('upload')} Import</button></div></div>`).join('')}${V.card('Purchase orders','Vendor PO upload lives in Procurement',`<p class="mute sm">Columns: Vendor Code · Design SKU · Qty · Rate · Expected Date · Remarks</p><button class="btn sm gold" data-act="poUpload">${V.ic('upload')} Upload PO</button>`,'fam')}</div>`}});
V.acts.imTpl=el=>{const m=IMPORTS[el.dataset.k];if(window.XLSX){const ws=XLSX.utils.aoa_to_sheet([m.head,...m.sample.slice(0,2)]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,m.t);XLSX.writeFile(wb,V.slug()+'_'+el.dataset.k+'_template.xlsx')}else V.dl('template.csv',[m.head,...m.sample.slice(0,2)].map(r=>r.join(',')).join('\n'))};
V.acts.imGo=el=>{const k=el.dataset.k,m=IMPORTS[k];let rows=null;
 const draw=()=>{const b=$('#imb');if(!rows){b.innerHTML=`<div class="center" style="padding:28px;border:2px dashed var(--gold);border-radius:16px;background:var(--surface2)"><p class="mute sm">Columns: ${m.head.join(' · ')}</p><input type="file" id="imf" accept=".xlsx,.xls,.csv" style="max-width:320px;margin:auto"><div class="mt"><button class="btn sm" id="ims">Use sample data (demo)</button></div></div>`;
   $('#ims').onclick=()=>{rows=m.sample.map(r=>r.slice());draw()};$('#imf').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const raw=await new Promise(res=>{const r=new FileReader();r.onload=()=>{const wb=XLSX.read(r.result,{type:'array'});res(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''}))};r.readAsArrayBuffer(f)});rows=raw.slice(1).filter(r=>r.some(x=>x!==''));draw()}catch(err){V.toast('Could not read file','bad')}};return}
  const ev=rows.map(r=>m.check(r)),ok=ev.filter(e=>!e.length).length;b.innerHTML=`<div class="row">${V.badge(ok+' valid','ok')}${V.badge((rows.length-ok)+' errors',rows.length-ok?'bad':'')}</div><div class="tscroll mt" style="max-height:320px"><table class="t"><thead><tr><th>#</th>${m.head.map(h=>`<th>${h}</th>`).join('')}<th>Validation</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+2}</td>${m.head.map((h,j)=>`<td>${V.esc(r[j])}</td>`).join('')}<td>${ev[i].length?ev[i].map(e=>V.badge(e,'bad')).join(' '):V.badge('OK','ok')}</td></tr>`).join('')}</tbody></table></div>`;$('#imc').disabled=!ok};
 V.modal({title:'Import — '+m.t,xl:true,body:'<div id="imb"></div>',onOpen:draw,foot:[{l:'Cancel'},{l:'Import valid rows',cls:'primary',fn:()=>{if(!rows)return false;const good=rows.filter(r=>!m.check(r).length);if(!good.length){V.toast('No valid rows','bad');return false}
  if(k==='opening'){const g=V.group(good,r=>r[4]);g.forEach((rs,loc)=>{V.L.grnPost({vendor:'V01',loc,date:V.db.today,opening:true,by:V.S.user,note:'Opening stock import',lines:rs.map(r=>({sku:r[0],qty:+r[1],rate:+r[2],mrps:Array(+r[1]).fill(+r[3]),costs:Array(+r[1]).fill(+r[2])}))})})}else good.forEach(m.commit);
  V.L.audit('Import '+k,good.length+' rows');V.save();V.toast(good.length+' rows imported');V.refresh()}}]});V.$$('#mbg footer .btn')[1].id='imc';$('#imc').disabled=true};

// ================= AUDIT TRAIL =================
V.page('auditlog',{title:'Audit Trail',crumb:'Admin',
render(){const d=V.db,t=V.S.alTab||'log';
 return V.head('Audit Trail','Who did what and when — price overrides, approvals, stock moves, day-end, sync and logins.')
 +`<div class="tabs"><button class="${t==='log'?'on':''}" data-act="alTab" data-t="log">Activity log</button><button class="${t==='ses'?'on':''}" data-act="alTab" data-t="ses">Login sessions</button></div>`
 +(t==='log'?V.table('al',{rows:d.audit.slice().reverse().slice(0,800),cols:[{k:'t',l:'Timestamp'},{k:'user',l:'User',f:r=>V.L.userName(r.user),v:r=>r.user},{k:'act',l:'Action',f:r=>`<b>${V.esc(r.act)}</b>`,v:r=>r.act},{k:'ref',l:'Reference'}],pageSize:15}):V.table('ses',{rows:d.sessions,cols:[{k:'t',l:'Time'},{k:'user',l:'User',f:r=>V.L.userName(r.user),v:r=>r.user},{k:'ev',l:'Event',f:r=>V.badge(r.ev,r.ev==='Login'?'ok':'bad'),v:r=>r.ev},{k:'ip',l:'IP'},{k:'dev',l:'Device'}],pageSize:15}))}});
V.acts.alTab=el=>{V.S.alTab=el.dataset.t;V.refresh()};

// ================= SETTINGS =================
V.page('settings',{title:'Settings',crumb:'Admin',
render(){const S=V.db.settings;
 return V.head('Settings','Business-wide rules. In this demo they are stored in your browser only.')
 +(V.showBrandAdmin()?V.brandCard():V.clientCard())+`<div class="g ${V.basic?'':'g2 '}mt">${V.card('Identification & tracking','Every saree gets a unique serial number',`<div class="frm">${V.field('Client business name',`<input value="${V.esc(V.brand.business)}" disabled>`,V.basic?'':'Edit under White-label branding')}${V.field('Default tracking',`<div class="seg"><button class="on">Serial</button>${V.basic?'':'<button disabled>Batch (per item)</button>'}</div>`)}${V.field('Serial format',`<input value="${S.serialFormat}" disabled>`,'e.g. <b>KJV-2610-00045</b>')}${V.field('Default GST on sarees',`<input value="${S.gstDefault}%" disabled>`,'Overridable per item (HSN-driven)')}</div>`)}
  ${V.basic?'':V.card('Controls','Cash, discounts and approvals',`<div class="frm">${V.field('Cash receipt limit',`<input value="${V.inr(S.cashLimit)}" disabled>`,'Sec 269ST — ₹2 lakh per transaction')}${V.field('Approver PIN',`<input value="••••" disabled>`,'Demo PIN: 1234')}</div><h4 style="margin:6px 0 8px">Discount limits by role</h4><div class="chips">${V.db.users.map(u=>`<span class="badge">${u.role}: ${u.disc}%</span>`).join('')}</div>`)}</div>
 ${V.card('Demo data','',`<p class="mute">The demo ships with six months of trading, 4 exhibitions and a live Hyderabad pop-up. Everything you do is saved in this browser.</p><div class="row"><button class="btn" data-act="exportAll">${V.ic('download')} Download all data (JSON)</button><button class="btn danger" data-act="resetDemo">${V.ic('return')} Reset demo data</button></div>`,'mt')}`}});
V.acts.exportAll=()=>V.dl(V.slug()+'_data.json',JSON.stringify(V.db,null,1),'application/json');
V.acts.resetDemo=async()=>{if(await V.confirm('Reset all demo data to the original six-month dataset? Your changes will be lost.','Reset',true))V.resetDemo()};
})();
