/* POS billing, invoices, bookings/holds/trials, sales returns */
(function(){
const $=V.$;
V.pinGate=(msg,cb)=>V.modal({title:'Manager approval',body:`<p style="margin:0 0 12px">${msg}</p>${V.field('Approver PIN','<input id="pin" type="password" inputmode="numeric" maxlength="4" autocomplete="off">','Demo PIN: <b>1234</b>')}`,foot:[{l:'Cancel'},{l:'Approve',cls:'primary',fn:()=>{if($('#pin').value===V.db.settings.approvalPin){setTimeout(cb,50);return}V.toast('Incorrect PIN','bad');return false}}]});
const initPos=()=>({cart:[],cust:null,cashier:V.S.user,pays:[],q:'',weave:'ALL',note:'',approved:false,booking:null,trial:null,hold:null});
const P=()=>V.S.pos||(V.S.pos=initPos());
V.posCalc=()=>{const s=P(),loc=V.curLoc().id;const ls=s.cart.map(c=>{const p=V.m.piece[c.u],it=V.m.item[p.sku],gross=p.mrp*c.qty,d=Math.round(gross*(c.pct||0)/100/10)*10,n=gross-d,tb=n/(1+it.gst/100);return {c,p,it,gross,d,n,tb,tx:n-tb}});
 const sub=V.sum(ls,l=>l.gross),disc=V.sum(ls,l=>l.d),net=V.sum(ls,l=>l.n),tax=V.sum(ls,l=>l.tx),tb=V.sum(ls,l=>l.tb),ts=V.L.taxSplit(loc,s.cust,tax);
 const lim=V.m.user[s.cashier].disc,over=!V.basic&&ls.some(l=>(l.c.pct||0)>lim);
 const paid=V.sum(s.pays,x=>+x.amt||0),cash=V.sum(s.pays.filter(x=>x.mode==='Cash'),x=>+x.amt||0);
 return {ls,sub,disc,net,tax,tb,ts,lim,over,paid,cash,due:net-paid,change:Math.max(0,paid-net),loc}};

V.page('pos',{title:'POS Billing',crumb:'POS & Cash',
render(){const s=P(),loc=V.curLoc(),d=V.db;if(V.S.posCust){s.cust=V.S.posCust;V.S.posCust=null}
 const ex=d.exhibitions.find(e=>e.plant===loc.id);
 return `<div class="row between" style="margin-bottom:14px"><div><h1 style="font-size:30px">POS Billing</h1><div class="row sm mute"><span class="badge ${loc.type==='Exhibition'?'gold':'ok'}">${V.ic(loc.type==='Exhibition'?'flag':'store')} ${V.esc(loc.name)}</span><span>GSTIN ${loc.gstin}</span>${ex?`<span class="badge gold" style="font-family:monospace">${ex.code}</span>`:''}</div></div>
 <div class="row"><button class="btn" data-act="posHeld">${V.ic('clock')} Held bills (${(d.heldBills||[]).length})</button><button class="btn" data-act="posClear">${V.ic('x')} Clear</button></div></div>
 <div class="pos"><div><div class="card flat" style="margin-bottom:14px;padding:14px"><div class="search" style="flex:none;max-width:none">${V.ic('scan')}<input id="pq" placeholder="Scan serial / search design, colour, weave…  (Enter adds exact serial)" value="${V.esc(s.q)}" autocomplete="off" aria-label="Scan or search saree"></div><div class="chips" style="margin-top:10px" id="pchips"></div></div><div id="pgrid"></div></div>
 <aside class="card cart" id="pcart" aria-label="Cart"></aside></div>`},
mount(){const s=P();V.posGrid();V.posCart();
 const q=$('#pq');q.addEventListener('input',()=>{s.q=q.value;V.posGrid()});q.addEventListener('keydown',e=>{if(e.key==='Enter'){const v=q.value.trim().toLowerCase(),p=V.L.avail(V.curLoc().id).find(x=>x.no.toLowerCase()===v);if(p){V.posAdd(p.u);q.value='';s.q='';V.posGrid()}else V.toast('No exact serial match at this location','bad')}});q.focus()}});
V.posGrid=()=>{const s=P(),loc=V.curLoc().id,inCart=new Set(s.cart.map(c=>c.u));let ps=V.L.avail(loc).filter(p=>!inCart.has(p.u));
 const wk=['ALL',...V.uniq(ps.map(p=>V.m.item[p.sku].weave||'ACC'))];const cnt=k=>k==='ALL'?ps.length:ps.filter(p=>(V.m.item[p.sku].weave||'ACC')===k).length;
 $('#pchips').innerHTML=wk.map(k=>`<button class="chip ${s.weave===k?'on':''}" data-act="posWeave" data-k="${k}">${k==='ALL'?'All':k==='ACC'?'Accessories':V.m.weave[k].name} · ${cnt(k)}</button>`).join('');
 if(s.weave!=='ALL')ps=ps.filter(p=>(V.m.item[p.sku].weave||'ACC')===s.weave);
 if(s.q){const q=s.q.toLowerCase();ps=ps.filter(p=>{const it=V.m.item[p.sku];return p.no.toLowerCase().includes(q)||it.name.toLowerCase().includes(q)||it.colour.toLowerCase().includes(q)})}
 ps.sort((a,b)=>b.mrp-a.mrp);const g=$('#pgrid');if(!g)return;
 g.innerHTML=ps.length?`<div class="pgrid">${ps.slice(0,48).map(p=>{const it=V.m.item[p.sku];return `<button class="pcard" data-act="posAddBtn" data-u="${p.u}" aria-label="Add ${V.esc(it.name)} to bill">${V.swp(p,120,144)}<div class="inf"><b>${V.esc(it.name)}</b><small style="font-family:monospace">${p.no}</small><small>${V.esc(it.colour)}${p.trk==='batch'?' · '+p.qty+' in batch':''}</small><div class="pr">${V.inr(p.mrp)}</div></div></button>`}).join('')}</div>${ps.length>48?`<p class="mute center mt">Showing 48 of ${ps.length} — refine search</p>`:''}`:`<div class="card"><div class="empty">${V.art.empty()}<div>No stock matches at this location.<br><span class="sm">Switch location from the top bar or transfer stock in.</span></div></div></div>`};
V.posAdd=u=>{const s=P(),p=V.m.piece[u];if(s.cart.find(c=>c.u===u))return;s.cart.push({u,qty:1,pct:0});V.posGrid();V.posCart();V.toast(p.no+' added')};
V.acts.posAddBtn=el=>V.posAdd(el.dataset.u);
V.acts.posWeave=el=>{P().weave=el.dataset.k;V.posGrid()};
V.acts.posClear=async()=>{if(!P().cart.length&&!P().pays.length)return;if(await V.confirm('Clear the current bill?','Clear',true)){V.S.pos=initPos();V.refresh()}};
V.posCart=()=>{const s=P(),c=V.posCalc(),cu=s.cust?V.m.cust[s.cust]:null,box=$('#pcart');if(!box)return;
 const pm=['Cash','UPI','Card','Bank Transfer','EMI','Cheque'].concat(cu&&cu.credit?['Store Credit']:[]).concat(s.booking?['Advance']:[]);
 box.innerHTML=`<div style="position:relative"><div class="lab" style="margin-bottom:5px">Customer</div>${cu?`<div class="row between" style="padding:10px 12px;border:1px solid var(--gold);border-radius:12px;background:var(--surface2)"><div><b>${V.esc(cu.name)}</b> ${V.basic?'':V.badge(cu.tier,'gold')}<div class="xs mute">${cu.phone} · ${cu.city}${cu.gstin?' · GSTIN '+cu.gstin:''}${cu.credit?' · credit '+V.inr(cu.credit):''}</div></div><button class="iconbtn" data-act="posCustClear" aria-label="Remove customer">${V.ic('x')}</button></div>`:`<div class="row" style="flex-wrap:nowrap"><input id="pcq" placeholder="Search name / mobile (walk-in if blank)" autocomplete="off"><button class="btn sm" data-act="custNew" aria-label="Add new customer">${V.ic('plus')}</button></div><div class="sresults" id="pcr" hidden style="top:76px"></div>`}</div>
 <div class="lines mt">${c.ls.map((l,i)=>`<div class="cline"><div>${V.swp(l.p,54,64)}</div><div><b class="sm">${V.esc(l.it.name)}</b><div class="xs mute" style="font-family:monospace">${l.p.no}</div><div class="row" style="gap:6px;margin-top:4px;flex-wrap:nowrap"><label class="xs mute" for="d${i}">Disc %</label><input id="d${i}" type="number" min="0" max="50" step="0.5" value="${l.c.pct||0}" data-act2="pct" data-i="${i}" style="width:70px;min-height:32px;padding:4px 8px;${(l.c.pct||0)>c.lim?'border-color:var(--warn)':''}">${l.p.trk==='batch'?`<input type="number" min="1" max="${l.p.qty}" value="${l.c.qty}" data-act2="qty" data-i="${i}" style="width:60px;min-height:32px;padding:4px 8px" aria-label="Quantity">`:''}</div></div><div class="right"><button class="iconbtn" style="width:32px;height:32px" data-act="posRm" data-i="${i}" aria-label="Remove">${V.ic('x')}</button><div class="b">${V.inr(l.n)}</div>${l.d?`<div class="xs mute" style="text-decoration:line-through">${V.inr(l.gross)}</div>`:''}</div></div>`).join('')||`<div class="empty" style="padding:24px 10px">${V.art.empty()}<div class="sm">Scan or tap a saree to start billing</div></div>`}</div>
 <div class="tot"><div><span>Subtotal (MRP)</span><span>${V.inr(c.sub)}</span></div>${c.disc?`<div><span>Discount</span><span style="color:var(--ok)">− ${V.inr(c.disc)}</span></div>`:''}<div class="xs mute"><span>Taxable value</span><span>${V.inr(c.tb)}</span></div>${c.ts.inter?`<div class="xs mute"><span>IGST</span><span>${V.inr(c.ts.igst)}</span></div>`:`<div class="xs mute"><span>CGST + SGST</span><span>${V.inr(c.ts.cgst)} + ${V.inr(c.ts.sgst)}</span></div>`}<div class="grand"><span>Total</span><span>${V.inr(c.net)}</span></div></div>
 ${c.over&&!s.approved?`<div class="login-note" style="border-color:var(--warn);margin-bottom:10px">Discount above ${c.lim}% limit for ${V.esc(V.m.user[s.cashier].name)} — <button class="btn sm" data-act="posApprove">Manager approval</button></div>`:''}
 ${c.ls.length?`<div class="lab" style="margin-bottom:6px">Payment</div>${s.pays.map((p,i)=>`<div class="pay"><select data-act2="pm" data-i="${i}" aria-label="Mode">${pm.map(m=>`<option ${m===p.mode?'selected':''}>${m}</option>`).join('')}</select><input type="number" min="0" value="${p.amt}" data-act2="pa" data-i="${i}" aria-label="Amount"><button class="iconbtn" style="width:28px;height:28px" data-act="posPayRm" data-i="${i}" aria-label="Remove payment">${V.ic('x')}</button>${p.mode!=='Cash'?`<input data-act2="pr" data-i="${i}" value="${V.esc(p.ref||'')}" placeholder="Ref / UTR / last 4" style="grid-column:1/-1;min-height:34px">`:''}</div>`).join('')}
 <div class="chips" style="margin-bottom:8px">${['UPI','Card','Cash','Bank Transfer','EMI'].map(m=>`<button class="chip" data-act="posPay" data-m="${m}">+ ${m}</button>`).join('')}</div>
 <div class="row between sm" style="margin-bottom:10px"><span>${c.due>0?`Balance due <b style="color:var(--bad)">${V.inr(c.due)}</b>`:c.change>0?`Change to return <b>${V.inr(c.change)}</b>`:`<b style="color:var(--ok)">Fully paid ✓</b>`}</span><span class="mute">${V.basic?'':`Earns ${Math.floor(c.net/100)} pts`}</span></div>
 <div class="row"><select id="pcash" aria-label="Cashier" style="flex:1">${V.db.users.filter(u=>['Cashier','Store Manager','Exhibition In-charge','Owner'].includes(u.role)).map(u=>`<option value="${u.id}" ${u.id===s.cashier?'selected':''}>${u.name} (${u.role})</option>`).join('')}</select></div>
 <div class="row mt" style="flex-wrap:nowrap"><button class="btn" data-act="posHold" style="flex:1">${V.ic('clock')} Hold</button>${V.basic?'':`<button class="btn" data-act="posBook" style="flex:1" ${c.ls.length!==1?'disabled':''}>${V.ic('gift')} Advance</button>`}<button class="btn primary lg" data-act="posPost" style="flex:2" ${c.due>0||(c.over&&!s.approved)?'disabled':''}>${V.ic('check')} Complete sale</button></div>`:''}`;
 const q=$('#pcq');if(q)q.addEventListener('input',()=>{const t=q.value.trim().toLowerCase(),r=$('#pcr');if(t.length<2){r.hidden=true;return}const m=V.db.customers.filter(x=>x.name.toLowerCase().includes(t)||x.phone.includes(t)).slice(0,6);r.hidden=!m.length;r.innerHTML=m.map(x=>`<a href="javascript:void 0" data-act="posCustPick" data-id="${x.id}"><span><b>${V.esc(x.name)}</b> <small>${x.phone} · ${x.city}</small></span>${V.basic?'':V.badge(x.tier,'gold')}</a>`).join('')});
 V.$$('[data-act2]',box).forEach(el=>el.addEventListener('change',()=>{const i=+el.dataset.i,k=el.dataset.act2;
   if(k==='pct'){const v=Math.max(0,Math.min(50,+el.value||0));s.cart[i].pct=v;s.approved=false}else if(k==='qty'){s.cart[i].qty=Math.max(1,Math.min(V.m.piece[s.cart[i].u].qty,+el.value||1))}else if(k==='pm'){s.pays[i].mode=el.value}else if(k==='pa'){s.pays[i].amt=+el.value||0}else if(k==='pr'){s.pays[i].ref=el.value;return}
   if(k==='pct'||k==='qty'){V.posRebalance()}V.posCart()}));
 const cs=$('#pcash');if(cs)cs.onchange=()=>{s.cashier=cs.value;s.approved=false;V.posCart()}};
V.posRebalance=()=>{const s=P();if(s.pays.length===1){s.pays[0].amt=Math.round(V.posCalc().net)}};
V.acts.posCustPick=el=>{P().cust=el.dataset.id;V.posCart()};V.acts.posCustClear=()=>{P().cust=null;V.posCart()};
V.acts.posRm=el=>{const s=P();s.cart.splice(+el.dataset.i,1);if(!s.cart.length)s.pays=[];else V.posRebalance();V.posGrid();V.posCart()};
V.acts.posPay=el=>{const s=P(),c=V.posCalc();if(!c.ls.length){V.toast('Add a saree first','bad');return}s.pays.push({mode:el.dataset.m,amt:Math.max(0,Math.round(c.due)),ref:''});V.posCart()};
V.acts.posPayRm=el=>{P().pays.splice(+el.dataset.i,1);V.posCart()};
V.acts.posApprove=()=>V.pinGate('A discount above the cashier limit needs manager approval.',()=>{P().approved=true;V.L.audit('Discount override approved','POS',V.S.user);V.toast('Discount approved by manager');V.posCart()});
V.acts.posHold=()=>{const s=P();if(!s.cart.length)return;const d=V.db;d.heldBills=d.heldBills||[];d.heldBills.push({id:'HB-'+(d.heldBills.length+1),loc:V.curLoc().id,t:V.now(),state:JSON.parse(JSON.stringify(s))});V.S.pos=initPos();V.save();V.toast('Bill held — resume anytime');V.refresh()};
V.acts.posHeld=()=>{const hb=V.db.heldBills||[];V.modal({title:'Held bills',body:hb.length?hb.map((h,i)=>`<div class="row between" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${h.id}</b> <span class="mute sm">${h.t} · ${h.state.cart.length} item(s) · ${h.state.cust?V.esc(V.m.cust[h.state.cust].name):'Walk-in'}</span></div><button class="btn sm primary" data-act="posResume" data-i="${i}">Resume</button></div>`).join(''):'<p class="mute">No held bills.</p>'})};
V.acts.posResume=el=>{const hb=V.db.heldBills,h=hb.splice(+el.dataset.i,1)[0];V.S.pos=h.state;V.closeModal();V.save();V.refresh()};
V.acts.posBook=()=>{const s=P(),c=V.posCalc(),l=c.ls[0];V.modal({title:'Take advance / book saree',body:`<p class="mute" style="margin-top:0">${V.esc(l.it.name)} · ${l.p.no} · ${V.inr(l.n)}</p>${!s.cust?'<div class="login-note" style="border-color:var(--warn)">Select a customer first.</div>':''}<div class="frm">${V.field('Advance (₹)',`<input id="bka" type="number" value="${Math.round(l.n*.25/1000)*1000}">`)}${V.field('Mode','<select id="bkm"><option>UPI</option><option>Card</option><option>Cash</option><option>Bank Transfer</option></select>')}${V.field('Balance due by',`<input id="bkd" type="date" value="${V.addDays(V.db.today,14)}">`)}</div>`,foot:[{l:'Cancel'},{l:'Book saree',cls:'primary',fn:()=>{if(!s.cust){V.toast('Select a customer','bad');return false}const a=+$('#bka').value;if(!(a>0)||a>l.n){V.toast('Enter a valid advance','bad');return false}
  const b={no:'BKG-'+(301+V.db.bookings.length),date:V.db.today,cust:s.cust,u:l.p.u,advance:a,mode:$('#bkm').value,due:$('#bkd').value,status:'Open',by:s.cashier};V.db.bookings.push(b);l.p.status='booked';l.p.holdFor=s.cust;V.L.move(l.p,'BOOK',l.p.loc,l.p.loc,b.no,'',s.cashier,'Advance '+a);
  if($('#bkm').value==='Cash'){const r=V.L.drawer(V.curLoc().id,V.db.today);r.entries.push({t:'in',amt:a,reason:'Booking advance '+b.no,time:V.now(),by:s.cashier})}V.L.audit('Booking',b.no);V.S.pos=initPos();V.save();V.toast(b.no+' booked with advance '+V.inr(a));V.refresh()}}]})};
V.acts.posPost=()=>{const s=P(),c=V.posCalc();if(!c.ls.length||c.due>0)return;if(c.change>0&&c.change>c.cash){V.toast('Overpayment can only be returned from cash received','bad');return}
 if(c.cash-Math.min(c.change,c.cash)>V.db.settings.cashLimit){V.toast('Cash receipts above ₹2,00,000 are not permitted (Sec 269ST). Split with UPI/Card.','bad');return}
 const loc=c.loc;const dr=V.L.drawer(loc,V.db.today);if(dr.status==='closed'){V.toast('Day-end already closed for today at this location','bad');return}
 const cu=s.cust?V.m.cust[s.cust]:null;const sc=s.pays.find(p=>p.mode==='Store Credit');if(sc&&cu){if(sc.amt>cu.credit){V.toast('Store credit exceeds balance','bad');return}}
 const inv=V.L.invoicePost({loc,date:V.db.today,cust:s.cust,cashier:s.cashier,sp:s.cashier,lines:c.ls.map(l=>({u:l.c.u,qty:l.c.qty,disc:l.d})),pays:s.pays.filter(p=>p.amt>0).map(p=>({mode:p.mode==='Advance'?'Advance':p.mode,amt:+p.amt,ref:p.ref}))});
 if(sc&&cu)cu.credit-=sc.amt;if(cu){cu.spend=(cu.spend||0)+inv.net;cu.loyalty=Math.floor(cu.spend/100)}
 if(s.booking){const b=V.db.bookings.find(x=>x.no===s.booking);if(b)b.status='Converted'}if(s.trial){const t=V.db.trials.find(x=>x.no===s.trial);if(t)t.status='Converted'}if(s.hold){const h=V.db.holds.find(x=>x.no===s.hold);if(h)h.status='Converted'}
 V.S.pos=initPos();V.save();V.showInvoice(inv.no,true)};
V.invoiceHtml=inv=>{const lo=V.m.loc[inv.loc],c=inv.cust?V.m.cust[inv.cust]:null,B=V.brand.business;
 return `<div class="inv"><div class="row between" style="align-items:flex-start"><div><div class="row" style="flex-wrap:nowrap;gap:10px">${V.brand.logo?V.brandMark(44):''}<h2>${V.esc(B)}</h2></div><div>${V.esc(lo.name)}<br>GSTIN: <b>${lo.gstin}</b> · ${lo.state}</div></div><div class="right"><b style="font-size:15px">TAX INVOICE</b><br>${inv.no}<br>${V.fd(inv.date)} ${inv.time}</div></div><div class="temple"></div>
 <div class="row between" style="align-items:flex-start"><div><b>Billed to</b><br>${c?V.esc(c.name)+'<br>'+c.phone+(c.gstin?'<br>GSTIN '+c.gstin:''):'Walk-in customer'}</div><div class="right">Place of supply: <b>${inv.inter&&c?c.state:lo.state}</b><br>${inv.inter?'Inter-state (IGST)':'Intra-state (CGST+SGST)'}</div></div>
 <table style="margin-top:10px"><thead><tr><th>#</th><th>Description / Serial</th><th>HSN</th><th class="r">Qty</th><th class="r">MRP</th><th class="r">Disc</th><th class="r">Taxable</th><th class="r">GST</th><th class="r">Amount</th></tr></thead><tbody>${inv.lines.map((l,i)=>`<tr><td>${i+1}</td><td>${V.esc(l.name)}<br><span style="font-family:monospace;font-size:11px">${l.no}</span></td><td>${l.hsn}</td><td class="r">${l.qty}</td><td class="r">${V.inr(l.mrp)}</td><td class="r">${l.disc?V.inr(l.disc):'—'}</td><td class="r">${V.inr(l.taxable)}</td><td class="r">${l.gst}%</td><td class="r">${V.inr(l.net)}</td></tr>`).join('')}</tbody></table>
 <div class="row between mt" style="align-items:flex-start"><div style="max-width:55%"><b>Payment</b><br>${inv.pays.map(p=>`${p.mode} ${V.inr(p.amt)}${p.ref?' ('+V.esc(p.ref)+')':''}`).join(' · ')}${inv.change?`<br>Change returned ${V.inr(inv.change)}`:''}<br><br><i>${V.words(inv.net)} Rupees Only</i></div><table style="width:280px"><tr><td>Taxable value</td><td class="r">${V.inr(inv.taxable)}</td></tr>${inv.inter?`<tr><td>IGST</td><td class="r">${V.inr(inv.igst)}</td></tr>`:`<tr><td>CGST</td><td class="r">${V.inr(inv.cgst)}</td></tr><tr><td>SGST</td><td class="r">${V.inr(inv.sgst)}</td></tr>`}<tr><td>Discount given</td><td class="r">${V.inr(inv.disc)}</td></tr><tr><td><b>Grand total</b></td><td class="r"><b style="font-size:16px">${V.inr(inv.net)}</b></td></tr></table></div>
 <div class="temple"></div><div class="row between" style="font-size:11px;color:#555"><span>Handloom Mark / Silk Mark certified pieces. Exchange within 7 days with tags intact. Subject to ${lo.city} jurisdiction.</span><span>${V.art.qr(inv.no,17,2)}</span></div></div>`};
V.showInvoice=(no,fresh)=>{const inv=V.m.inv[no];V.modal({title:fresh?'✓ Sale completed — '+inv.no:inv.no,xl:true,body:V.invoiceHtml(inv),foot:[...(V.basic?[]:[{l:'WhatsApp / Email',fn:()=>{V.toast('Invoice link shared with '+(inv.cust?V.m.cust[inv.cust].phone:'customer')+' (demo)');return false}}]),{l:'Sales return',fn:()=>{setTimeout(()=>V.acts.srNew(null,inv.no),50)}},{l:'Print',fn:()=>{V.printHtml(V.invoiceHtml(inv),inv.no);return false}},{l:fresh?'New bill':'Close',cls:'primary',fn:()=>{if(fresh)V.refresh()}}]})};

// ================= INVOICES =================
V.page('invoices',{title:'Invoices',crumb:'POS & Cash',
render(no){const d=V.db;if(no){setTimeout(()=>{V.showInvoice(no);history.replaceState(null,'','#/invoices')},30)}
 const rows=d.invoices.slice().reverse().map(i=>Object.assign({},i,{cn:i.cust?V.m.cust[i.cust].name:'Walk-in',ln:V.m.loc[i.loc].city,mode:V.uniq(i.pays.map(p=>p.mode)).join('+'),items:i.lines.length}));
 return V.head('Invoices','All GST invoices across showroom and exhibitions. Click to view, print or raise a return.')
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'Invoices',n:d.invoices.length,ic:'receipt',c:V.brand.primary,sub:'6 months'})}${V.kpi({l:'Net sales',n:V.sum(d.invoices,i=>i.net),f:'short',ic:'cash',c:'#1E2A5E',sub:'incl. GST'})}${V.kpi({l:'Avg ticket',n:V.sum(d.invoices,i=>i.net)/d.invoices.length,f:'short',ic:'tag',c:V.brand.accent,sub:'per invoice'})}${V.kpi({l:'GST collected',n:V.sum(d.invoices,i=>i.tax||i.net-i.taxable),f:'short',ic:'coins',c:'#0F6B6B',sub:V.basic?'GST on all bills':'CGST+SGST+IGST'})}</div>`
 +V.table('inv',{rows,ph:'Search invoice, customer, location…',cols:[{k:'no',l:'Invoice',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'cn',l:'Customer'},{k:'ln',l:'Location'},{k:'items',l:'Items',fmt:'num'},{k:'mode',l:'Payment'},{k:'net',l:'Amount',fmt:'inr'},{k:'sync',l:'Shopify',fmt:'badge'}],onRow:r=>V.showInvoice(r.no)})}});

// ================= BOOKINGS / HOLDS / TRIALS =================
V.page('bookings',{title:'Bookings, Holds & Trials',crumb:'POS & Cash',
render(){const d=V.db,t=V.S.bkTab||'book';
 const tabs=`<div class="tabs" role="tablist">${[['book','Bookings (advance)'],['hold','Customer holds'],['trial','Approval on sight']].map(x=>`<button class="${t===x[0]?'on':''}" data-act="bkTab" data-t="${x[0]}" role="tab">${x[1]}</button>`).join('')}</div>`;
 const cn=r=>V.esc(V.m.cust[r.cust].name),sn=r=>V.m.piece[r.u].no;
 let body='';
 if(t==='book')body=V.table('bk',{rows:d.bookings.slice().reverse().map(r=>Object.assign({},r,{pc:V.m.piece[r.u],bal:V.m.piece[r.u].mrp-r.advance})),cols:[{k:'no',l:'No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'cust',l:'Customer',f:cn,v:cn},{k:'u',l:'Saree',f:r=>`${V.esc(V.m.item[r.pc.sku].name)}<div class="xs mute" style="font-family:monospace">${r.pc.no}</div>`,v:sn},{k:'advance',l:'Advance',fmt:'inr'},{k:'bal',l:'Balance',fmt:'inr'},{k:'due',l:'Due by',fmt:'date'},{k:'status',l:'Status',fmt:'badge'},{k:'a',l:'',nosort:true,f:r=>r.status==='Open'?`<button class="btn sm primary" data-act="bkConvert" data-k="book" data-no="${r.no}">Bill now</button> <button class="btn sm" data-act="bkCancel" data-k="book" data-no="${r.no}">Cancel</button>`:''}]});
 else if(t==='hold')body=V.table('hl',{rows:d.holds.slice().reverse(),cols:[{k:'no',l:'No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'cust',l:'Customer',f:cn,v:cn},{k:'u',l:'Saree',f:r=>`${V.esc(V.m.item[V.m.piece[r.u].sku].name)}<div class="xs mute" style="font-family:monospace">${sn(r)}</div>`,v:sn},{k:'until',l:'Hold until',fmt:'date'},{k:'status',l:'Status',fmt:'badge'},{k:'a',l:'',nosort:true,f:r=>r.status==='Active'?`<button class="btn sm primary" data-act="bkConvert" data-k="hold" data-no="${r.no}">Bill now</button> <button class="btn sm" data-act="bkCancel" data-k="hold" data-no="${r.no}">Release</button>`:''}]});
 else body=V.table('tr',{rows:d.trials.slice().reverse(),cols:[{k:'no',l:'No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Issued',fmt:'date'},{k:'cust',l:'Customer',f:cn,v:cn},{k:'u',l:'Saree',f:r=>`${V.esc(V.m.item[V.m.piece[r.u].sku].name)}<div class="xs mute" style="font-family:monospace">${sn(r)}</div>`,v:sn},{k:'due',l:'Return by',fmt:'date'},{k:'status',l:'Status',fmt:'badge'},{k:'a',l:'',nosort:true,f:r=>r.status==='Out'?`<button class="btn sm primary" data-act="bkConvert" data-k="trial" data-no="${r.no}">Keep → bill</button> <button class="btn sm" data-act="bkCancel" data-k="trial" data-no="${r.no}">Returned</button>`:''}]});
 return V.head('Bookings, Holds & Trials','Premium sarees are rarely bought on first sight. Reserve against an <b>advance</b>, hold for a family viewing, or send out <b>on approval</b> — stock stays accounted for.',`<button class="btn primary" data-act="bkNew" data-k="${t}">${V.ic('plus')} New ${t==='book'?'booking':t==='hold'?'hold':'approval issue'}</button>`)
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'Open bookings',n:d.bookings.filter(b=>b.status==='Open').length,ic:'gift',c:V.brand.accent,sub:V.short(V.sum(d.bookings.filter(b=>b.status==='Open'),b=>b.advance))+' advances held'})}${V.kpi({l:'Balance to collect',n:V.sum(d.bookings.filter(b=>b.status==='Open'),b=>V.m.piece[b.u].mrp-b.advance),f:'short',ic:'wallet',c:V.brand.primary,sub:'on open bookings'})}${V.kpi({l:'Active holds',n:d.holds.filter(h=>h.status==='Active').length,ic:'clock',c:'#1E2A5E',sub:'reserved pieces'})}${V.kpi({l:'Out on approval',n:d.trials.filter(h=>h.status==='Out').length,ic:'eye',c:'#0F6B6B',sub:'with customers'})}</div>`+tabs+body}});
V.acts.bkTab=el=>{V.S.bkTab=el.dataset.t;V.refresh()};
V.acts.bkConvert=el=>{const k=el.dataset.k,no=el.dataset.no,col={book:V.db.bookings,hold:V.db.holds,trial:V.db.trials}[k],r=col.find(x=>x.no===no),s=V.S.pos=initPos();s.cust=r.cust;s.cart=[{u:r.u,qty:1,pct:0}];
 if(k==='book'){s.booking=no;s.pays=[{mode:'Advance',amt:r.advance,ref:no}];const p=V.m.piece[r.u];s.pays.push({mode:'UPI',amt:p.mrp-r.advance,ref:''})}else s[k==='hold'?'hold':'trial']=no;
 const p=V.m.piece[r.u];V.S.loc=p.loc;try{localStorage.setItem('vk_loc',p.loc)}catch(e){}V.go('#/pos')};
V.acts.bkCancel=async el=>{const k=el.dataset.k,no=el.dataset.no,col={book:V.db.bookings,hold:V.db.holds,trial:V.db.trials}[k],r=col.find(x=>x.no===no),p=V.m.piece[r.u];
 if(!await V.confirm(k==='book'?`Cancel booking ${no}? The advance of ${V.inr(r.advance)} is converted to store credit.`:`Release ${no} back to stock?`,'Yes',k==='book'))return;
 p.status='in_stock';delete p.holdFor;r.status=k==='trial'?'Returned':'Cancelled';if(k==='hold')r.status='Released';if(k==='book'){V.m.cust[r.cust].credit=(V.m.cust[r.cust].credit||0)+r.advance}V.save();V.toast('Done');V.refresh()};
V.acts.bkNew=el=>{const k=el.dataset.k,loc=V.curLoc().id;V.modal({title:k==='book'?'New booking (advance)':k==='hold'?'New customer hold':'Issue on approval',wide:true,body:`<div class="frm">${V.field('Customer *',`<select name="cust"><option value="">Select</option>${V.opts(V.db.customers,'',{v:c=>c.id,l:c=>c.name+' · '+c.phone})}</select>`)}${V.field('Saree *',`<select name="u"><option value="">Select (${V.esc(V.curLoc().name)})</option>${V.L.avail(loc).filter(p=>p.trk==='serial').slice(0,150).map(p=>`<option value="${p.u}">${p.no} — ${V.esc(V.m.item[p.sku].name)} (${V.inr(p.mrp)})</option>`).join('')}</select>`)}${k==='book'?V.field('Advance (₹) *','<input name="adv" type="number">')+V.field('Mode','<select name="mode"><option>UPI</option><option>Card</option><option>Cash</option></select>'):''}${V.field(k==='book'?'Balance due by':k==='hold'?'Hold until':'Return by',`<input name="due" type="date" value="${V.addDays(V.db.today,k==='hold'?3:k==='trial'?3:14)}">`)}</div>`,
  foot:[{l:'Cancel'},{l:'Save',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['cust','u'])||(k==='book'&&!V.need(v,['adv'])))return false;const p=V.m.piece[v.u],T=V.db.today;
   if(k==='book'){const b={no:'BKG-'+(301+V.db.bookings.length),date:T,cust:v.cust,u:v.u,advance:+v.adv,mode:v.mode,due:v.due,status:'Open',by:V.S.user};V.db.bookings.push(b);p.status='booked';V.L.move(p,'BOOK',p.loc,p.loc,b.no,'',V.S.user,'Advance '+v.adv);if(v.mode==='Cash'){V.L.drawer(loc,T).entries.push({t:'in',amt:+v.adv,reason:'Booking '+b.no,time:V.now(),by:V.S.user})}}
   else if(k==='hold'){const h={no:'HLD-'+(101+V.db.holds.length),date:T,cust:v.cust,u:v.u,until:v.due,status:'Active',by:V.S.user,note:''};V.db.holds.push(h);p.status='hold';V.L.move(p,'HOLD',p.loc,p.loc,h.no,'',V.S.user)}
   else{const t={no:'TRL-'+(201+V.db.trials.length),date:T,cust:v.cust,u:v.u,due:v.due,status:'Out',by:V.S.user};V.db.trials.push(t);p.status='trial';V.L.move(p,'TRIAL',p.loc,'Customer',t.no,'',V.S.user)}
   p.holdFor=v.cust;V.save();V.toast('Saved');V.refresh()}}]})};

// ================= SALES RETURNS =================
V.page('sreturn',{title:'Sales Returns',crumb:'POS & Cash',
render(inv){const d=V.db;if(inv)setTimeout(()=>{V.acts.srNew(null,inv);history.replaceState(null,'','#/sreturn')},30);
 const rows=d.salesReturns.slice().reverse().map(r=>Object.assign({},r,{cn:r.cust?V.m.cust[r.cust].name:'Walk-in',pcs:r.lines.map(l=>l.no).join(', '),reason:r.lines[0].reason}));
 return V.head('Sales Returns & Exchanges','Damage, shade mismatch or change of choice — against the original invoice and serial. Good pieces re-enter stock; damaged ones go to <b>quarantine</b>. Credit notes sync to Shopify as refunds.',`<button class="btn primary" data-act="srNew">${V.ic('plus')} New Return</button>`)
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'Returns',n:rows.length,ic:'return',c:'#B3261E',sub:V.pct(rows.length,d.invoices.length)+'% of invoices'})}${V.kpi({l:'Value returned',n:V.sum(rows,r=>r.amt),f:'short',ic:'coins',c:V.brand.primary,sub:'incl. GST'})}${V.kpi({l:'Credit notes',n:rows.filter(r=>r.cn).length,ic:'file',c:V.brand.accent,sub:'issued'})}${V.kpi({l:'Quarantined',n:V.sum(rows,r=>r.lines.filter(l=>l.cond==='damaged').length),ic:'alert',c:'#0F6B6B',sub:'damaged pieces'})}</div>`
 +V.table('sr',{rows,cols:[{k:'no',l:'Return',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'inv',l:'Invoice',f:r=>`<a href="#/invoices/${encodeURIComponent(r.inv)}">${r.inv}</a>`,v:r=>r.inv},{k:'cn',l:'Customer'},{k:'pcs',l:'Serial'},{k:'reason',l:'Reason'},{k:'mode',l:'Settlement',f:r=>r.mode+(r.cn?` · ${r.cn}`:r.refundMode?` · ${r.refundMode}`:''),v:r=>r.mode},{k:'amt',l:'Amount',fmt:'inr'}]})}});
V.acts.srNew=(el,pre)=>{V.modal({title:'New Sales Return / Exchange',xl:true,body:`${V.field('Invoice no. *',`<input id="sri" list="srl" placeholder="Type invoice number" value="${pre||''}"><datalist id="srl">${V.db.invoices.slice(-80).reverse().map(i=>`<option value="${i.no}">`).join('')}</datalist>`)}<div id="srb" class="mute">Enter an invoice to list returnable lines.</div>`,
  onOpen:()=>{const show=()=>{const iv=V.m.inv[$('#sri').value.trim()];if(!iv){$('#srb').innerHTML='<span class="mute">Invoice not found.</span>';return}
    $('#srb').innerHTML=`<div class="mb sm"><b>${iv.no}</b> · ${V.fd(iv.date)} · ${iv.cust?V.esc(V.m.cust[iv.cust].name):'Walk-in'} · ${V.inr(iv.net)}</div><div class="tscroll"><table class="t"><thead><tr><th></th><th>Item</th><th class="n">Amount</th><th>Reason</th><th>Condition</th></tr></thead><tbody>${iv.lines.map((l,i)=>{const done=V.db.salesReturns.some(r=>r.inv===iv.no&&r.lines.some(x=>x.u===l.u));return `<tr><td><input type="checkbox" data-i="${i}" ${done?'disabled':''}></td><td>${V.esc(l.name)}<div class="xs mute" style="font-family:monospace">${l.no}</div></td><td class="n">${V.inr(l.net)}</td><td><select data-r="${i}">${V.RETURN_REASONS.map(r=>`<option>${r}</option>`).join('')}</select></td><td><select data-c="${i}"><option value="good">Good — restock</option><option value="damaged">Damaged — quarantine</option></select>${done?'<div class="xs" style="color:var(--bad)">Already returned</div>':''}</td></tr>`}).join('')}</tbody></table></div>
    <div class="frm mt">${V.field('Settlement','<select id="srm"><option>Credit Note</option><option>Refund</option><option>Exchange</option></select>')}${V.field('Refund via','<select id="srf"><option>UPI</option><option>Card</option><option>Bank Transfer</option><option>Cash</option></select>','Applies to refunds')}</div>`};
   $('#sri').addEventListener('input',show);if(pre)show()},
  foot:[{l:'Cancel'},{l:'Post return',cls:'primary',fn:()=>{const iv=V.m.inv[$('#sri').value.trim()];if(!iv){V.toast('Select a valid invoice','bad');return false}const ls=V.$$('#srb [data-i]:checked').map(c=>({u:iv.lines[+c.dataset.i].u,reason:V.$(`[data-r="${c.dataset.i}"]`).value,cond:V.$(`[data-c="${c.dataset.i}"]`).value}));if(!ls.length){V.toast('Select at least one line','bad');return false}
   const r=V.L.salesReturn({inv:iv.no,lines:ls,mode:$('#srm').value,refundMode:$('#srf').value,date:V.db.today,by:V.S.user,loc:V.curLoc().id});V.save();V.toast(`${r.no} posted · ${r.cn||r.mode} ${V.inr(r.amt)}`);V.go('#/sreturn');V.refresh()}}]})};
})();
