/* Procurement: PO (+Excel upload), GRN with serial/batch generation, purchase return, local purchase, vendor ledger */
(function(){
const $=V.$;
V.setPath=(o,path,val)=>{const k=path.split('.');let t=o;for(let i=0;i<k.length-1;i++)t=t[k[i]];t[k[k.length-1]]=val};
document.addEventListener('change',e=>{const t=e.target;if(t.dataset&&t.dataset.st){let v=t.type==='checkbox'?t.checked:t.value;if(t.type==='number')v=v===''?0:+v;V.setPath(V.S,t.dataset.st,v);if(t.dataset.re)V.refresh()}});

// -------- labels --------
V.labelHtml=p=>{const it=V.m.item[p.sku];return `<div class="label"><div>${V.art.qr(p.no,17,3)}</div><div><b class="nm">${V.esc(it.name)}</b><div>${V.esc(it.colour)} · ${V.esc(it.fabric)}</div><div>${V.esc(it.region||'')} ${it.cert?'· '+V.esc(it.cert):''}</div><div class="no">${p.no}</div>${V.art.barcode(p.no,150,26)}<div style="margin-top:2px"><b>MRP ${V.inr(p.mrp)}</b> <span style="opacity:.7">(incl. GST)</span></div></div></div>`};
V.printLabels=us=>V.printHtml(`<div>${us.map(u=>V.labelHtml(V.m.piece[u])).join('')}</div>`,'Labels');

// ================= PURCHASE ORDERS =================
const TEMPLATE_HEAD=['Vendor Code','Design SKU','Qty','Rate','Expected Date','Remarks'];
const normKey=k=>String(k).toLowerCase().replace(/[^a-z0-9]/g,'');
const parseCsv=t=>{const rows=[];let r=[],c='',q=false;for(let i=0;i<t.length;i++){const ch=t[i];if(q){if(ch==='"'&&t[i+1]==='"'){c+='"';i++}else if(ch==='"')q=false;else c+=ch}else if(ch==='"')q=true;else if(ch===','){r.push(c);c=''}else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&t[i+1]==='\n')i++;r.push(c);rows.push(r);r=[];c=''}else c+=ch}if(c||r.length){r.push(c);rows.push(r)}
  const h=rows.shift().map(x=>x.trim());return rows.filter(x=>x.some(y=>y.trim())).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]])))};
const sampleRows=()=>{const t=V.addDays(V.db.today,14);return [['V-KJV','KJV-01',8,'62000',t,'Festive season lot'],['V-KJV','KJV-03',6,'',t,'Rate to be confirmed'],['V-BNR','BNR-02',7,'54000',t,''],['V-BNR','BNR-99',4,'60000',t,'Unknown SKU (demo error)'],['V-PTL','PTL-01',4,'182000',V.addDays(V.db.today,30),'Advance paid'],['V-JMD','JMD-02',10,'24500',t,''],['V-XYZ','POC-01',5,'18000',t,'Unknown vendor (demo error)']].map(r=>Object.fromEntries(TEMPLATE_HEAD.map((h,i)=>[h,r[i]])))};
const toIso=v=>{if(v instanceof Date)return V.iso(v);if(typeof v==='number'&&v>20000)return V.iso(new Date(Math.round((v-25569)*864e5)));const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''};
V.validatePoRows=raw=>{const d=V.db;return raw.map((o,i)=>{const g=n=>{const k=Object.keys(o).find(x=>normKey(x)===normKey(n));return k?o[k]:''};
  const r={row:i+2,vcode:String(g('Vendor Code')).trim(),sku:String(g('Design SKU')).trim(),qty:+g('Qty'),rate:+g('Rate'),exp:toIso(g('Expected Date')),rem:String(g('Remarks')||''),errs:[],warns:[]};
  const v=d.vendors.find(x=>x.code===r.vcode||x.id===r.vcode),it=V.m.item[r.sku];r.vendor=v;r.item=it;
  if(!v)r.errs.push('Vendor code not found');if(!it)r.errs.push('Design SKU not in Item Master');else if(v&&it.weave&&v.weave&&it.weave!==v.weave)r.warns.push('Design weave differs from vendor cluster');
  if(!(r.qty>0)||r.qty%1)r.errs.push('Qty must be a whole number > 0');
  if(!(r.rate>0)){if(it){r.rate=it.cost;r.warns.push('Rate blank — std cost '+V.inr(it.cost)+' applied')}else r.errs.push('Rate missing')}
  if(it&&r.rate>it.cost*1.2)r.warns.push('Rate >20% above standard cost');
  if(!r.exp){r.exp=V.addDays(d.today,14);r.warns.push('Expected date defaulted (+14 days)')}
  return r})};
V.page('po',{title:'Purchase Orders',crumb:'Procurement',
render(){const d=V.db,rows=d.pos.slice().reverse().map(p=>Object.assign({},p,{vn:V.m.vendor[p.vendor].name,units:V.sum(p.lines,l=>l.qty),rcv:V.sum(p.lines,l=>l.rcv)}));
 const open=d.pos.filter(p=>!['Closed'].includes(p.status));
 return V.head('Purchase Orders','Raise POs manually or <b>upload an Excel sheet</b> — rows are validated against vendor and item masters before any PO is created. Goods then flow into inventory through GRN.',`<button class="btn" data-act="poTemplate">${V.ic('download')} Excel template</button><button class="btn gold" data-act="poUpload">${V.ic('upload')} Upload PO (Excel)</button><button class="btn primary" data-act="poNew">${V.ic('plus')} New PO</button>`)
 +`<div class="g ${V.basic?'g3':'g4'}" style="margin-bottom:18px">${V.kpi({l:'Open POs',n:open.length,ic:'file',c:'#1E2A5E',sub:V.short(V.sum(open,p=>p.value))+' committed'})}${V.kpi({l:'Awaiting delivery',n:d.pos.filter(p=>p.status==='Issued'||p.status==='Approved').length,ic:'truck',c:V.brand.accent,sub:'issued / approved'})}${V.kpi({l:'Partially received',n:d.pos.filter(p=>p.status==='Partially Received').length,ic:'layers',c:'#0F6B6B',sub:'balance pending'})}${V.basic?'':V.kpi({l:'Drafts for approval',n:d.pos.filter(p=>p.status==='Draft').length,ic:'inbox',c:V.brand.primary,sub:'need owner sign-off'})}</div>`
 +V.table('po',{rows,ph:'Search PO, vendor…',cols:[{k:'no',l:'PO No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'vn',l:'Vendor'},{k:'units',l:'Units',fmt:'num'},{k:'rcv',l:'Received',f:r=>`${r.rcv}/${r.units}`,v:r=>r.rcv},{k:'value',l:'Value',fmt:'inr'},{k:'expected',l:'Expected',fmt:'date'},{k:'src',l:'Source',f:r=>r.src==='Excel Upload'?V.badge('Excel','gold'):'Manual',v:r=>r.src},{k:'status',l:'Status',fmt:'badge'}],onRow:r=>V.acts.poView(r.no)})}});
V.acts.poView=no=>{const p=V.m.po[no],v=V.m.vendor[p.vendor];
 const nextA=V.basic?{Draft:['Issue to vendor','primary','issue'],Approved:['Issue to vendor','primary','issue'],Issued:['Receive goods (GRN)','gold','grn'],'Partially Received':['Receive balance (GRN)','gold','grn']}[p.status]:{Draft:['Approve PO','primary','approve'],Approved:['Issue to vendor','primary','issue'],Issued:['Receive goods (GRN)','gold','grn'],'Partially Received':['Receive balance (GRN)','gold','grn']}[p.status];
 V.modal({title:p.no,wide:true,body:`<div class="row between"><div><b>${V.esc(v.name)}</b><div class="mute sm">${v.city}, ${v.state} · ${v.gstin||'Unregistered'} · ${V.esc(p.terms||'')}</div></div>${V.badge(p.status)}</div>
  <div class="tscroll mt"><table class="t"><thead><tr><th>Design</th><th class="n">Ordered</th><th class="n">Received</th><th class="n">Pending</th><th class="n">Rate</th><th class="n">Amount</th></tr></thead><tbody>${p.lines.map(l=>`<tr><td><b>${l.sku}</b> ${V.esc(V.m.item[l.sku].name)}</td><td class="n">${l.qty}</td><td class="n">${l.rcv}</td><td class="n">${Math.max(0,l.qty-l.rcv)}</td><td class="n">${V.inr(l.rate)}</td><td class="n">${V.inr(l.qty*l.rate)}</td></tr>`).join('')}</tbody><tfoot><tr><td>Total</td><td class="n">${V.sum(p.lines,l=>l.qty)}</td><td class="n">${V.sum(p.lines,l=>l.rcv)}</td><td></td><td></td><td class="n">${V.inr(p.value)}</td></tr></tfoot></table></div>
  <p class="mute sm mt">Raised ${V.fd(p.date)} by ${V.L.userName(p.by)} · expected ${V.fd(p.expected)} · source ${p.src}${p.notes?' · '+V.esc(p.notes):''}</p>`,
  foot:[...(V.basic?[]:[{l:'Print PO',fn:()=>{V.printHtml(`<h2>Purchase Order ${p.no}</h2><div class="temple"></div><p><b>${V.esc(v.name)}</b><br>${v.city}, ${v.state}<br>GSTIN: ${v.gstin||'Unregistered'}</p><table><tr><th>Design</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr>${p.lines.map(l=>`<tr><td>${l.sku} ${V.esc(V.m.item[l.sku].name)}</td><td class="r">${l.qty}</td><td class="r">${V.inr(l.rate)}</td><td class="r">${V.inr(l.qty*l.rate)}</td></tr>`).join('')}</table><h3 style="text-align:right">Total ${V.inr(p.value)}</h3><p>Expected delivery ${V.fd(p.expected)} · Terms: ${V.esc(p.terms||'')}</p>`);return false}}]),...(nextA?[{l:nextA[0],cls:nextA[1],fn:()=>{if(nextA[2]==='approve'){p.status='Approved';p.approvedBy=V.S.user;V.L.audit('PO approved',p.no)}else if(nextA[2]==='issue'){p.status='Issued';V.L.audit('PO issued',p.no)}else{V.S.grn=null;V.go('#/grn/'+encodeURIComponent(p.no));return}V.save();V.toast(p.no+' → '+p.status);V.refresh()}}]:[]) ]})};
V.acts.poSample=el=>{const bad=el.dataset.bad==='1',rows=sampleRows().filter(r=>bad||(r['Design SKU']!=='BNR-99'&&r['Vendor Code']!=='V-XYZ')),nm=V.slug()+(bad?'_Sample_PO_with_errors':'_Sample_PO');if(window.XLSX){const ws=XLSX.utils.aoa_to_sheet([TEMPLATE_HEAD,...rows.map(r=>TEMPLATE_HEAD.map(h=>r[h]))]);ws['!cols']=[{wch:14},{wch:14},{wch:8},{wch:12},{wch:16},{wch:30}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'PO');XLSX.writeFile(wb,nm+'.xlsx')}else V.dl(nm+'.csv',[TEMPLATE_HEAD.join(','),...rows.map(r=>TEMPLATE_HEAD.map(h=>r[h]).join(','))].join('\n'));V.toast('Sample PO file downloaded — upload it here')};
V.acts.poTemplate=()=>{if(window.XLSX){const ws=XLSX.utils.aoa_to_sheet([TEMPLATE_HEAD,...sampleRows().slice(0,3).map(r=>TEMPLATE_HEAD.map(h=>r[h]))]);ws['!cols']=[{wch:14},{wch:14},{wch:8},{wch:12},{wch:16},{wch:30}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'PO');XLSX.writeFile(wb,V.slug()+'_PO_Template.xlsx')}else V.dl(V.slug()+'_PO_Template.csv',TEMPLATE_HEAD.join(',')+'\nV-KJV,KJV-01,8,62000,'+V.addDays(V.db.today,14)+',Festive lot');V.toast('Template downloaded')};
V.acts.poNew=()=>{const lines=[{sku:'',qty:1,rate:0}];
 const rowHtml=()=>lines.map((l,i)=>`<tr><td><select data-i="${i}" data-f="sku">${'<option value="">Select design</option>'+V.db.items.filter(it=>it.cat==='Saree'&&(!$('#pov').value||V.m.vendor[$('#pov').value].weave===it.weave)).map(it=>`<option value="${it.sku}" ${l.sku===it.sku?'selected':''}>${it.sku} — ${V.esc(it.name)}</option>`).join('')}</select></td><td><input type="number" min="1" data-i="${i}" data-f="qty" value="${l.qty}" style="width:80px"></td><td><input type="number" min="0" data-i="${i}" data-f="rate" value="${l.rate}" style="width:120px"></td><td class="n">${V.inr(l.qty*l.rate)}</td><td><button class="iconbtn" data-i="${i}" data-f="del" aria-label="Remove line">${V.ic('x')}</button></td></tr>`).join('');
 V.modal({title:'New Purchase Order',xl:true,body:`<div class="frm">${V.field('Vendor *',`<select id="pov">${'<option value="">Select vendor</option>'+V.db.vendors.filter(v=>v.weave).map(v=>`<option value="${v.id}">${V.esc(v.name)} (${V.m.weave[v.weave].name})</option>`).join('')}</select>`)}${V.field('Expected delivery',`<input type="date" id="poe" value="${V.addDays(V.db.today,14)}">`)}</div><div class="tscroll"><table class="t"><thead><tr><th>Design</th><th>Qty</th><th>Rate (₹)</th><th class="n">Amount</th><th></th></tr></thead><tbody id="pol">${rowHtml()}</tbody></table></div><button class="btn sm mt" id="poadd">${V.ic('plus')} Add line</button> <b style="float:right;margin-top:14px" id="pot"></b>`,
  onOpen:r=>{const upd=()=>{$('#pol').innerHTML=rowHtml();$('#pot').textContent='Total '+V.inr(V.sum(lines,l=>l.qty*l.rate))};
   $('#pov').addEventListener('change',()=>{lines.forEach(l=>l.sku='');upd()});$('#poadd').onclick=()=>{lines.push({sku:'',qty:1,rate:0});upd()};
   r.addEventListener('change',e=>{const t=e.target,i=t.dataset.i;if(i===undefined)return;const f=t.dataset.f;if(f==='sku'){lines[i].sku=t.value;lines[i].rate=t.value?V.m.item[t.value].cost:0}else if(f==='qty')lines[i].qty=Math.max(1,+t.value||1);else if(f==='rate')lines[i].rate=+t.value||0;upd()});
   r.addEventListener('click',e=>{const b=e.target.closest('[data-f=del]');if(b){lines.splice(+b.dataset.i,1);if(!lines.length)lines.push({sku:'',qty:1,rate:0});upd()}});upd()},
  foot:V.basic?[{l:'Cancel'},{l:'Create PO',cls:'primary',fn:()=>save('Issued')}]:[{l:'Cancel'},{l:'Save as draft',fn:()=>save('Draft')},{l:'Create & approve',cls:'primary',fn:()=>save('Approved')}]});
 function save(st){const v=$('#pov').value,ls=lines.filter(l=>l.sku&&l.qty>0&&l.rate>0);if(!v||!ls.length){V.toast('Pick a vendor and at least one valid line','bad');return false}const po=V.L.poCreate({vendor:v,date:V.db.today,expected:$('#poe').value,lines:ls,status:st,by:V.S.user});V.save();V.toast(po.no+' created');V.refresh()}};
V.acts.poUpload=()=>{V.S.upl=null;
 const draw=()=>{const u=V.S.upl,box=$('#upl');if(!u){box.innerHTML=`<div class="center" style="padding:30px;border:2px dashed var(--gold);border-radius:16px;background:var(--surface2)"><div class="gold">${V.ic('upload')}</div><h4>Drop your PO Excel / CSV here</h4><p class="mute sm">Columns: ${TEMPLATE_HEAD.join(' · ')}</p><input type="file" id="upf" accept=".xlsx,.xls,.csv" style="max-width:320px;margin:auto"><div class="mt row" style="justify-content:center"><button class="btn sm" id="ups">Use sample file (demo)</button><button class="btn sm" data-act="poTemplate">Download template</button></div><div class="mt row" style="justify-content:center"><button class="btn sm gold" data-act="poSample" data-bad="0">${V.ic('download')} Sample PO (valid)</button><button class="btn sm" data-act="poSample" data-bad="1">${V.ic('download')} Sample PO (with errors)</button></div></div>`;
   $('#upf').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const raw=/\.csv$/i.test(f.name)?parseCsv(await f.text()):await new Promise(res=>{const r=new FileReader();r.onload=()=>{const wb=XLSX.read(r.result,{type:'array',cellDates:true});res(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}))};r.readAsArrayBuffer(f)});V.S.upl={name:f.name,rows:V.validatePoRows(raw)};draw()}catch(err){V.toast('Could not read file: '+err.message,'bad')}};
   $('#ups').onclick=()=>{V.S.upl={name:'sample_po_upload.xlsx',rows:V.validatePoRows(sampleRows())};draw()};return}
  const ok=u.rows.filter(r=>!r.errs.length),bad=u.rows.length-ok.length,vs=V.uniq(ok.map(r=>r.vendor.id));
  box.innerHTML=`<div class="row between"><div><b>${V.esc(u.name)}</b> · ${u.rows.length} rows</div><div class="row">${V.badge(ok.length+' valid','ok')}${V.badge(bad+' with errors',bad?'bad':'')}${V.badge(u.rows.filter(r=>!r.errs.length&&r.warns.length).length+' warnings','warn')}</div></div>
  <div class="tscroll mt" style="max-height:340px"><table class="t"><thead><tr><th>Row</th><th>Vendor</th><th>SKU</th><th class="n">Qty</th><th class="n">Rate</th><th>Expected</th><th>Validation</th></tr></thead><tbody>${u.rows.map(r=>`<tr><td>${r.row}</td><td>${V.esc(r.vcode)}</td><td>${V.esc(r.sku)}</td><td class="n">${r.qty||''}</td><td class="n">${r.rate?V.inr(r.rate):''}</td><td>${V.fd(r.exp)}</td><td>${r.errs.length?r.errs.map(e=>V.badge(e,'bad')).join(' '):V.badge('OK','ok')} ${r.warns.map(e=>V.badge(e,'warn')).join(' ')}</td></tr>`).join('')}</tbody></table></div>
  <div class="login-note mt">${ok.length?`<b>${vs.length} PO${vs.length>1?'s':''}</b> will be created (one per vendor) from ${ok.length} valid rows.`:'No valid rows.'} ${bad?'Rows with errors are skipped — fix the file and re-upload.':''}</div>`;
  $('#upc').disabled=!ok.length};
 V.modal({title:'Upload Purchase Order (Excel)',xl:true,body:'<div id="upl"></div>',onOpen:draw,foot:[{l:'Close'},{l:'Start over',fn:()=>{V.S.upl=null;V.acts.poUpload();return false}},{l:'Create POs',cls:'primary',fn:()=>{const u=V.S.upl;if(!u)return false;const ok=u.rows.filter(r=>!r.errs.length);if(!ok.length){V.toast('Nothing valid to create','bad');return false}
   const by=V.group(ok,r=>r.vendor.id);const made=[];by.forEach((rs,vid)=>{const po=V.L.poCreate({vendor:vid,date:V.db.today,expected:rs[0].exp,lines:rs.map(r=>({sku:r.sku,qty:r.qty,rate:r.rate})),status:V.basic?'Issued':'Approved',by:V.S.user,src:'Excel Upload',notes:'Uploaded from '+u.name});made.push(po.no)});V.save();V.toast(made.length+' PO(s) created: '+made.join(', '));V.refresh()}}]});
 const b=V.$$('#mbg footer .btn');b[2].id='upc';b[2].disabled=true};

// ================= GRN =================
V.page('grn',{title:'GRN · Goods Inward',crumb:'Procurement',
render(po){const d=V.db;
 if(po==='new'||po){if(!V.S.grn||V.S.grn.po!==(po==='new'?'':po))V.grnInit(po==='new'?'':po);return V.grnWizard()}
 const rows=d.grns.slice().reverse().map(g=>Object.assign({},g,{vn:V.m.vendor[g.vendor].name,units:V.sum(g.lines,l=>l.acc),rej:V.sum(g.lines,l=>l.rej)}));
 return V.head('GRN · Goods Inward','Receive against a PO, run QC, and <b>auto-generate a unique serial number for every piece</b>. Print tags for every piece before it hits the shelf.',`<a class="btn primary" href="#/grn/new" data-act="grnFresh">${V.ic('plus')} New GRN</a>`)
 +`<div class="g g4" style="margin-bottom:18px">${V.kpi({l:'GRNs posted',n:d.grns.length,ic:'truck',c:'#1E2A5E',sub:'since go-live'})}${V.kpi({l:'Units inwarded',n:V.sum(d.grns,g=>V.sum(g.lines,l=>l.acc)),ic:'qr',c:V.brand.primary,sub:'each with a unique ID'})}${V.kpi({l:'QC rejected',n:V.sum(d.grns,g=>V.sum(g.lines,l=>l.rej)),ic:'alert',c:'#B3261E',sub:V.pct(V.sum(d.grns,g=>V.sum(g.lines,l=>l.rej)),V.sum(d.grns,g=>V.sum(g.lines,l=>l.recv)))+'% of received'})}${V.kpi({l:'Inward value',n:V.sum(d.grns,g=>g.value),f:'short',ic:'coins',c:V.brand.accent,sub:'at cost'})}</div>`
 +V.table('grn',{rows,cols:[{k:'no',l:'GRN No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'po',l:'PO',f:r=>r.po||(r.opening?'<span class="badge gold">Opening stock</span>':'<span class="mute">Direct</span>'),v:r=>r.po||''},{k:'vn',l:'Vendor'},{k:'units',l:'Accepted',fmt:'num'},{k:'rej',l:'Rejected',fmt:'num'},{k:'value',l:'Value',fmt:'inr'},{k:'loc',l:'Location',f:r=>V.esc(V.m.loc[r.loc].city),v:r=>r.loc},{k:'qc',l:'QC',fmt:'badge'}],onRow:r=>V.acts.grnView(r.no)})}});
V.acts.grnFresh=()=>{V.S.grn=null};
V.grnInit=pono=>{const po=pono?V.m.po[pono]:null;V.S.grn={po:pono,vendor:po?po.vendor:'',loc:'MAIN',date:V.db.today,freight:0,step:po?2:1,done:null,
  lines:po?po.lines.filter(l=>l.qty>l.rcv).map(l=>({sku:l.sku,ordered:l.qty,pending:l.qty-l.rcv,qty:l.qty-l.rcv,rej:0,reason:'',rate:l.rate,trk:V.m.item[l.sku].trk,mrps:null})):[]}};
V.grnPreview=()=>{const g=V.S.grn,off={};return g.lines.map(l=>{const it=V.m.item[l.sku],acc=Math.max(0,l.qty-l.rej),k=V.L.serKey(it,g.date,l.trk),n=l.trk==='serial'?acc:(acc?1:0);const st=(V.db.seq[k.key]||0)+(off[k.key]||0);off[k.key]=(off[k.key]||0)+n;
  const nos=Array.from({length:n},(_,i)=>k.pre+String(st+i+1).padStart(k.pad,'0'));const need=l.trk==='serial'?acc:(acc?1:0);if(!l.pc||l.pc.length!==need||l.pcRate!==l.rate)V.grnPcInit(l,it,need);return {l,it,acc,nos}})};
// ---- GRN pricing: cost price + markup (% or ₹) -> selling price + GST -> final MRP ----
V.grnRound=()=>{const g=V.S.grn;return g&&g.round!==undefined?+g.round:100};
V.grnCalc=(r,gst)=>{const rd=V.grnRound(),sp=(+r.cost||0)+(+r.amt||0),gs=sp*gst/100,raw=sp+gs;return {sp,gs,mrp:rd>0?Math.round(raw/rd)*rd:Math.round(raw)}};
V.grnPcInit=(l,it,n)=>{const cost=+l.rate||0,pct=cost?Math.round(((it.mrp/(1+it.gst/100))/cost-1)*10000)/100:0,amt=Math.round(cost*pct)/100;l.pc=Array.from({length:n},()=>({cost,pct,amt}));l.pcRate=l.rate};
V.grnPcSet=(r,field,val)=>{val=Math.max(0,+val||0);if(field==='cost'){r.cost=val;r.amt=Math.round(r.cost*r.pct)/100}else if(field==='pct'){r.pct=val;r.amt=Math.round(r.cost*val)/100}else{r.amt=val;r.pct=r.cost?Math.round(val/r.cost*10000)/100:0}};
V.grnPcCells=(i,j)=>{const g=V.S.grn,l=g.lines[i],it=V.m.item[l.sku],r=l.pc[j],c=V.grnCalc(r,it.gst),set=(k,v)=>{const e=document.getElementById(`gp-${i}-${j}-${k}`);if(e)e.textContent=v};set('sp',V.inr(c.sp));set('gst',V.inr(c.gs));set('mrp',V.inr(c.mrp))};
V.grnPcTotals=()=>{const g=V.S.grn,e=document.getElementById('gp-tot');if(!e)return;let cost=0,mk=0,mrp=0,n=0;g.lines.forEach(l=>{const it=V.m.item[l.sku];(l.pc||[]).forEach(r=>{const c=V.grnCalc(r,it.gst),q=l.trk==='serial'?1:Math.max(0,l.qty-l.rej);cost+=r.cost*q;mk+=r.amt*q;mrp+=c.mrp*q;n+=q})});e.innerHTML=`<span>${n} pcs</span><span>Cost <b>${V.inr(cost)}</b></span><span>Markup <b>${V.inr(mk)}</b> (${cost?(mk/cost*100).toFixed(1):0}%)</span><span>Total MRP incl. GST <b>${V.inr(mrp)}</b></span>`};
V.grnWizard=()=>{const g=V.S.grn,steps=['Select PO / vendor','Receive & QC','Serial / Batch preview','Post & labels'];
 const stp=`<div class="steps">${steps.map((s,i)=>`<div class="s ${g.step>i+1||g.done?'done':g.step===i+1?'on':''}">${i+1}. ${s}</div>`).join('')}</div>`;
 const head=V.head(g.po?'GRN against '+g.po:'New GRN','',`<a class="btn" href="#/grn" data-act="grnFresh">‹ Cancel</a>`);
 if(g.done){const gr=V.m.grn[g.done],us=gr.lines.flatMap(l=>l.units);return head+stp+`<div class="card center"><div style="width:90px;margin:auto;color:var(--ok)">${V.ic('check')}</div><h2>${gr.no} posted</h2><p class="mute">${V.sum(gr.lines,l=>l.acc)} units added to ${V.esc(V.m.loc[gr.loc].name)} · stock value ${V.inr(gr.value)}</p>
  <div class="chips" style="justify-content:center;margin:12px 0 18px">${us.slice(0,18).map(u=>`<a class="chip" href="#/trace/${V.m.piece[u].no}">${V.m.piece[u].no}</a>`).join('')}${us.length>18?`<span class="mute">+${us.length-18} more</span>`:''}</div>
  <div class="row" style="justify-content:center"><button class="btn gold lg" data-act="grnLabels" data-no="${gr.no}">${V.ic('print')} Print ${us.length} tags</button><a class="btn lg" href="#/stock">${V.ic('box')} View stock</a><a class="btn lg" href="#/grn" data-act="grnFresh">All GRNs</a></div><h4 style="margin:22px 0 10px">Tag preview</h4><div class="lbl-sheet" style="text-align:left">${us.slice(0,3).map(u=>V.labelHtml(V.m.piece[u])).join('')}</div></div>`}
 if(g.step===1){const pos=V.db.pos.filter(p=>['Issued','Approved','Partially Received'].includes(p.status));
  return head+stp+`<div class="g ${V.basic?'':'g2'}"><div class="card"><h3>Receive against a purchase order</h3><div class="sub">Pending lines are pre-filled</div>${pos.length?pos.map(p=>`<a class="row between" style="padding:12px;border:1px solid var(--line);border-radius:12px;margin-bottom:8px;text-decoration:none;color:inherit" href="#/grn/${encodeURIComponent(p.no)}"><span><b>${p.no}</b><div class="xs mute">${V.esc(V.m.vendor[p.vendor].name)} · ${V.fds(p.expected)}</div></span>${V.badge(p.status)}</a>`).join(''):`<p class="mute">No open purchase orders. Create one in <a href="#/po">Purchase Orders</a> (or upload an Excel sample) and it will appear here.</p>`}</div>
  ${V.basic?'':`<div class="card"><h3>Direct GRN (no PO)</h3><div class="sub">Walk-in weaver delivery or opening stock</div>${V.field('Vendor',`<select data-st="grn.vendor" data-re="1"><option value="">Select vendor</option>${V.opts(V.db.vendors,g.vendor,{v:v=>v.id,l:v=>v.name})}</select>`)}${g.vendor?V.field('Add design',`<select id="gadd"><option value="">Select…</option>${V.db.items.filter(i=>i.cat==='Saree'&&V.m.vendor[g.vendor].weave===i.weave||i.cat==='Accessory').map(i=>`<option value="${i.sku}">${i.sku} — ${V.esc(i.name)}</option>`).join('')}</select>`):''}
  <button class="btn primary" data-act="grnNext">Continue →</button></div>`}</div>`}
 const prevCard=g.step>=3?V.grnPreview():null;
 const vend=V.m.vendor[g.vendor];
 if(g.step===2)return head+stp+`<div class="card"><div class="row between"><div><h3>${vend?V.esc(vend.name):'Select vendor'}</h3><div class="sub">Enter what physically arrived and what failed QC</div></div><div class="row">${V.field('Receiving location',`<select data-st="grn.loc">${V.opts(V.db.locations.filter(l=>['Showroom','Warehouse'].includes(l.type)),g.loc,{v:l=>l.id,l:l=>l.name})}</select>`,'','')}${V.field('GRN date',`<input type="date" data-st="grn.date" data-re="1" value="${g.date}">`)}</div></div>
  <div class="tscroll"><table class="t"><thead><tr><th>Design</th><th class="n">Ordered</th><th class="n">Pending</th><th>Received</th><th>QC rejected</th><th>Reject reason</th>${V.basic?'':'<th>Numbering</th>'}<th class="n">Rate</th></tr></thead><tbody>${g.lines.map((l,i)=>`<tr><td><b>${l.sku}</b><div class="xs mute">${V.esc(V.m.item[l.sku].name)}</div></td><td class="n">${l.ordered||'—'}</td><td class="n">${l.pending??'—'}</td><td><input type="number" min="0" style="width:84px" data-st="grn.lines.${i}.qty" data-re="1" value="${l.qty}"></td><td><input type="number" min="0" max="${l.qty}" style="width:84px" data-st="grn.lines.${i}.rej" data-re="1" value="${l.rej}"></td><td><input data-st="grn.lines.${i}.reason" value="${V.esc(l.reason)}" placeholder="${l.rej?'Required':'—'}" ${l.rej?'':'disabled'}></td>${V.basic?'':`<td><select data-st="grn.lines.${i}.trk" data-re="1" style="min-width:120px"><option value="serial" ${l.trk==='serial'?'selected':''}>Serial (1 per piece)</option><option value="batch" ${l.trk==='batch'?'selected':''}>Batch no.</option></select></td>`}<td><input type="number" style="width:110px" data-st="grn.lines.${i}.rate" value="${l.rate}"></td></tr>`).join('')||'<tr><td colspan="${V.basic?7:8}"><div class="empty">Add a design to continue</div></td></tr>'}</tbody></table></div>
  ${!g.po&&g.vendor?`<div class="mt">${V.field('Add design',`<select id="gadd"><option value="">Select…</option>${V.db.items.filter(i=>i.cat==='Saree'&&vend.weave===i.weave||i.cat==='Accessory').map(i=>`<option value="${i.sku}">${i.sku} — ${V.esc(i.name)}</option>`).join('')}</select>`)}</div>`:''}
  <div class="row between mt"><div class="sm mute">Accepted units: <b>${V.sum(g.lines,l=>Math.max(0,l.qty-l.rej))}</b> · Rejected: <b>${V.sum(g.lines,l=>l.rej)}</b></div><button class="btn primary" data-act="grnNext">Preview serial numbers →</button></div></div>`;
 if(g.step===3)return head+stp+`<div class="card"><h3>Auto-generated identifiers</h3><div class="sub">Format <code>${V.esc(V.db.settings.serialFormat)}</code> </div>
  <div class="card flat mt" style="padding:14px"><div class="row"><div class="field" style="margin:0"><label>Round final MRP to</label><select data-st="grn.round" data-re="1" style="width:170px"><option value="0" ${V.grnRound()===0?'selected':''}>Nearest ₹1 (exact)</option><option value="10" ${V.grnRound()===10?'selected':''}>Nearest ₹10</option><option value="100" ${V.grnRound()===100?'selected':''}>Nearest ₹100</option><option value="500" ${V.grnRound()===500?'selected':''}>Nearest ₹500</option></select></div><div class="field" style="margin:0"><label>Markup % for all pieces</label><div class="row" style="flex-wrap:nowrap"><input type="number" min="0" step="0.5" id="mk-all" style="width:100px" placeholder="e.g. 35"><button class="btn sm" data-act="grnMk" data-i="all">Apply to all</button></div></div><div class="sm mute" style="max-width:420px">Final MRP = (Cost price + Markup) + GST. Edit Markup % <b>or</b> Markup ₹ — the other updates automatically.</div></div></div>
  ${prevCard.map(p=>{const i=g.lines.indexOf(p.l),isS=p.l.trk==='serial';return `<div class="row between" style="margin:18px 0 8px"><h4 style="margin:0">${p.it.sku} · ${V.esc(p.it.name)} ${V.badge(isS?'Serial':'Batch',isS?'info':'gold')} <span class="badge">GST ${p.it.gst}%</span></h4><div class="row" style="flex-wrap:nowrap;gap:6px"><input type="number" min="0" step="0.5" id="mk-${i}" style="width:90px;min-height:34px" placeholder="Markup %" aria-label="Markup % for this design"><button class="btn sm" data-act="grnMk" data-i="${i}">Apply to design</button></div></div>
   <div class="tscroll"><table class="t"><thead><tr><th>${isS?'Serial no.':'Batch no.'}</th>${isS?'<th>Tag</th>':''}<th>Cost price (₹)</th><th>Markup %</th><th>Markup (₹)</th><th class="n">Selling price</th><th class="n">GST ${p.it.gst}%</th><th class="n">Final MRP (incl. GST)</th></tr></thead><tbody>${(p.l.pc||[]).map((r,j)=>{const c=V.grnCalc(r,p.it.gst);return `<tr><td><b style="font-family:monospace">${p.nos[j]||'—'}</b>${isS?'':`<div class="xs mute">${p.acc} units</div>`}</td>${isS?`<td><span style="display:inline-block;vertical-align:middle">${V.art.qr(p.nos[j],13,2)}</span></td>`:''}<td><input type="number" min="0" id="gp-${i}-${j}-cost" data-gp="${i}.${j}.cost" value="${r.cost}" style="width:120px"></td><td><input type="number" min="0" step="0.1" id="gp-${i}-${j}-pct" data-gp="${i}.${j}.pct" value="${r.pct}" style="width:90px"></td><td><input type="number" min="0" id="gp-${i}-${j}-amt" data-gp="${i}.${j}.amt" value="${r.amt}" style="width:120px"></td><td class="n" id="gp-${i}-${j}-sp">${V.inr(c.sp)}</td><td class="n" id="gp-${i}-${j}-gst">${V.inr(c.gs)}</td><td class="n"><b style="font-size:15px;color:var(--primary)" id="gp-${i}-${j}-mrp">${V.inr(c.mrp)}</b></td></tr>`}).join('')||'<tr><td colspan="8" class="mute">No accepted units</td></tr>'}</tbody></table></div>`}).join('')}
  <div class="card flat mt" style="padding:12px 16px;background:var(--surface2)"><div class="row between" id="gp-tot" style="gap:20px"></div></div>
  <div class="row between mt"><button class="btn" data-act="grnBack">← Back</button><div class="row">${V.field('Freight / packing (₹)',`<input type="number" style="width:140px" data-st="grn.freight" value="${g.freight}">`,'','')}<button class="btn primary lg" data-act="grnPost">${V.ic('check')} Post GRN & generate ${V.sum(prevCard,p=>p.l.trk==='serial'?p.acc:p.acc?1:0)} IDs</button></div></div></div>`;
 return head+stp};
V.acts.grnNext=()=>{const g=V.S.grn;
 if(g.step===1){if(!g.vendor){V.toast('Select a PO or a vendor','bad');return}g.step=2;V.refresh();return}
 if(g.step===2){if(!g.lines.length||V.sum(g.lines,l=>l.qty)<=0){V.toast('Enter received quantity','bad');return}const bad=g.lines.find(l=>l.rej>l.qty||(l.rej>0&&!l.reason.trim()));if(bad){V.toast(bad.rej>bad.qty?'Rejected cannot exceed received':'Give a reason for rejected units','bad');return}g.step=3;V.refresh()}};
V.acts.grnBack=()=>{V.S.grn.step--;V.refresh()};
V.acts.grnPost=()=>{const g=V.S.grn,gr=V.L.grnPost({po:g.po||null,vendor:g.vendor,loc:g.loc,date:g.date,by:V.S.user,freight:g.freight,lines:g.lines.map(l=>({sku:l.sku,qty:l.qty,rej:l.rej,rate:l.rate,ordered:l.ordered,rejReason:l.reason,trk:l.trk,costs:(l.pc||[]).map(r=>r.cost),mrps:(l.pc||[]).map(r=>V.grnCalc(r,V.m.item[l.sku].gst).mrp),mks:(l.pc||[]).map(r=>({pct:r.pct,amt:r.amt}))}))});g.done=gr.no;V.save();V.toast(gr.no+' posted — serials generated');V.refresh()};
V.acts.grnLabels=el=>{const gr=V.m.grn[el.dataset.no];V.printLabels(gr.lines.flatMap(l=>l.units))};
V.page('grn').mount=po=>{if(V.S.grn&&V.S.grn.step===3)V.grnPcTotals();const s=$('#gadd');if(s)s.onchange=()=>{const g=V.S.grn;if(!s.value)return;const it=V.m.item[s.value];if(!g.lines.find(l=>l.sku===it.sku))g.lines.push({sku:it.sku,ordered:0,pending:null,qty:1,rej:0,reason:'',rate:it.cost,trk:it.trk,mrps:null});if(g.step===1)g.step=2;V.refresh()}};
V.acts.grnView=no=>{const g=V.m.grn[no];V.modal({title:g.no,wide:true,body:`<div class="row between"><div><b>${V.esc(V.m.vendor[g.vendor].name)}</b><div class="mute sm">${V.fd(g.date)} · ${V.esc(V.m.loc[g.loc].name)} · by ${V.L.userName(g.by)}${g.po?' · PO '+g.po:''}</div></div>${V.badge(g.qc)}</div>
 <div class="tscroll mt"><table class="t"><thead><tr><th>Design</th><th class="n">Ordered</th><th class="n">Received</th><th class="n">Rejected</th><th class="n">Accepted</th><th>Identifiers</th></tr></thead><tbody>${g.lines.map(l=>`<tr><td><b>${l.sku}</b> ${V.esc(V.m.item[l.sku].name)}${l.rejReason?`<div class="xs" style="color:var(--bad)">${V.esc(l.rejReason)}</div>`:''}</td><td class="n">${l.ordered}</td><td class="n">${l.recv}</td><td class="n">${l.rej}</td><td class="n">${l.acc}</td><td>${l.units.slice(0,4).map(u=>`<a href="#/trace/${V.m.piece[u].no}" data-act="closeModal" class="chip">${V.m.piece[u].no}</a>`).join(' ')}${l.units.length>4?` +${l.units.length-4}`:''}</td></tr>`).join('')}</tbody></table></div>`,foot:[{l:'Reprint tags',fn:()=>{V.printLabels(g.lines.flatMap(l=>l.units));return false}},{l:'Close',cls:'primary'}]})};

// ================= PURCHASE RETURN =================
V.page('preturn',{title:'Purchase Returns',crumb:'Procurement',
render(){const d=V.db,rows=d.purchaseReturns.slice().reverse().map(r=>Object.assign({},r,{vn:V.m.vendor[r.vendor].name,pcs:r.units.map(u=>V.m.piece[u].no).join(', ')}));
 return V.head('Purchase Returns','Send defective / mismatched pieces back to the weaver against the original GRN. A <b>debit note</b> is raised and the vendor ledger is adjusted automatically.',`<button class="btn primary" data-act="prNew">${V.ic('plus')} New Purchase Return</button>`)
 +`<div class="g g3" style="margin-bottom:18px">${V.kpi({l:'Returns raised',n:rows.length,ic:'return',c:V.brand.primary,sub:'to vendors'})}${V.kpi({l:'Debit value',n:V.sum(rows,r=>r.amt),f:'short',ic:'coins',c:'#B3261E',sub:'adjusted against payables'})}${V.kpi({l:'Return rate',n:V.pct(rows.length,V.sum(d.grns,g=>V.sum(g.lines,l=>l.acc)))*10/10,f:'pct',ic:'target',c:'#0F6B6B',sub:'of inward units'})}</div>`
 +V.table('pr',{rows,cols:[{k:'no',l:'Return No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'vn',l:'Vendor'},{k:'grn',l:'GRN'},{k:'pcs',l:'Serials'},{k:'reason',l:'Reason'},{k:'dn',l:'Debit note'},{k:'amt',l:'Amount',fmt:'inr'}]})}});
V.acts.prNew=()=>{V.modal({title:'New Purchase Return',wide:true,body:`${V.field('Vendor *',`<select id="prv"><option value="">Select vendor</option>${V.opts(V.db.vendors.filter(v=>v.weave),'',{v:v=>v.id,l:v=>v.name})}</select>`)}<div id="prl" class="mute">Select a vendor to list returnable stock.</div>${V.field('Reason *','<select id="prr"><option>Zari tarnish found after QC re-check</option><option>Shade variation vs approved sample</option><option>Pallu weaving defect</option><option>Wrong design delivered</option><option>Other quality issue</option></select>')}`,
  onOpen:()=>{$('#prv').onchange=()=>{const ps=V.db.pieces.filter(p=>p.vendor===$('#prv').value&&p.status==='in_stock'&&['MAIN','VAULT'].includes(p.loc)&&p.trk==='serial').slice(0,40);$('#prl').innerHTML=ps.length?`<div class="tscroll" style="max-height:260px"><table class="t"><tbody>${ps.map(p=>`<tr><td><input type="checkbox" value="${p.u}"></td><td><b>${p.no}</b></td><td>${V.esc(V.m.item[p.sku].name)}</td><td>${p.grn}</td><td class="n">${V.inr(p.cost)}</td></tr>`).join('')}</tbody></table></div>`:'No returnable stock for this vendor.'}},
  foot:[{l:'Cancel'},{l:'Create return & debit note',cls:'primary',fn:()=>{const us=V.$$('#prl input:checked').map(x=>x.value);if(!us.length){V.toast('Select at least one serial','bad');return false}const v=$('#prv').value,r=V.L.purchaseReturn({vendor:v,grn:V.m.piece[us[0]].grn,units:us,reason:$('#prr').value,date:V.db.today,by:V.S.user});V.save();V.toast(`${r.no} · debit note ${r.dn} for ${V.inr(r.amt)}`);V.refresh()}}]})};

// ================= LOCAL PURCHASE =================
V.page('localpurchase',{title:'Local Purchase',crumb:'Procurement',
render(){const d=V.db,rows=d.localPurchases.slice().reverse().map(r=>Object.assign({},r,{vn:V.m.vendor[r.vendor]?V.m.vendor[r.vendor].name:r.vendor}));const bycat=V.group(d.localPurchases,x=>x.category);
 return V.head('Local Purchase','Spot buys — packing, blouse fabric, fixtures, repairs — with bill capture. Cash purchases hit the drawer; stock-in items flow to inventory.',`<button class="btn primary" data-act="lpNew">${V.ic('plus')} New Local Purchase</button>`)
 +`<div class="g g21" style="margin-bottom:18px">${V.card('Spend by category','All local purchases','<div class="cw sm"><canvas id="c-lp"></canvas></div>')}<div class="g" style="gap:18px">${V.kpi({l:'Local purchases',n:rows.length,ic:'shop',c:'#1E2A5E',sub:'entries'})}${V.kpi({l:'Total spend',n:V.sum(rows,r=>r.amt),f:'short',ic:'wallet',c:V.brand.accent,sub:'incl. GST '+V.short(V.sum(rows,r=>r.gst))})}</div></div>`
 +V.table('lp',{rows,cols:[{k:'no',l:'No',f:r=>`<b>${r.no}</b>`},{k:'date',l:'Date',fmt:'date'},{k:'vn',l:'Vendor'},{k:'category',l:'Category'},{k:'desc',l:'Description'},{k:'qty',l:'Qty',fmt:'num'},{k:'amt',l:'Amount',fmt:'inr'},{k:'gst',l:'GST (ITC)',fmt:'inr'},{k:'mode',l:'Paid by'},{k:'bill',l:'Bill'}].concat(V.basic?[]:[{k:'stockIn',l:'Stock-in',f:r=>r.stockIn?V.badge('Yes','info'):'—',v:r=>r.stockIn?'Yes':''}])})},
mount(){const m={};V.db.localPurchases.forEach(r=>m[r.category]=(m[r.category]||0)+r.amt);const k=Object.keys(m);V.chart('c-lp',{type:'bar',horizontal:true,labels:k,data:[{label:'Spend',data:k.map(x=>m[x]),color:'#1E2A5E'}],fmt:V.short,legend:false})}});
V.acts.lpNew=()=>V.modal({title:'New Local Purchase',wide:true,body:`<div class="frm">${V.field('Supplier',`<select name="vendor">${V.opts(V.db.vendors.filter(v=>v.type==='Local Supplier'),'',{v:v=>v.id,l:v=>v.name})}</select>`)}${V.field('Category','<select name="category"><option>Packing Material</option><option>Blouse Fabric</option><option>Display & Fixtures</option><option>Stationery</option><option>Repairs & Maintenance</option><option>Gift Boxes</option></select>')}${V.field('Description *','<input name="desc">','','full')}${V.field('Quantity','<input name="qty" type="number" value="1" min="1">')}${V.field('Rate incl. GST (₹)','<input name="rate" type="number" min="1">')}${V.field('Paid by','<select name="mode"><option>Cash</option><option>UPI</option><option>Card</option></select>','Cash creates a drawer cash-out entry')}${V.field('Bill no.','<input name="bill">')}${V.basic?'':'<div class="field full"><label><input type="checkbox" name="stockIn"> Add to stock as batch (e.g. blouse fabric)</label></div>'}</div>`,
  foot:[{l:'Cancel'},{l:'Save',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['desc','rate']))return false;const amt=+v.qty*+v.rate,no='LP-'+String(V.db.localPurchases.length+1).padStart(4,'0');
   V.db.localPurchases.push({no,date:V.db.today,vendor:v.vendor,loc:V.S.loc,category:v.category,desc:v.desc,qty:+v.qty,rate:+v.rate,amt,gst:Math.round(amt*.18/1.18),mode:v.mode,bill:v.bill,stockIn:v.stockIn,by:V.S.user});
   if(v.mode==='Cash'){const r=V.L.drawer(V.S.loc,V.db.today);if(r.status==='open')r.entries.push({t:'out',amt,reason:'Local purchase '+no,time:V.now(),by:V.S.user})}
   if(v.stockIn){const it=V.m.item['ACC-BLS'];const p=V.L.addPiece({no:V.L.serial(it,V.db.today,'batch'),trk:'batch',sku:'ACC-BLS',vendor:v.vendor,grn:no,loc:V.S.loc,qty:+v.qty,q0:+v.qty,cost:+v.rate,mrp:it.mrp,since:V.db.today});V.L.move(p,'GRN','Local',V.S.loc,no,V.db.today,V.S.user)}
   V.L.audit('Local purchase',no);V.save();V.toast(no+' saved');V.refresh()}}]});

// ================= VENDOR LEDGER =================
V.vendorLedger=id=>{const d=V.db,rows=[];d.grns.filter(g=>g.vendor===id).forEach(g=>rows.push({date:g.date,doc:g.no,type:'GRN (bill)',cr:g.value+g.freight,dr:0}));d.vpay.filter(p=>p.vendor===id).forEach(p=>rows.push({date:p.date,doc:p.id,type:p.type,cr:0,dr:p.amt,note:p.against}));d.purchaseReturns.filter(p=>p.vendor===id).forEach(p=>rows.push({date:p.date,doc:p.dn,type:'Debit note',cr:0,dr:p.amt}));
  rows.sort((a,b)=>a.date<b.date?-1:1);let b=0;rows.forEach(r=>{b+=r.cr-r.dr;r.bal=b});return rows};
V.page('vledger',{title:'Vendor Ledger',crumb:'Procurement',
render(id){const d=V.db;
 if(!id){const rows=d.vendors.map(v=>Object.assign({},v,{bal:V.vendorBal(v.id),adv:V.sum(d.vpay.filter(p=>p.vendor===v.id&&p.type==='Advance'),p=>p.amt)}));
  return V.head('Vendor Ledger','Payables, advances and debit notes per weaver.')+V.table('vl',{rows,cols:[{k:'name',l:'Vendor',f:r=>`<b>${V.esc(r.name)}</b>`},{k:'type',l:'Type'},{k:'terms',l:'Terms'},{k:'adv',l:'Advances paid',fmt:'inr'},{k:'bal',l:'Net payable',fmt:'inr'}],totals:['adv','bal'],onRow:r=>V.go('#/vledger/'+r.id)})}
 const v=V.m.vendor[id],rows=V.vendorLedger(id);
 return V.head(V.esc(v.name)+' — Ledger',`${v.city}, ${v.state} · ${v.terms}`,`<a class="btn" href="#/vledger">‹ All vendors</a><button class="btn primary" data-act="vpNew" data-id="${id}">${V.ic('plus')} Payment / Advance</button>`)
  +`<div class="g g3" style="margin-bottom:18px">${V.kpi({l:'Net payable',n:V.vendorBal(id),f:'inr',ic:'wallet',c:V.brand.primary,sub:'after payments & debit notes'})}${V.kpi({l:'Total purchases',n:V.sum(rows,r=>r.cr),f:'short',ic:'truck',c:'#1E2A5E',sub:rows.filter(r=>r.type==='GRN (bill)').length+' GRNs'})}${V.kpi({l:'Paid / adjusted',n:V.sum(rows,r=>r.dr),f:'short',ic:'check',c:'#2E8B57',sub:'payments, advances, debit notes'})}</div>`
  +V.table('vlg',{rows:rows.slice().reverse(),cols:[{k:'date',l:'Date',fmt:'date'},{k:'doc',l:'Document',f:r=>`<b>${r.doc}</b>`},{k:'type',l:'Type',fmt:'badge'},{k:'note',l:'Against',f:r=>r.note||''},{k:'cr',l:'Bill (Cr)',fmt:'inr'},{k:'dr',l:'Paid / DN (Dr)',fmt:'inr'},{k:'bal',l:'Balance',fmt:'inr'}]})}});
V.acts.vpNew=el=>{const id=el.dataset.id;V.modal({title:'Record vendor payment',body:`<div class="frm">${V.field('Type','<select name="type"><option>Payment</option><option>Advance</option></select>')}${V.field('Amount (₹) *','<input name="amt" type="number" min="1">')}${V.field('Mode','<select name="mode"><option>Bank Transfer</option><option>Cheque</option><option>UPI</option></select>')}${V.field('Reference / UTR','<input name="ref">')}${V.field('Against','<input name="against" placeholder="GRN / PO / purpose">','','full')}</div>`,foot:[{l:'Cancel'},{l:'Save',cls:'primary',fn:()=>{const v=V.formVals($('#mbg'));if(!V.need(v,['amt']))return false;V.db.vpay.push({id:V.L.next('vp','VP-',4),date:V.db.today,vendor:id,type:v.type,amt:+v.amt,mode:v.mode,ref:v.ref,against:v.against});V.L.audit('Vendor payment',id);V.save();V.toast('Recorded');V.refresh()}}]})};

// live recalculation while typing in the GRN pricing table
document.addEventListener('input',e=>{const t=e.target,k=t.dataset&&t.dataset.gp;if(!k||!V.S.grn)return;const [i,j,f]=k.split('.'),l=V.S.grn.lines[+i];if(!l||!l.pc)return;const r=l.pc[+j];V.grnPcSet(r,f,t.value);
  const put=(n,v)=>{if(n!==f){const el=document.getElementById(`gp-${i}-${j}-${n}`);if(el)el.value=v}};put('pct',r.pct);put('amt',r.amt);V.grnPcCells(+i,+j);V.grnPcTotals()});
V.acts.grnMk=el=>{const g=V.S.grn,which=el.dataset.i,v=Math.max(0,+(document.getElementById('mk-'+which)||{}).value||0);if(!(v>=0)){return}
  g.lines.forEach((l,i)=>{if(which==='all'||+which===i)(l.pc||[]).forEach(r=>V.grnPcSet(r,'pct',v))});V.refresh()};
})();
