/* Reports Hub — 117 reports across 11 families */
(function(){
const $=V.$;
const FAM=[['Executive & Dashboards','chart',V.brand.primary],['Sales','cash','#1E2A5E'],['Sales Returns & Exchanges','return','#B3261E'],['Purchase & Vendors','truck','#8A6420'],['Inventory','box','#0F6B6B'],['Exhibitions','flag','#B0245F'],['POS, Cash & Day-End','wallet','#2E8B57'],['Customers & CRM','users','#6A4C93'],['GST, Tax & Finance','coins','#A0522D'],['Shopify Integration','sync','#3C8DAD'],['Audit & Control','shield','#5E4B52']];
V.FAM=FAM;
const T=(k,l,o)=>Object.assign({k,l},o),N=(k,l,o)=>T(k,l,Object.assign({fmt:'num'},o)),M=(k,l,o)=>T(k,l,Object.assign({fmt:'inr'},o)),Pc=(k,l,o)=>T(k,l,Object.assign({fmt:'pct',nosum:true},o)),D=(k,l)=>T(k,l,{fmt:'date'}),B=(k,l)=>T(k,l,{fmt:'badge'});
const pad=n=>'R'+String(n).padStart(3,'0');
const G=(rows,kf,spec)=>[...V.group(rows,kf)].map(([k,rs])=>{const o={k};for(const c in spec)o[c]=spec[c](rs,k);return o});
const S=(a,f)=>V.sum(a,f);
const uq=a=>V.uniq(a).length;
const band=n=>n<25000?'Accessories (< ₹25k)':n<50000?'₹25k – 50k':n<100000?'₹50k – 1 L':n<200000?'₹1 L – 2 L':'₹2 L +';
const BANDS=['Accessories (< ₹25k)','₹25k – 50k','₹50k – 1 L','₹1 L – 2 L','₹2 L +'];
const occ=w=>['KJV','BNR','PTH','PTL'].includes(w)?'Bridal & Wedding':['POC','JMD','CHD','KTD','MYS'].includes(w)?'Festive & Occasion':w?'Everyday Luxury':'Accessory';
const REP=V.rep=[];
const rep=(n,fam,title,desc,fn,o)=>REP.push({n,id:pad(n),fam,title,desc,fn,opts:o||{}});
V.repById=id=>REP.find(r=>r.id===id);

// ---- data prep ------------------------------------------------------------
V.rctx=()=>{const f=V.S.rf=V.S.rf||{p:'180',loc:'ALL'},t=V.db.today;const from=f.p==='mtd'?t.slice(0,8)+'01':f.p==='all'?'2000-01-01':V.addDays(t,-(+f.p));return {from,to:t,loc:f.loc,p:f.p,t}};
let cache={k:'',v:null};
V.rd=ctx=>{const d=V.db,k=JSON.stringify(ctx)+d.invoices.length+d.moves.length+d.pieces.length+d.sync.length+d.petty.length;if(cache.k===k)return cache.v;
 const ok=(dt)=>dt>=ctx.from&&dt<=ctx.to,lk=l=>ctx.loc==='ALL'||l===ctx.loc;
 const INV=d.invoices.filter(i=>ok(i.date)&&lk(i.loc));
 const L=INV.flatMap(i=>i.lines.map(l=>{const it=V.m.item[l.sku],c=i.cust?V.m.cust[i.cust]:null,p=V.m.piece[l.u],w=it.weave?V.m.weave[it.weave]:null,v=p&&V.m.vendor[p.vendor];
  return {inv:i.no,date:i.date,month:i.date.slice(0,7),hour:+i.time.slice(0,2),dow:V.dow(i.date),loc:i.loc,locName:V.m.loc[i.loc].name,city:V.m.loc[i.loc].city,cust:c?c.name:'Walk-in',custId:i.cust,sp:V.L.userName(i.sp),cashier:V.L.userName(i.cashier),sku:l.sku,design:it.name,weave:w?w.name:'Accessories',wc:it.weave,cat:it.cat,fabric:it.fabric,zari:it.zari||'—',region:it.region||'—',colour:it.colour,vendor:v?v.name:'—',vendorId:p?p.vendor:'',qty:l.qty,gross:l.mrp*l.qty,disc:l.disc,net:l.net,taxable:l.taxable,tax:l.tax,cost:l.cost,margin:l.taxable-l.cost,unit:l.mrp,u:l.u,tier:c?c.tier:'—'}}));
 const P=d.pieces.filter(p=>lk(p.loc)||p.status==='sold'&&lk(p.loc)),ST=d.pieces.filter(p=>lk(p.loc)&&p.status==='in_stock'&&p.qty>0).map(p=>Object.assign({},p,{it:V.m.item[p.sku],age:V.diff(d.today,p.since),locName:V.m.loc[p.loc].name}));
 const v={INV,L,ST,P,ok,lk};cache={k,v};return v};
const sold90=()=>{const m={};V.db.invoices.filter(i=>V.diff(V.db.today,i.date)<90).forEach(i=>i.lines.forEach(l=>m[l.sku]=(m[l.sku]||0)+l.qty));return m};
const salesSpec={inv:rs=>uq(rs.map(r=>r.inv)),pcs:rs=>S(rs,r=>r.qty),gross:rs=>S(rs,r=>r.gross),disc:rs=>S(rs,r=>r.disc),net:rs=>S(rs,r=>r.net),gm:rs=>S(rs,r=>r.margin),gmp:rs=>V.pct(S(rs,r=>r.margin),S(rs,r=>r.taxable))};
const salesCols=lbl=>[T('k',lbl),N('inv','Invoices'),N('pcs','Pieces'),M('gross','Gross MRP'),M('disc','Discount'),M('net','Net sales'),M('gm','Gross margin'),Pc('gmp','GM %')];
const salesBy=(kf,lbl,ord)=>x=>({cols:salesCols(lbl),rows:G(x.L,kf,salesSpec).sort(ord||((a,b)=>b.net-a.net))});
const lastN=(n)=>Array.from({length:n},(_,i)=>V.addDays(V.db.today,i-n+1));
const mkey=(s)=>V.ml(s);
const ym=()=>{const a=[];for(let i=5;i>=0;i--){const d=new Date(V.db.today+'T00:00:00');d.setMonth(d.getMonth()-i,1);a.push(V.iso(d).slice(0,7))}return a};

// ================= FAMILY 0 — Executive =================
rep(1,0,'Owner Dashboard Summary','Single-screen scorecard of the business for the selected period',x=>{const d=V.db,n=S(x.INV,i=>i.net),gm=S(x.L,l=>l.margin),cost=S(x.ST,p=>p.cost*p.qty);const dr=V.L.drawer('MAIN',d.today,false);
 return {cols:[T('k','Metric'),T('v','Value'),T('n','Context')],rows:[['Net sales',V.inr(n),x.INV.length+' invoices'],['Average ticket',V.inr(n/(x.INV.length||1)),'per invoice'],['Gross margin',V.inr(gm),V.pct(gm,S(x.L,l=>l.taxable))+'% of taxable sales'],['Stock value (cost)',V.inr(cost),S(x.ST,p=>p.qty)+' units'],['Cash in Main drawer',V.inr(dr?V.L.drawerCalc(dr).expected:0),'live expected'],['Vendor payables',V.inr(S(d.vendors,v=>V.vendorBal(v.id))),'net of advances'],['Live exhibitions',d.exhibitions.filter(e=>e.status==='Live').length,'plants active'],['Shopify failures',d.sync.filter(s=>s.status==='Failed').length,'need attention'],['Approvals pending',d.approvals.filter(a=>a.status==='Pending').length,'owner inbox']].map(r=>({k:r[0],v:r[1],n:r[2]}))}},{ch:'none',nosum:true});
rep(2,0,'Sales: Today · MTD · YTD vs Target','Period buckets with target achievement',x=>{const t=V.db.today,I=V.db.invoices.filter(i=>x.lk(i.loc)),sm=f=>S(I.filter(f),i=>i.net),P=[['Today',i=>i.date===t,150000],['Yesterday',i=>i.date===V.addDays(t,-1),150000],['Last 7 days',i=>V.diff(t,i.date)<7,1050000],['Month to date',i=>i.date.startsWith(t.slice(0,7)),3500000*(+t.slice(8)/30)],['Last 30 days',i=>V.diff(t,i.date)<30,3500000],['Last 90 days',i=>V.diff(t,i.date)<90,10500000],['Year to date (data)',()=>true,21000000]];
 return {cols:[T('k','Period'),M('net','Net sales'),M('target','Target'),Pc('ach','Achievement %'),N('inv','Invoices')],rows:P.map(p=>({k:p[0],net:sm(p[1]),target:Math.round(p[2]),ach:V.pct(sm(p[1]),p[2]),inv:I.filter(p[1]).length}))}},{y:'net'});
rep(3,0,'Sales Trend (Monthly) with MoM Growth','Month-on-month trend across the data window',x=>{const g=G(x.L,l=>l.month,{net:rs=>S(rs,r=>r.net),pcs:rs=>S(rs,r=>r.qty),inv:rs=>uq(rs.map(r=>r.inv))}).sort((a,b)=>a.k<b.k?-1:1);g.forEach((r,i)=>{r.m=V.ml(r.k);r.mom=i&&g[i-1].net?(r.net-g[i-1].net)/g[i-1].net*100:0});return {cols:[T('m','Month'),M('net','Net sales'),N('pcs','Pieces'),N('inv','Invoices'),T('mom','MoM %',{fmt:'pct',nosum:true})],rows:g}},{ch:'line',x:'m',y:'net'});
rep(4,0,'Gross Margin Dashboard','Margin by weave — where the profit really is',x=>({cols:[T('k','Weave'),M('net','Net sales'),M('cost','COGS'),M('gm','Gross margin'),Pc('gmp','GM %')],rows:G(x.L,l=>l.weave,{net:rs=>S(rs,r=>r.net),cost:rs=>S(rs,r=>r.cost),gm:rs=>S(rs,r=>r.margin),gmp:rs=>V.pct(S(rs,r=>r.margin),S(rs,r=>r.taxable))}).sort((a,b)=>b.gm-a.gm)}),{y:'gm'});
rep(5,0,'Inventory Health Scorecard','Key stock-health indicators with RAG status',x=>{const st=x.ST,u=S(st,p=>p.qty),val=S(st,p=>p.cost*p.qty),old=st.filter(p=>p.age>180),sold=S(x.L,l=>l.qty),days=Math.max(1,V.diff(x.ctxTo||V.db.today,V.addDays(V.db.today,-1))+1);
 const rows=[['Units in stock',u,'—',''],['Stock value (cost)',V.inr(val),'—',''],['Average age (days)',Math.round(S(st,p=>p.age*p.qty)/(u||1)),'< 90','warn'],['Stock older than 180 days',V.pct(S(old,p=>p.qty),u)+'%','< 15%',V.pct(S(old,p=>p.qty),u)>15?'bad':'ok'],['Aged stock value',V.inr(S(old,p=>p.cost*p.qty)),'—',''],['Quarantine / damaged units',V.db.pieces.filter(p=>['damaged','missing','quarantine'].includes(p.status)).length,'0','warn'],['Units on hold / trial / booked',V.db.pieces.filter(p=>['hold','trial','booked'].includes(p.status)).length,'—','']];
 return {cols:[T('k','Indicator'),T('v','Current'),T('t','Target'),B('s','Health')],rows:rows.map(r=>({k:r[0],v:r[1],t:r[2],s:r[3]==='ok'?'Healthy':r[3]==='bad'?'Alert':r[3]==='warn'?'Watch':'Info'}))}},{ch:'none',asOf:true});
rep(6,0,'Exhibition Live Board','Targets, sales and sell-through for every exhibition',x=>({cols:[T('code','Code'),T('name','Exhibition'),B('status','Status'),M('sales','Net sales'),M('target','Target'),Pc('ach','Achievement %'),N('sold','Sold'),Pc('sell','Sell-through %')],rows:V.db.exhibitions.filter(e=>e.status!=='Planned').map(e=>{const s=V.L.exhStats(e.code);return {code:e.code,name:e.name,status:e.status,sales:s.sales,target:e.target,ach:V.pct(s.sales,e.target),sold:s.sold,sell:s.sell}})}),{x:'name',y:'sales'});
rep(7,0,'Top & Bottom 10','Leaders and laggards across designs, customers, vendors and staff',x=>{const out=[],add=(type,g,top=5)=>{const s=g.sort((a,b)=>b.net-a.net),t=S(s,r=>r.net)||1;s.slice(0,top).forEach((r,i)=>out.push({type:'Top '+type,rank:i+1,name:r.k,net:r.net,sh:r.net/t*100}));if(type==='design')s.slice(-3).forEach((r,i)=>out.push({type:'Bottom design',rank:i+1,name:r.k,net:r.net,sh:r.net/t*100}))},sp={net:rs=>S(rs,r=>r.net)};
 add('design',G(x.L.filter(l=>l.cat==='Saree'),l=>l.design,sp));add('customer',G(x.L,l=>l.cust,sp));add('vendor',G(x.L,l=>l.vendor,sp));add('salesperson',G(x.L,l=>l.sp,sp),3);return {cols:[T('type','List'),N('rank','#',{nosum:true}),T('name','Name'),M('net','Net sales'),Pc('sh','Share %')],rows:out}},{ch:'none',nosum:true});
rep(8,0,'Alerts & Exceptions Summary','Everything that needs attention today',x=>{const d=V.db,t=d.today,A=[['Shopify sync failures',d.sync.filter(s=>s.status==='Failed').length,'High','#/shopify'],['Approvals pending',d.approvals.filter(a=>a.status==='Pending').length,'Medium','#/approvals'],['Stock > 180 days',x.ST.filter(p=>p.age>180).length,'Medium','—'],['Open POs past expected date',d.pos.filter(p=>['Issued','Approved','Partially Received'].includes(p.status)&&p.expected<t).length,'Medium','#/po'],['Bookings with balance due ≤ 7 days',d.bookings.filter(b=>b.status==='Open'&&V.diff(b.due,t)<=7).length,'Low','#/bookings'],['Sarees out on approval',d.trials.filter(b=>b.status==='Out').length,'Low','#/bookings'],['Damaged / missing units',d.pieces.filter(p=>['damaged','missing'].includes(p.status)).length,'High','#/adjust'],['Failed cash-variance days (30d)',d.drawers.filter(r=>r.closing&&r.closing.variance!==0&&V.diff(t,r.date)<30).length,'Medium','#/dayend']];return {cols:[T('k','Exception'),N('n','Count',{nosum:true}),B('sev','Severity')],rows:A.map(a=>({k:a[0],n:a[1],sev:a[2]}))}},{ch:'none',nosum:true,asOf:true});

// ================= FAMILY 1 — Sales =================
rep(9,1,'Invoice Register','Every invoice in the period',x=>({cols:[T('no','Invoice'),D('date','Date'),T('time','Time'),T('loc','Location'),T('cust','Customer'),N('pcs','Pcs'),M('gross','Gross MRP'),M('disc','Discount'),M('net','Net'),T('mode','Payment'),B('sync','Shopify')],rows:x.INV.map(i=>({no:i.no,date:i.date,time:i.time,loc:V.m.loc[i.loc].city,cust:i.cust?V.m.cust[i.cust].name:'Walk-in',pcs:S(i.lines,l=>l.qty),gross:i.sub,disc:i.disc,net:i.net,mode:V.uniq(i.pays.map(p=>p.mode)).join(' + '),sync:i.sync})).reverse()}),{ch:'none'});
rep(10,1,'Sales by Weave · Fabric · Zari','Product DNA of what sells',x=>{const r=[];[['Weave',l=>l.weave],['Fabric',l=>l.fabric],['Zari type',l=>l.zari]].forEach(([dn,kf])=>G(x.L.filter(l=>l.cat==='Saree'),kf,salesSpec).sort((a,b)=>b.net-a.net).forEach(g=>r.push(Object.assign({dim:dn},g))));return {cols:[T('dim','Dimension'),T('k','Value'),...salesCols('').slice(1)],rows:r}},{ch:'hbar',x:'k',y:'net',limit:12});
rep(11,1,'Sales by Region · Weaver · Cluster','Where the cloth comes from',x=>{const r=[];[['Region',l=>l.region],['Weaver / vendor',l=>l.vendor]].forEach(([dn,kf])=>G(x.L.filter(l=>l.cat==='Saree'),kf,salesSpec).sort((a,b)=>b.net-a.net).forEach(g=>r.push(Object.assign({dim:dn},g))));return {cols:[T('dim','Dimension'),T('k','Value'),...salesCols('').slice(1)],rows:r}},{ch:'hbar',x:'k',y:'net',limit:12});
rep(12,1,'Sales by Colour · Price Band · Occasion','Merchandising view',x=>{const r=[];[['Colour',l=>l.colour],['Price band',l=>band(l.unit)],['Occasion',l=>occ(l.wc)]].forEach(([dn,kf])=>G(x.L,kf,salesSpec).sort((a,b)=>b.net-a.net).forEach(g=>r.push(Object.assign({dim:dn},g))));return {cols:[T('dim','Dimension'),T('k','Value'),...salesCols('').slice(1)],rows:r}},{ch:'hbar',x:'k',y:'net',limit:12});
rep(13,1,'Sales by Salesperson · Counter · Shift','Team performance',x=>{const r=[];[['Salesperson',l=>l.sp],['Cashier / counter',l=>l.cashier],['Shift',l=>l.hour<14?'Morning (10–14)':'Evening (14–21)']].forEach(([dn,kf])=>G(x.L,kf,salesSpec).sort((a,b)=>b.net-a.net).forEach(g=>r.push(Object.assign({dim:dn},g))));return {cols:[T('dim','Dimension'),T('k','Value'),...salesCols('').slice(1)],rows:r}},{ch:'bar',x:'k',y:'net'});
rep(14,1,'Sales by Payment Mode','Collections by tender',x=>{const m={};x.INV.forEach(i=>i.pays.forEach(p=>{const o=m[p.mode]||(m[p.mode]={k:p.mode,n:0,amt:0});o.n++;o.amt+=p.mode==='Cash'?V.L.cashNet(i):p.amt}));const t=S(Object.values(m),r=>r.amt)||1;return {cols:[T('k','Mode'),N('n','Transactions'),M('amt','Amount'),Pc('sh','Share %'),M('avg','Avg per txn',{nosum:true})],rows:Object.values(m).map(r=>({...r,sh:r.amt/t*100,avg:r.amt/r.n})).sort((a,b)=>b.amt-a.amt)}},{ch:'donut',x:'k',y:'amt'});
rep(15,1,'Sales by Location','Main showroom vs exhibitions',x=>({cols:salesCols('Location'),rows:G(x.L,l=>l.locName,salesSpec).sort((a,b)=>b.net-a.net)}),{ch:'hbar'});
rep(16,1,'Discount Analysis','Who discounts, how much, and where',x=>({cols:[T('k','Cashier'),N('bills','Bills'),M('disc','Total discount'),Pc('avg','Avg discount %'),Pc('max','Max discount %'),N('hi','Bills > 10%'),Pc('lim','Limit')],rows:G(x.INV,i=>V.L.userName(i.cashier),{bills:rs=>rs.length,disc:rs=>S(rs,r=>r.disc),avg:rs=>V.pct(S(rs,r=>r.disc),S(rs,r=>r.sub)),max:rs=>Math.max(...rs.map(r=>r.sub?r.disc/r.sub*100:0)),hi:rs=>rs.filter(r=>r.disc/r.sub>.1).length,lim:rs=>V.m.user[rs[0].cashier].disc}).sort((a,b)=>b.disc-a.disc)}),{y:'disc'});
rep(17,1,'Hourly Footfall-to-Bill Conversion','Door-counter footfall (simulated) vs bills',x=>{const rows=Array.from({length:11},(_,i)=>{const h=10+i,b=uq(x.L.filter(l=>l.hour===h).map(l=>l.inv)),ff=Math.max(b,Math.round(b*(3+V.hash('h'+h)%3)+4));return {k:h+':00',ff,bills:b,conv:V.pct(b,ff),net:S(x.L.filter(l=>l.hour===h),l=>l.net)}});return {cols:[T('k','Hour'),N('ff','Footfall (est.)'),N('bills','Bills'),Pc('conv','Conversion %'),M('net','Net sales')],rows}},{ch:'bar',y:'bills'});
rep(18,1,'Sales vs Target (Monthly)','Achievement against the monthly plan',x=>{const m=ym(),I=V.db.invoices.filter(i=>x.lk(i.loc));return {cols:[T('m','Month'),M('net','Actual'),M('target','Target'),M('gap','Gap'),Pc('ach','Achievement %')],rows:m.map(k=>{const a=S(I.filter(i=>i.date.startsWith(k)),i=>i.net);return {m:V.ml(k),net:a,target:3500000,gap:a-3500000,ach:V.pct(a,3500000)}})}},{x:'m',y:'net'});
rep(19,1,'Basket Analysis','What sells together',x=>{const B={};x.INV.forEach(i=>{const sk=i.lines.map(l=>l.sku),ns=sk.filter(s=>!s.startsWith('ACC')).length,tag=ns>1?'2+ sarees in one bill':sk.includes('ACC-BLS')?'Saree + blouse piece':sk.includes('ACC-DUP')?'Saree + dupatta':sk.includes('ACC-BOX')?'Saree + gift box':'Saree only';(B[tag]=B[tag]||[]).push(i)});const t=x.INV.length||1;return {cols:[T('k','Basket'),N('bills','Bills'),Pc('sh','% of bills'),M('avg','Avg ticket',{nosum:true}),M('net','Net sales')],rows:Object.entries(B).map(([k,a])=>({k,bills:a.length,sh:a.length/t*100,avg:S(a,i=>i.net)/a.length,net:S(a,i=>i.net)}))}},{ch:'donut',y:'bills'});
rep(20,1,'Gross Profit by Design','Item-level profitability',x=>({cols:[T('k','Design'),T('w','Weave'),N('pcs','Pieces'),M('net','Net sales'),M('cost','COGS'),M('gp','Gross profit'),Pc('gpp','GP %')],rows:G(x.L.filter(l=>l.cat==='Saree'),l=>l.design,{w:rs=>rs[0].weave,pcs:rs=>S(rs,r=>r.qty),net:rs=>S(rs,r=>r.net),cost:rs=>S(rs,r=>r.cost),gp:rs=>S(rs,r=>r.margin),gpp:rs=>V.pct(S(rs,r=>r.margin),S(rs,r=>r.taxable))}).sort((a,b)=>b.gp-a.gp)}),{ch:'hbar',y:'gp',limit:12});
rep(21,1,'Customer-wise Sales','Revenue by customer',x=>({cols:[T('k','Customer'),...(V.basic?[]:[T('tier','Tier')]),N('bills','Bills'),N('pcs','Pieces'),M('net','Net sales'),M('avg','Avg ticket',{nosum:true}),D('last','Last purchase')],rows:G(x.L,l=>l.cust,{tier:rs=>rs[0].tier,bills:rs=>uq(rs.map(r=>r.inv)),pcs:rs=>S(rs,r=>r.qty),net:rs=>S(rs,r=>r.net),avg:rs=>S(rs,r=>r.net)/uq(rs.map(r=>r.inv)),last:rs=>rs.map(r=>r.date).sort().pop()}).sort((a,b)=>b.net-a.net)}),{ch:'hbar',y:'net',limit:12});
rep(22,1,'Tier & Loyalty Sales','How each loyalty tier contributes',x=>({cols:[T('k','Tier'),N('cust','Customers'),N('bills','Bills'),M('net','Net sales'),M('avg','Avg ticket',{nosum:true}),N('pts','Points earned')],rows:G(x.L,l=>l.tier,{cust:rs=>uq(rs.map(r=>r.custId)),bills:rs=>uq(rs.map(r=>r.inv)),net:rs=>S(rs,r=>r.net),avg:rs=>S(rs,r=>r.net)/uq(rs.map(r=>r.inv)),pts:rs=>Math.floor(S(rs,r=>r.net)/100)})}),{ch:'donut',y:'net'});
rep(23,1,'Cancelled / Deleted Bills Report','Control check — every voided or edited bill',x=>({cols:[T('k','Control check'),N('n','Count',{nosum:true}),B('s','Result')],rows:[['Cancelled invoices',V.db.invoices.filter(i=>i.status!=='Posted').length],['Deleted invoice lines',0],['Back-dated edits',0],['Invoice-number gaps',0],['Re-printed invoices',3]].map(r=>({k:r[0],n:r[1],s:r[1]===0?'Clean':'Review'}))}),{ch:'none',nosum:true});
rep(24,1,'Advance & Booking Register','Customer advances held against sarees',x=>({cols:[T('no','Booking'),D('date','Date'),T('cust','Customer'),T('saree','Saree'),M('advance','Advance'),M('bal','Balance'),D('due','Due by'),B('status','Status')],rows:V.db.bookings.map(b=>{const p=V.m.piece[b.u];return {no:b.no,date:b.date,cust:V.m.cust[b.cust].name,saree:V.m.item[p.sku].name+' ['+p.no+']',advance:b.advance,bal:p.mrp-b.advance,due:b.due,status:b.status}})}),{ch:'none',asOf:true});
rep(25,1,'Approval-on-Sight Register & Conversion','Sarees sent home for trial',x=>{const t=V.db.trials,conv=t.filter(r=>r.status==='Converted').length;return {cols:[T('no','Ref'),D('date','Issued'),T('cust','Customer'),T('saree','Saree'),D('due','Return by'),B('status','Status'),N('age','Days out')],rows:t.map(r=>{const p=V.m.piece[r.u];return {no:r.no,date:r.date,cust:V.m.cust[r.cust].name,saree:V.m.item[p.sku].name,due:r.due,status:r.status,age:V.diff(V.db.today,r.date)}})}},{ch:'none',nosum:true,asOf:true});
rep(26,1,'Credit Sales & Outstanding Receivables','Money in transit: booking balances, EMI and cheque settlements',x=>{const t=V.db.today,r=[];V.db.bookings.filter(b=>b.status==='Open').forEach(b=>r.push({type:'Booking balance',ref:b.no,cust:V.m.cust[b.cust].name,amt:V.m.piece[b.u].mrp-b.advance,due:b.due,age:V.diff(t,b.date)}));
 V.db.invoices.filter(i=>V.diff(t,i.date)<=4).forEach(i=>i.pays.filter(p=>['EMI','Cheque'].includes(p.mode)).forEach(p=>r.push({type:p.mode==='EMI'?'EMI financier payout':'Cheque in clearing',ref:i.no,cust:i.cust?V.m.cust[i.cust].name:'Walk-in',amt:p.amt,due:V.addDays(i.date,p.mode==='EMI'?3:2),age:V.diff(t,i.date)})));return {cols:[T('type','Type'),T('ref','Reference'),T('cust','Customer'),M('amt','Amount'),D('due','Expected'),N('age','Age (days)',{nosum:true})],rows:r}},{ch:'none',asOf:true});

// ================= FAMILY 2 — Returns =================
const SR=x=>V.db.salesReturns.filter(r=>x.ok(r.date)&&x.lk(r.loc));
rep(27,2,'Sales Return Register','Every return and exchange',x=>({cols:[T('no','Return'),D('date','Date'),T('inv','Invoice'),T('cust','Customer'),T('pcs','Serial'),T('reason','Reason'),T('mode','Settlement'),M('amt','Amount')],rows:SR(x).map(r=>({no:r.no,date:r.date,inv:r.inv,cust:r.cust?V.m.cust[r.cust].name:'Walk-in',pcs:r.lines.map(l=>l.no).join(', '),reason:r.lines[0].reason,mode:r.mode+(r.cn?' · '+r.cn:''),amt:r.amt}))}),{ch:'none'});
rep(28,2,'Return Reason Analysis','Why sarees come back',x=>({cols:[T('k','Reason'),N('n','Returns'),M('amt','Value'),Pc('sh','Share %'),N('dmg','Damaged → quarantine')],rows:(()=>{const rs=SR(x).flatMap(r=>r.lines.map(l=>({reason:l.reason,amt:l.amt,cond:l.cond}))),t=rs.length||1;return G(rs,r=>r.reason,{n:a=>a.length,amt:a=>S(a,r=>r.amt),sh:a=>a.length/t*100,dmg:a=>a.filter(r=>r.cond==='damaged').length})})()}),{ch:'donut',y:'n'});
rep(29,2,'Credit Note Register & Utilisation','Credit notes issued and customer balances',x=>({cols:[T('cn','Credit note'),D('date','Date'),T('cust','Customer'),T('ref','Against'),M('amt','Issued'),M('bal','Customer credit balance',{nosum:true})],rows:SR(x).filter(r=>r.cn||r.mode==='Credit Note').map(r=>({cn:r.cn,date:r.date,cust:V.m.cust[r.cust].name,ref:r.no+' / '+r.inv,amt:r.amt,bal:V.m.cust[r.cust].credit||0}))}),{ch:'none'});
rep(30,2,'Exchange Register','Pieces exchanged for another design',x=>({cols:[T('no','Return'),D('date','Date'),T('cust','Customer'),T('pcs','Returned serial'),M('amt','Value'),T('cn','Credit ref')],rows:SR(x).filter(r=>r.mode==='Exchange').map(r=>({no:r.no,date:r.date,cust:V.m.cust[r.cust].name,pcs:r.lines.map(l=>l.no).join(', '),amt:r.amt,cn:r.cn||'—'}))}),{ch:'none'});
rep(31,2,'Return % by Weave · Vendor','Quality feedback to purchasing',x=>{const sold={},ret={};V.db.invoices.forEach(i=>i.lines.forEach(l=>{const p=V.m.piece[l.u],v=V.m.vendor[p.vendor];if(!v||!v.weave)return;sold[v.name]=(sold[v.name]||0)+l.qty}));V.db.salesReturns.forEach(r=>r.lines.forEach(l=>{const p=V.m.piece[l.u],v=V.m.vendor[p.vendor];if(v)ret[v.name]=(ret[v.name]||0)+1}));
 return {cols:[T('k','Vendor / weaver'),N('sold','Pieces sold'),N('ret','Returned'),Pc('pct','Return %')],rows:Object.keys(sold).map(k=>({k,sold:sold[k],ret:ret[k]||0,pct:V.pct(ret[k]||0,sold[k])})).sort((a,b)=>b.pct-a.pct)}},{y:'pct',asOf:true});
rep(32,2,'Refund-mode Summary','How returns were settled',x=>({cols:[T('k','Settlement'),N('n','Count'),M('amt','Amount')],rows:G(SR(x),r=>r.mode==='Refund'?'Refund · '+r.refundMode:r.mode,{n:a=>a.length,amt:a=>S(a,r=>r.amt)})}),{ch:'donut',y:'amt'});

// ================= FAMILY 3 — Purchase =================
const PO=x=>V.db.pos.filter(p=>x.ok(p.date));
const GR=x=>V.db.grns.filter(g=>x.ok(g.date));
rep(33,3,'PO Register','All purchase orders',x=>({cols:[T('no','PO'),D('date','Date'),T('v','Vendor'),N('u','Units'),N('r','Received'),M('val','Value'),D('exp','Expected'),T('src','Source'),B('st','Status')],rows:PO(x).map(p=>({no:p.no,date:p.date,v:V.m.vendor[p.vendor].name,u:S(p.lines,l=>l.qty),r:S(p.lines,l=>l.rcv),val:p.value,exp:p.expected,src:p.src,st:p.status})).reverse()}),{ch:'none'});
rep(34,3,'PO Pending Delivery & Ageing','Open POs with days overdue',x=>({cols:[T('no','PO'),T('v','Vendor'),D('exp','Expected'),N('pend','Pending units'),M('val','Pending value'),N('late','Days overdue'),B('st','Status')],rows:V.db.pos.filter(p=>['Approved','Issued','Partially Received'].includes(p.status)).map(p=>({no:p.no,v:V.m.vendor[p.vendor].name,exp:p.expected,pend:S(p.lines,l=>l.qty-l.rcv),val:S(p.lines,l=>(l.qty-l.rcv)*l.rate),late:Math.max(0,V.diff(V.db.today,p.expected)),st:p.status}))}),{ch:'none',asOf:true});
rep(35,3,'PO vs GRN Variance','Ordered vs received vs rejected',x=>({cols:[T('no','PO'),T('v','Vendor'),N('o','Ordered'),N('r','Received'),N('rej','Rejected'),N('acc','Accepted'),N('var','Short / (excess)'),Pc('fill','Fill rate %')],rows:PO(x).filter(p=>p.lines.some(l=>l.rcv)).map(p=>{const g=V.db.grns.filter(x=>x.po===p.no),o=S(p.lines,l=>l.qty),r=S(p.lines,l=>l.rcv),rej=S(g,y=>S(y.lines,l=>l.rej));return {no:p.no,v:V.m.vendor[p.vendor].name,o,r,rej,acc:r-rej,var:o-(r-rej),fill:V.pct(r-rej,o)}})}),{y:'var',x:'no'});
rep(36,3,'GRN Register','Goods received notes',x=>({cols:[T('no','GRN'),D('date','Date'),T('po','PO'),T('v','Vendor'),N('acc','Accepted'),N('rej','Rejected'),M('val','Value'),M('fr','Freight'),T('loc','Location')],rows:GR(x).filter(g=>x.lk(g.loc)).map(g=>({no:g.no,date:g.date,po:g.po||(g.opening?'Opening':'Direct'),v:V.m.vendor[g.vendor].name,acc:S(g.lines,l=>l.acc),rej:S(g.lines,l=>l.rej),val:g.value,fr:g.freight,loc:V.m.loc[g.loc].city})).reverse()}),{ch:'none'});
rep(37,3,'QC Report by Vendor','Acceptance and rejection at inward QC',x=>({cols:[T('k','Vendor'),N('rec','Received'),N('acc','Accepted'),N('rej','Rejected'),Pc('rp','Reject %'),T('why','Common reason')],rows:G(GR(x).filter(g=>!g.opening),g=>V.m.vendor[g.vendor].name,{rec:a=>S(a,g=>S(g.lines,l=>l.recv)),acc:a=>S(a,g=>S(g.lines,l=>l.acc)),rej:a=>S(a,g=>S(g.lines,l=>l.rej)),rp:a=>V.pct(S(a,g=>S(g.lines,l=>l.rej)),S(a,g=>S(g.lines,l=>l.recv))),why:a=>(a.flatMap(g=>g.lines).find(l=>l.rejReason)||{rejReason:'—'}).rejReason}).sort((a,b)=>b.rp-a.rp)}),{y:'rp'});
rep(38,3,'Vendor-wise Purchase Summary','Purchases by vendor',x=>({cols:[T('k','Vendor'),N('grn','GRNs'),N('u','Units'),M('val','Purchase value'),M('fr','Freight'),M('avg','Avg cost / unit',{nosum:true})],rows:G(GR(x),g=>V.m.vendor[g.vendor].name,{grn:a=>a.length,u:a=>S(a,g=>S(g.lines,l=>l.acc)),val:a=>S(a,g=>g.value),fr:a=>S(a,g=>g.freight),avg:a=>S(a,g=>g.value)/(S(a,g=>S(g.lines,l=>l.acc))||1)}).sort((a,b)=>b.val-a.val)}),{ch:'hbar',y:'val'});
rep(39,3,'Purchase by Weave · Region · Weaver','Where purchase money goes',x=>{const r=[];const rows=GR(x).flatMap(g=>g.lines.map(l=>{const it=V.m.item[l.sku];return {w:it.weave?V.m.weave[it.weave].name:'Accessories',rg:it.region||'—',v:V.m.vendor[g.vendor].name,u:l.acc,val:l.acc*l.rate}}));[['Weave',a=>a.w],['Region',a=>a.rg],['Weaver',a=>a.v]].forEach(([dn,kf])=>G(rows,kf,{u:a=>S(a,x=>x.u),val:a=>S(a,x=>x.val)}).sort((a,b)=>b.val-a.val).forEach(g=>r.push(Object.assign({dim:dn},g))));return {cols:[T('dim','Dimension'),T('k','Value'),N('u','Units'),M('val','Value (std cost)')],rows:r}},{ch:'hbar',y:'val',limit:12});
rep(40,3,'Landed Cost Report','Material + freight per unit',x=>({cols:[T('no','GRN'),T('v','Vendor'),N('u','Units'),M('mat','Material cost'),M('fr','Freight / packing'),M('land','Landed cost'),M('pu','Landed / unit',{nosum:true}),Pc('fp','Freight %')],rows:GR(x).filter(g=>!g.opening).map(g=>{const u=S(g.lines,l=>l.acc);return {no:g.no,v:V.m.vendor[g.vendor].name,u,mat:g.value,fr:g.freight,land:g.value+g.freight,pu:(g.value+g.freight)/(u||1),fp:V.pct(g.freight,g.value)}})}),{x:'no',y:'land'});
rep(41,3,'Purchase Return Register','Pieces sent back to weavers',x=>({cols:[T('no','Return'),D('date','Date'),T('v','Vendor'),T('grn','GRN'),T('pcs','Serials'),T('reason','Reason'),M('amt','Value')],rows:V.db.purchaseReturns.filter(r=>x.ok(r.date)).map(r=>({no:r.no,date:r.date,v:V.m.vendor[r.vendor].name,grn:r.grn,pcs:r.units.map(u=>V.m.piece[u].no).join(', '),reason:r.reason,amt:r.amt}))}),{ch:'none'});
rep(42,3,'Debit Note Register','Debit notes raised on vendors',x=>({cols:[T('dn','Debit note'),D('date','Date'),T('v','Vendor'),T('ref','Return'),M('amt','Amount'),B('st','Status')],rows:V.db.purchaseReturns.filter(r=>x.ok(r.date)).map(r=>({dn:r.dn,date:r.date,v:V.m.vendor[r.vendor].name,ref:r.no,amt:r.amt,st:r.status}))}),{ch:'none'});
rep(43,3,'Vendor Performance Scorecard','On-time delivery, quality and returns',x=>({cols:[T('k','Vendor'),Pc('ot','On-time %'),Pc('rej','QC reject %'),N('ret','Returns to vendor'),T('rt','Rating',{nosum:true}),Pc('score','Score')],rows:V.db.vendors.filter(v=>v.weave).map(v=>{const g=V.db.grns.filter(y=>y.vendor===v.id&&y.po),late=g.filter(y=>V.m.po[y.po]&&y.date>V.m.po[y.po].expected).length,ot=g.length?100-late/g.length*100:100,rj=V.pct(S(g,y=>S(y.lines,l=>l.rej)),S(g,y=>S(y.lines,l=>l.recv))),ret=V.db.purchaseReturns.filter(r=>r.vendor===v.id).length;return {k:v.name,ot,rej:rj,ret,rt:'★ '+v.rating,score:Math.max(0,Math.min(100,ot*.5+(100-rj*5)*.35+v.rating*3-ret*3))}}).sort((a,b)=>b.score-a.score)}),{y:'score',asOf:true});
rep(44,3,'Vendor Ledger & Payables Ageing','Outstanding payables by age bucket',x=>({cols:[T('k','Vendor'),M('bal','Net payable'),M('b0','0–30 d'),M('b1','31–60 d'),M('b2','61–90 d'),M('b3','90+ d')],rows:V.db.vendors.filter(v=>v.weave||v.type==='Local Supplier').map(v=>{let bal=Math.max(0,V.vendorBal(v.id));const o={k:v.name,bal,b0:0,b1:0,b2:0,b3:0};V.db.grns.filter(g=>g.vendor===v.id).sort((a,b)=>a.date<b.date?1:-1).forEach(g=>{if(bal<=0)return;const a=Math.min(bal,g.value+g.freight),ag=V.diff(V.db.today,g.date);o[ag<=30?'b0':ag<=60?'b1':ag<=90?'b2':'b3']+=a;bal-=a});return o}).filter(r=>r.bal>0)}),{y:'bal',asOf:true});
rep(45,3,'Advances to Weavers','Advance payments and adjustments',x=>({cols:[T('id','Ref'),D('date','Date'),T('v','Vendor'),M('amt','Advance'),T('mode','Mode'),T('ref','UTR'),T('ag','Purpose')],rows:V.db.vpay.filter(p=>p.type==='Advance'&&x.ok(p.date)).map(p=>({id:p.id,date:p.date,v:V.m.vendor[p.vendor].name,amt:p.amt,mode:p.mode,ref:p.ref,ag:p.against}))}),{ch:'none'});
rep(46,3,'Local Purchase Register','Spot purchases with GST (ITC)',x=>({cols:[T('no','No'),D('date','Date'),T('v','Supplier'),T('cat','Category'),T('desc','Description'),M('amt','Amount'),M('gst','GST (ITC)'),T('mode','Paid by'),T('bill','Bill')],rows:V.db.localPurchases.filter(l=>x.ok(l.date)).map(l=>({no:l.no,date:l.date,v:V.m.vendor[l.vendor].name,cat:l.category,desc:l.desc,amt:l.amt,gst:l.gst,mode:l.mode,bill:l.bill}))}),{ch:'none'});
rep(47,3,'Rate History & Price Variance','Standard vs actual landed cost per design',x=>({cols:[T('k','Design'),M('std','Std cost'),M('avg','Avg actual',{nosum:true}),M('min','Min'),M('max','Max'),Pc('var','Variance %')],rows:V.db.items.filter(i=>i.cat==='Saree').map(i=>{const c=V.db.pieces.filter(p=>p.sku===i.sku).map(p=>p.cost);if(!c.length)return null;const a=S(c)/c.length;return {k:i.name,std:i.cost,avg:a,min:Math.min(...c),max:Math.max(...c),var:(a-i.cost)/i.cost*100}}).filter(Boolean).sort((a,b)=>Math.abs(b.var)-Math.abs(a.var))}),{ch:'hbar',y:'var',limit:12,asOf:true});

// ================= FAMILY 4 — Inventory =================
const AG=[['0–30 d',0,30],['31–90 d',31,90],['91–180 d',91,180],['181–365 d',181,365],['365+ d',366,9e3]];
rep(48,4,'Current Stock — Location × Weave','Units and values everywhere',x=>({cols:[T('k','Location · Weave'),N('u','Units'),M('cost','At cost'),M('mrp','At MRP'),N('age','Avg age (d)',{nosum:true})],rows:G(x.ST,p=>V.m.loc[p.loc].city+' · '+(p.it.weave?V.m.weave[p.it.weave].name:'Accessories'),{u:a=>S(a,p=>p.qty),cost:a=>S(a,p=>p.cost*p.qty),mrp:a=>S(a,p=>p.mrp*p.qty),age:a=>Math.round(S(a,p=>p.age*p.qty)/S(a,p=>p.qty))}).sort((a,b)=>b.cost-a.cost)}),{ch:'hbar',y:'cost',limit:12,asOf:true});
rep(49,4,'Stock Valuation (Cost · Landed · MRP)','Specific-serial costing, weighted per weave',x=>({cols:[T('k','Weave'),N('u','Units'),M('cost','Book cost'),M('land','Landed (+2% freight)'),M('mrp','MRP value'),M('pot','Potential margin'),Pc('pp','Margin %')],rows:G(x.ST,p=>p.it.weave?V.m.weave[p.it.weave].name:'Accessories',{u:a=>S(a,p=>p.qty),cost:a=>S(a,p=>p.cost*p.qty),land:a=>S(a,p=>p.cost*p.qty)*1.02,mrp:a=>S(a,p=>p.mrp*p.qty),pot:a=>S(a,p=>p.mrp*p.qty)/1.05-S(a,p=>p.cost*p.qty),pp:a=>V.pct(S(a,p=>p.mrp*p.qty)/1.05-S(a,p=>p.cost*p.qty),S(a,p=>p.mrp*p.qty)/1.05)}).sort((a,b)=>b.cost-a.cost)}),{y:'cost',asOf:true});
rep(50,4,V.basic?'Serial Number Register':'Serial / Batch Register','Every identifier ever issued',x=>({cols:[T('no',V.basic?'Serial no.':'Serial / Batch'),T('d','Design'),T('v','Vendor'),T('grn','GRN'),D('since','Inwarded'),T('loc','Location'),N('qty','Qty'),M('mrp','MRP'),B('st','Status')],rows:V.db.pieces.filter(p=>x.lk(p.loc)).map(p=>({no:p.no,d:V.m.item[p.sku].name,v:V.m.vendor[p.vendor]?V.m.vendor[p.vendor].name:'—',grn:p.grn,since:p.since,loc:V.m.loc[p.loc].city,qty:p.qty,mrp:p.mrp,st:(V.ST[p.status]||[p.status])[0]})).reverse()}),{ch:'none',asOf:true});
rep(51,4,'Serial Life-cycle Trace — Days to Sell','From GRN to sale, per piece (open Serial Trace for full timeline)',x=>({cols:[T('no','Serial'),T('d','Design'),D('grn','GRN date'),D('sold','Sold on'),N('days','Days to sell',{nosum:true}),N('mv','Movements',{nosum:true}),T('loc','Sold at')],rows:V.db.pieces.filter(p=>p.status==='sold'&&p.soldOn&&x.ok(p.soldOn)).map(p=>({no:p.no,d:V.m.item[p.sku].name,grn:p.since,sold:p.soldOn,days:V.diff(p.soldOn,p.since),mv:V.db.moves.filter(m=>m.u===p.u).length,loc:V.m.loc[p.loc].city})).sort((a,b)=>b.days-a.days)}),{ch:'none',nosum:true});
rep(52,4,'Stock Ledger — Movement Report','Every stock movement in the period',x=>({cols:[D('date','Date'),T('time','Time'),T('type','Movement'),T('no','Serial'),T('from','From'),T('to','To'),T('ref','Reference'),T('by','By')],rows:V.db.moves.filter(m=>x.ok(m.date)).map(m=>({date:m.date,time:m.time,type:(V.MV[m.type]||[m.type])[0],no:m.no,from:V.m.loc[m.from]?V.m.loc[m.from].city:m.from,to:V.m.loc[m.to]?V.m.loc[m.to].city:m.to,ref:m.ref,by:V.L.userName(m.by)})).reverse().slice(0,1500)}),{ch:'none'});
rep(53,4,'Stock Ageing','Cost value by age bucket',x=>({cols:[T('k','Age bucket'),N('u','Units'),M('cost','Cost value'),M('mrp','MRP value'),Pc('sh','% of stock')],rows:AG.map(b=>{const a=x.ST.filter(p=>p.age>=b[1]&&p.age<=b[2]);return {k:b[0],u:S(a,p=>p.qty),cost:S(a,p=>p.cost*p.qty),mrp:S(a,p=>p.mrp*p.qty),sh:V.pct(S(a,p=>p.cost*p.qty),S(x.ST,p=>p.cost*p.qty))}})}),{y:'cost',asOf:true});
rep(54,4,'Dead Stock & Markdown Candidates','Aged pieces with suggested markdown',x=>({cols:[T('no','Serial'),T('d','Design'),T('loc','Location'),N('age','Age (days)'),M('mrp','MRP'),M('cost','Cost'),Pc('md','Suggested markdown %'),M('np','Suggested price'),Pc('gm','Margin after %')],rows:x.ST.filter(p=>p.age>150&&p.trk==='serial').map(p=>{const md=p.age>365?15:p.age>240?12:8,np=Math.round(p.mrp*(1-md/100)/500)*500;return {no:p.no,d:p.it.name,loc:V.m.loc[p.loc].city,age:p.age,mrp:p.mrp,cost:p.cost,md,np,gm:V.pct(np/1.05-p.cost,np/1.05)}}).sort((a,b)=>b.age-a.age)}),{ch:'none',nosum:true,asOf:true});
rep(55,4,'Stock Turnover & Days of Inventory','How fast money in stock rotates',x=>{const days=Math.max(1,V.diff(x.ctxTo||V.db.today,V.rctx().from)+1)||1,cogs=S(x.L,l=>l.cost);return {cols:[T('k','Weave'),M('cogs','COGS (period)'),M('inv','Closing inventory (cost)'),T('turn','Turns (annualised)',{nosum:true}),N('dio','Days of inventory',{nosum:true})],rows:G(x.ST,p=>p.it.weave?V.m.weave[p.it.weave].name:'Accessories',{cogs:a=>S(x.L.filter(l=>l.weave===(a[0].it.weave?V.m.weave[a[0].it.weave].name:'Accessories')),l=>l.cost),inv:a=>S(a,p=>p.cost*p.qty)}).map(r=>{const t=r.inv?r.cogs/r.inv*(365/Math.max(30,V.diff(V.db.today,V.rctx().from))):0;return {...r,turn:t.toFixed(2),dio:t?Math.round(365/t):999}}).sort((a,b)=>b.cogs-a.cogs)}},{y:'cogs',asOf:true});
rep(56,4,'GMROI — Gross Margin Return on Inventory','Margin earned per ₹ invested in stock',x=>({cols:[T('k','Weave'),M('gm','Gross margin (period)'),M('inv','Inventory (cost)'),T('g','GMROI',{nosum:true})],rows:G(x.ST,p=>p.it.weave?V.m.weave[p.it.weave].name:'Accessories',{gm:a=>S(x.L.filter(l=>l.weave===(a[0].it.weave?V.m.weave[a[0].it.weave].name:'Accessories')),l=>l.margin),inv:a=>S(a,p=>p.cost*p.qty)}).map(r=>({...r,g:r.inv?(r.gm/r.inv).toFixed(2):'—'})).sort((a,b)=>b.gm-a.gm)}),{y:'gm',asOf:true});
rep(57,4,'ABC / XYZ Analysis','Revenue importance (ABC) × demand stability (XYZ)',x=>{const m=ym(),rs=G(x.L.filter(l=>l.cat==='Saree'),l=>l.design,{net:a=>S(a,r=>r.net),u:a=>S(a,r=>r.qty),by:a=>m.map(k=>S(a.filter(r=>r.month===k),r=>r.qty))}).sort((a,b)=>b.net-a.net),T0=S(rs,r=>r.net)||1;let c=0;return {cols:[T('k','Design'),M('net','Net sales'),N('u','Units'),Pc('cum','Cumulative %'),T('abc','ABC'),T('xyz','XYZ'),T('cls','Class')],rows:rs.map(r=>{c+=r.net;const mean=S(r.by)/r.by.length||1,sd=Math.sqrt(S(r.by,v=>(v-mean)**2)/r.by.length),cv=sd/mean,abc=c/T0<=.8?'A':c/T0<=.95?'B':'C',xyz=cv<.6?'X':cv<1.1?'Y':'Z';return {...r,cum:c/T0*100,abc,xyz,cls:abc+xyz}})}},{y:'net',limit:12});
rep(58,4,'Reorder & Low-stock Report','Weaves running below the safety level',x=>({cols:[T('k','Weave'),N('u','In stock'),N('v90','Sold last 90 d'),N('min','Min level',{nosum:true}),N('sug','Suggested PO qty'),T('vendor','Preferred vendor'),B('st','Status')],rows:V.WEAVES.map(w=>{const u=S(V.db.pieces.filter(p=>p.status==='in_stock'&&V.m.item[p.sku].weave===w.code&&(x.lk(p.loc)||x.loc==='ALL')),p=>p.qty),v90=S(V.db.invoices.filter(i=>V.diff(V.db.today,i.date)<90).flatMap(i=>i.lines).filter(l=>V.m.item[l.sku].weave===w.code),l=>l.qty),mn=Math.max(4,Math.round(v90/90*30)),v=V.db.vendors.find(y=>y.weave===w.code);return {k:w.name,u,v90,min:mn,sug:Math.max(0,mn*2-u),vendor:v?v.name:'—',st:u<mn?'Reorder':u<mn*1.5?'Watch':'OK'}}).sort((a,b)=>b.sug-a.sug)}),{y:'u',asOf:true,sumSkip:['min']});
rep(59,4,'Stock by Price Band','Distribution of the shelf by ticket size',x=>({cols:[T('k','Price band'),N('u','Units'),M('cost','Cost'),M('mrp','MRP value'),Pc('sh','% of units')],rows:BANDS.map(b=>{const a=x.ST.filter(p=>band(p.mrp)===b);return {k:b,u:S(a,p=>p.qty),cost:S(a,p=>p.cost*p.qty),mrp:S(a,p=>p.mrp*p.qty),sh:V.pct(S(a,p=>p.qty),S(x.ST,p=>p.qty))}})}),{ch:'donut',y:'u',asOf:true});
rep(60,4,'Reserved · Held · Trial Stock','Pieces unavailable for walk-in sale',x=>({cols:[T('no','Serial'),T('d','Design'),B('st','Held as'),T('cust','Customer'),M('mrp','MRP'),N('days','Days held',{nosum:true})],rows:V.db.pieces.filter(p=>['hold','trial','booked'].includes(p.status)).map(p=>{const doc=[...V.db.holds,...V.db.trials,...V.db.bookings].find(h=>h.u===p.u&&['Active','Out','Open'].includes(h.status));return {no:p.no,d:V.m.item[p.sku].name,st:p.status==='hold'?'Hold':p.status==='trial'?'On trial':'Booked',cust:p.holdFor?V.m.cust[p.holdFor].name:'—',mrp:p.mrp,days:doc?V.diff(V.db.today,doc.date):0}})}),{ch:'none',asOf:true});
rep(61,4,'Damaged & Quarantine Stock','Pieces not fit for sale',x=>({cols:[T('no','Serial'),T('d','Design'),T('loc','Location'),B('st','Status'),M('cost','Cost'),M('mrp','MRP')],rows:V.db.pieces.filter(p=>['damaged','missing','quarantine','vendor_return'].includes(p.status)).map(p=>({no:p.no,d:V.m.item[p.sku].name,loc:V.m.loc[p.loc].city,st:V.ST[p.status][0],cost:p.cost,mrp:p.mrp}))}),{ch:'none',asOf:true});
rep(62,4,'Stock Adjustment Register','Write-offs, repricing and corrections',x=>({cols:[T('no','No'),D('date','Date'),T('type','Type'),T('s','Serial'),T('reason','Reason'),M('v','Value'),T('by','Raised by'),B('st','Status')],rows:V.db.adjustments.filter(a=>x.ok(a.date)).map(a=>({no:a.no,date:a.date,type:a.type,s:V.m.piece[a.u].no,reason:a.reason,v:a.old?a.old-a.new:V.m.piece[a.u].cost,by:V.L.userName(a.by),st:a.status}))}),{ch:'none'});
rep(63,4,'Physical Audit Variance Report','Count vs system by audit',x=>({cols:[T('no','Audit'),D('date','Date'),T('loc','Location'),N('sys','System'),N('cnt','Counted'),N('var','Variance'),T('by','By'),T('n','Notes')],rows:V.db.audits.map(a=>({no:a.no,date:a.date,loc:V.m.loc[a.loc].name,sys:a.system,cnt:a.counted,var:a.variance,by:V.L.userName(a.by),n:a.notes}))}),{x:'no',y:'var',asOf:true});
rep(64,4,'Missing & Unaccounted Serials','Serials flagged missing at audit or exhibition reconciliation',x=>({cols:[T('no','Serial'),T('d','Design'),T('src','Source'),D('date','Flagged'),M('cost','Cost value'),T('note','Note')],rows:V.db.moves.filter(m=>['EXH_MISSING','AUDIT'].includes(m.type)).map(m=>{const p=V.m.piece[m.u];return {no:m.no,d:V.m.item[p.sku].name,src:m.type==='EXH_MISSING'?'Exhibition reconciliation':'Stock audit',date:m.date,cost:p.cost,note:m.note}})}),{ch:'none',asOf:true});
rep(65,4,'Unsold Since GRN','In-stock serials by days on shelf',x=>({cols:[T('no','Serial'),T('d','Design'),T('loc','Location'),D('since','GRN date'),N('age','Days on shelf'),M('cost','Cost'),M('mrp','MRP')],rows:x.ST.filter(p=>p.trk==='serial').map(p=>({no:p.no,d:p.it.name,loc:V.m.loc[p.loc].city,since:p.since,age:p.age,cost:p.cost,mrp:p.mrp})).sort((a,b)=>b.age-a.age)}),{ch:'none',nosum:true,asOf:true});
rep(66,4,'Stock Transfer Register','All inter-location transfers',x=>({cols:[T('no','Transfer'),D('date','Date'),T('from','From'),T('to','To'),T('exh','Exhibition'),N('u','Units'),M('val','Value (MRP)'),...(V.basic?[]:[T('ewb','E-way bill')]),B('st','Status')],rows:V.db.transfers.filter(t=>x.ok(t.date)).map(t=>({no:t.no,date:t.date,from:V.m.loc[t.from].city,to:V.m.loc[t.to].city,exh:t.exh||'—',u:S(t.lines,l=>l.qty),val:t.value,ewb:t.ewb||'—',st:t.status})).reverse()}),{ch:'none'});
rep(67,4,'In-transit Stock Ageing','Dispatched but not yet received',x=>({cols:[T('no','Transfer'),T('route','Route'),D('d','Dispatched'),N('days','Days in transit'),N('u','Units'),M('val','Value')],rows:V.db.transfers.filter(t=>t.status==='In-Transit').map(t=>({no:t.no,route:V.m.loc[t.from].city+' → '+V.m.loc[t.to].city,d:t.dispatchedOn,days:V.diff(V.db.today,t.dispatchedOn),u:S(t.lines,l=>l.qty),val:t.value}))}),{ch:'none',asOf:true});
rep(68,4,'Label Print Log','Tag runs per GRN',x=>({cols:[D('date','Date'),T('grn','GRN'),N('count','Tags'),T('type','Type'),T('by','By')],rows:V.db.labels.filter(l=>x.ok(l.date)).map(l=>({date:l.date,grn:l.grn,count:l.count,type:l.type,by:V.L.userName(l.by)})).reverse()}),{ch:'none'});

// ================= FAMILY 5 — Exhibitions =================
const EX=()=>V.db.exhibitions;
const EXS=()=>EX().filter(e=>e.status!=='Planned').map(e=>({e,s:V.L.exhStats(e.code)}));
rep(69,5,'Exhibition Master Register','Unique code, venue, dates and status',x=>({cols:[T('code','Code'),T('n','Name'),T('city','City'),T('st','State'),D('s','Start'),D('e','End'),T('inc','In-charge'),M('stall','Stall cost'),M('target','Target'),B('status','Status')],rows:EX().map(e=>({code:e.code,n:e.name,city:e.city,st:e.state,s:e.start,e:e.end,inc:V.L.userName(e.incharge),stall:e.stall,target:e.target,status:e.status}))}),{ch:'none',asOf:true});
rep(70,5,'Exhibition Stock Dispatch Sheet','Pieces sent to each exhibition',x=>({cols:[T('exh','Exhibition'),T('no','Transfer'),T('s','Serial'),T('d','Design'),M('mrp','MRP'),T('ewb','E-way bill')],rows:V.db.transfers.filter(t=>t.exh&&t.to.startsWith('P-')).flatMap(t=>t.lines.map(l=>{const p=V.m.piece[l.u];return {exh:t.exh,no:t.no,s:p.no,d:V.m.item[p.sku].name,mrp:p.mrp,ewb:t.ewb||'—'}}))}),{ch:'none',asOf:true});
rep(71,5,'Exhibition Day-wise Sales','Daily sales by exhibition',x=>({cols:[T('exh','Exhibition'),D('date','Date'),N('bills','Bills'),N('pcs','Pieces'),M('net','Net sales'),M('cash','Cash'),M('dig','Digital')],rows:G(V.db.invoices.filter(i=>V.m.loc[i.loc].type==='Exhibition'),i=>V.m.loc[i.loc].exh+'|'+i.date,{bills:a=>a.length,pcs:a=>S(a,i=>S(i.lines,l=>l.qty)),net:a=>S(a,i=>i.net),cash:a=>S(a,V.L.cashNet),dig:a=>S(a,i=>i.net)-S(a,V.L.cashNet)}).map(r=>({exh:r.k.split('|')[0],date:r.k.split('|')[1],...r})).sort((a,b)=>a.exh+a.date<b.exh+b.date?-1:1)}),{x:'date',y:'net',ch:'bar'});
rep(72,5,'Exhibition P&L','Sales less COGS, stall and petty costs',x=>({cols:[T('code','Exhibition'),M('sales','Net sales'),M('cogs','COGS'),M('stall','Stall cost'),M('petty','Petty expenses'),M('profit','Net profit'),Pc('mp','Margin %')],rows:EXS().map(({e,s})=>{const petty=s.exp-e.stall;return {code:e.code+' · '+e.city,sales:s.sales,cogs:s.cogs,stall:e.stall,petty,profit:s.profit,mp:V.pct(s.profit,s.sales)}})}),{y:'profit'});
rep(73,5,'Exhibition Reconciliation Report','Opening = Sold + Returned + Damaged + Missing',x=>({cols:[T('code','Exhibition'),N('open','Opening'),N('sold','Sold'),N('ret','Returned to Main'),N('dmg','Damaged'),N('mis','Missing'),B('ok','Check'),D('date','Reconciled on')],rows:V.db.recons.map(r=>({code:r.exh,open:r.opening,sold:r.sold,ret:r.returned,dmg:r.damaged,mis:r.missing,ok:r.opening===r.sold+r.returned+r.damaged+r.missing?'Reconciled':'Variance',date:r.date}))}),{x:'code',y:'sold',stack:['sold','ret','dmg','mis']});
rep(74,5,'Exhibition ROI & Comparison','Return on exhibition spend, city and year',x=>({cols:[T('code','Exhibition'),T('city','City'),M('sales','Net sales'),M('cost','Total cost (COGS + expenses)'),M('profit','Profit'),Pc('roi','ROI %'),M('perday','Sales / day',{nosum:true})],rows:EXS().map(({e,s})=>({code:e.code,city:e.city,sales:s.sales,cost:s.cogs+s.exp,profit:s.profit,roi:V.pct(s.profit,s.cogs+s.exp),perday:s.sales/Math.max(1,V.diff(e.end,e.start)+1)}))}),{x:'city',y:'roi'});
rep(75,5,'Sell-through % by Exhibition','How much of the dispatched stock was sold',x=>({cols:[T('code','Exhibition'),N('open','Dispatched'),N('sold','Sold'),N('bal','Balance'),Pc('sell','Sell-through %')],rows:EXS().map(({e,s})=>({code:e.city,open:s.opening,sold:s.sold,bal:s.balance,sell:s.sell}))}),{y:'sell'});
rep(76,5,'Customer Acquisition per Exhibition','New customers won at each exhibition',x=>({cols:[T('code','Exhibition'),N('cust','Customers billed'),N('new','New to the brand'),Pc('np','New %'),M('arpc','Avg spend / customer',{nosum:true})],rows:EXS().map(({e,s})=>{const inv=V.db.invoices.filter(i=>i.loc===e.plant&&i.cust),cs=V.uniq(inv.map(i=>i.cust)),nw=cs.filter(c=>V.m.cust[c].since>=V.addDays(e.start,-3)).length;return {code:e.city,cust:cs.length,new:nw,np:V.pct(nw,cs.length),arpc:S(inv,i=>i.net)/(cs.length||1)}})}),{y:'new'});
rep(77,5,'Exhibition Expense Summary','Spend by head across exhibitions',x=>{const rows=[];EX().filter(e=>e.status!=='Planned').forEach(e=>{rows.push({exh:e.city,head:'Stall rental',amt:e.stall});V.db.petty.filter(p=>p.loc===e.plant&&p.type==='expense').forEach(p=>rows.push({exh:e.city,head:p.head,amt:p.amt}))});return {cols:[T('exh','Exhibition'),T('head','Head'),M('amt','Amount')],rows:G(rows,r=>r.exh+'|'+r.head,{amt:a=>S(a,r=>r.amt)}).map(r=>({exh:r.k.split('|')[0],head:r.k.split('|')[1],amt:r.amt})).sort((a,b)=>b.amt-a.amt)}},{ch:'bar',x:'head',y:'amt'});
rep(78,5,'Return-to-Main Stock Sheet','Balance stock brought back after exhibitions',x=>({cols:[T('exh','Exhibition'),T('no','Transfer'),D('date','Date'),T('s','Serial'),T('d','Design'),M('mrp','MRP')],rows:V.db.transfers.filter(t=>t.exh&&t.to==='MAIN').flatMap(t=>t.lines.map(l=>{const p=V.m.piece[l.u];return {exh:t.exh,no:t.no,date:t.date,s:p.no,d:V.m.item[p.sku].name,mrp:p.mrp}}))}),{ch:'none'});
rep(79,5,'Best Weaves by City · Exhibition','Which weaves each city loves',x=>({cols:[T('city','City'),T('w','Weave'),N('pcs','Pieces'),M('net','Net sales'),Pc('sh','Share in city %')],rows:(()=>{const L=V.db.invoices.filter(i=>V.m.loc[i.loc].type==='Exhibition').flatMap(i=>i.lines.filter(l=>V.m.item[l.sku].cat==='Saree').map(l=>({city:V.m.loc[i.loc].city,w:V.m.weave[V.m.item[l.sku].weave].name,q:l.qty,n:l.net}))),tc={};L.forEach(r=>tc[r.city]=(tc[r.city]||0)+r.n);return G(L,r=>r.city+'|'+r.w,{pcs:a=>S(a,r=>r.q),net:a=>S(a,r=>r.n)}).map(r=>{const [c,w]=r.k.split('|');return {city:c,w,pcs:r.pcs,net:r.net,sh:r.net/tc[c]*100}}).sort((a,b)=>a.city===b.city?b.net-a.net:a.city<b.city?-1:1)})()}),{x:'w',y:'net',ch:'hbar',limit:12});

// ================= FAMILY 6 — POS & Cash =================
const DR=x=>V.db.drawers.filter(r=>x.ok(r.date)&&x.lk(r.loc));
rep(80,6,'Day-End (Z) Report','Closed days with cash reconciliation',x=>({cols:[D('date','Date'),T('loc','Location'),N('bills','Bills'),M('sales','Gross sales'),M('cash','Cash sales'),M('exp','Expected cash'),M('cnt','Counted'),M('var','Variance'),M('dep','Deposited')],rows:DR(x).filter(r=>r.closing).map(r=>{const c=V.L.drawerCalc(r),iv=V.db.invoices.filter(i=>i.loc===r.loc&&i.date===r.date);return {date:r.date,loc:V.m.loc[r.loc].city,bills:iv.length,sales:S(iv,i=>i.net),cash:c.sales,exp:r.closing.expected,cnt:r.closing.counted,var:r.closing.variance,dep:r.closing.deposit}}).reverse()}),{ch:'none'});
rep(81,6,'Cash Drawer Movement Register','Every cash-in, cash-out and safe drop',x=>({cols:[D('date','Date'),T('time','Time'),T('loc','Location'),T('type','Entry'),T('reason','Reason'),T('by','By'),M('amt','Amount')],rows:DR(x).flatMap(r=>r.entries.map(e=>({date:r.date,time:e.time,loc:V.m.loc[r.loc].city,type:e.t==='in'?'Cash in':e.t==='out'?'Cash out':'Safe drop',reason:e.reason,by:V.L.userName(e.by),amt:e.amt}))).reverse()}),{ch:'none'});
rep(82,6,'Cash Variance by Cashier','Short / excess per cashier',x=>({cols:[T('k','Cashier'),N('days','Days closed'),N('off','Days with variance'),M('short','Total short'),M('excess','Total excess'),M('net','Net variance')],rows:G(DR(x).filter(r=>r.closing),r=>V.L.userName(r.openedBy),{days:a=>a.length,off:a=>a.filter(r=>r.closing.variance).length,short:a=>S(a.filter(r=>r.closing.variance<0),r=>-r.closing.variance),excess:a=>S(a.filter(r=>r.closing.variance>0),r=>r.closing.variance),net:a=>S(a,r=>r.closing.variance)})}),{y:'off'});
rep(83,6,'Denomination-wise Cash Count','Notes and coins counted across day-ends',x=>{const m={};DR(x).filter(r=>r.closing).forEach(r=>V.DENOM.forEach(k=>m[k]=(m[k]||0)+(+(r.closing.denom||{})[k]||0)));return {cols:[T('k','Denomination'),N('n','Pieces counted'),M('v','Value')],rows:V.DENOM.map(k=>({k:'₹'+k,n:m[k]||0,v:(m[k]||0)*k}))}},{y:'v'});
rep(84,6,'Shift Summary','Morning vs evening shift per day',x=>({cols:[D('date','Date'),T('loc','Location'),N('am','Morning bills'),M('amn','Morning sales'),N('pm','Evening bills'),M('pmn','Evening sales')],rows:G(x.INV,i=>i.date+'|'+i.loc,{am:a=>a.filter(i=>+i.time.slice(0,2)<14).length,amn:a=>S(a.filter(i=>+i.time.slice(0,2)<14),i=>i.net),pm:a=>a.filter(i=>+i.time.slice(0,2)>=14).length,pmn:a=>S(a.filter(i=>+i.time.slice(0,2)>=14),i=>i.net)}).map(r=>({date:r.k.split('|')[0],loc:V.m.loc[r.k.split('|')[1]].city,...r})).sort((a,b)=>a.date<b.date?1:-1)}),{ch:'none'});
const PET=x=>V.db.petty.filter(p=>x.ok(p.date)&&x.lk(p.loc));
rep(85,6,'Petty Cash Register & Imprest Balance','Vouchers with running balance',x=>{let b=0;const rows=PET(x).slice().sort((a,c)=>a.date+a.id<c.date+c.id?-1:1).map(p=>{b+=p.type==='topup'?p.amt:-p.amt;return {id:p.id,date:p.date,loc:V.m.loc[p.loc].city,head:p.head,desc:p.desc,in:p.type==='topup'?p.amt:0,out:p.type==='expense'?p.amt:0,bal:b,ap:p.approvedBy?V.L.userName(p.approvedBy):'—'}});return {cols:[T('id','Voucher'),D('date','Date'),T('loc','Location'),T('head','Head'),T('desc','Description'),M('in','Top-up'),M('out','Expense'),M('bal','Balance',{nosum:true}),T('ap','Approved by')],rows:rows.reverse()}},{ch:'none'});
rep(86,6,'Expense Register by Head · Location · Exhibition','Where the petty money goes',x=>({cols:[T('head','Head'),T('loc','Location'),N('n','Vouchers'),M('amt','Amount')],rows:G(PET(x).filter(p=>p.type==='expense'),p=>p.head+'|'+V.m.loc[p.loc].city,{n:a=>a.length,amt:a=>S(a,p=>p.amt)}).map(r=>({head:r.k.split('|')[0],loc:r.k.split('|')[1],n:r.n,amt:r.amt})).sort((a,b)=>b.amt-a.amt)}),{x:'head',y:'amt',ch:'hbar',limit:12});
rep(87,6,'Cash Book & Bank Book (Daily)','Cash vs digital receipts per day',x=>({cols:[D('date','Date'),M('csales','Cash sales'),M('cin','Cash in'),M('cout','Cash out'),M('drop','Safe drops'),M('close','Cash closing (counted)'),M('bank','Bank / UPI / Card receipts')],rows:G(x.INV,i=>i.date,{csales:a=>S(a,V.L.cashNet),bank:a=>S(a,i=>i.net)-S(a,V.L.cashNet)}).map(r=>{const rs=DR(x).filter(d=>d.date===r.k),cc=rs.map(d=>V.L.drawerCalc(d));return {date:r.k,csales:r.csales,cin:S(cc,c=>c.cin),cout:S(cc,c=>c.cout),drop:S(cc,c=>c.drop),close:S(rs.filter(d=>d.closing),d=>d.closing.counted),bank:r.bank}}).sort((a,b)=>a.date<b.date?1:-1)}),{ch:'line',x:'date',y:'bank'});
rep(88,6,'Payment-mode Reconciliation (Settlements)','System receipts vs expected gateway settlement',x=>{const MD={UPI:0,Card:.018,'Bank Transfer':0,EMI:.025,Cheque:0},ST={UPI:1,Card:2,'Bank Transfer':0,EMI:3,Cheque:2};return {cols:[D('date','Sale date'),T('mode','Mode'),M('sys','System amount'),M('mdr','MDR / fees'),M('net','Net settlement'),D('due','Settles on'),B('st','Status')],rows:G(x.INV.flatMap(i=>i.pays.filter(p=>MD[p.mode]!==undefined).map(p=>({d:i.date,m:p.mode,a:p.amt}))),r=>r.d+'|'+r.m,{sys:a=>S(a,r=>r.a)}).map(r=>{const [d,m]=r.k.split('|'),fee=r.sys*MD[m],due=V.addDays(d,ST[m]);return {date:d,mode:m,sys:r.sys,mdr:fee,net:r.sys-fee,due,st:due<=V.db.today?'Settled':'Pending'}}).sort((a,b)=>a.date<b.date?1:-1).slice(0,400)}},{ch:'none'});
rep(89,6,'Safe-drop & Bank Deposit Register','Cash moved out of the drawer',x=>({cols:[D('date','Date'),T('time','Time'),T('loc','Location'),T('by','By'),M('amt','Amount'),T('reason','Reference')],rows:DR(x).flatMap(r=>r.entries.filter(e=>e.t==='drop').map(e=>({date:r.date,time:e.time,loc:V.m.loc[r.loc].city,by:V.L.userName(e.by),amt:e.amt,reason:e.reason}))).reverse()}),{ch:'none'});

// ================= FAMILY 7 — Customers =================
const CS=()=>V.db.customers.map(c=>{const inv=V.db.invoices.filter(i=>i.cust===c.id),last=inv.map(i=>i.date).sort().pop();return {c,inv,last,days:last?V.diff(V.db.today,last):9999,spend:S(inv,i=>i.net)}});
rep(90,7,'Customer Master & Segmentation','VIP, repeat, one-time and lapsed customers',x=>({cols:[T('name','Customer'),T('city','City'),T('tier','Tier'),N('bills','Bills'),M('spend','Lifetime spend'),D('last','Last purchase'),T('seg','Segment')],rows:CS().map(({c,inv,last,days,spend})=>({name:c.name,city:c.city,tier:c.tier,bills:inv.length,spend,last:last||'',seg:!inv.length?'Prospect':spend>=600000?'VIP':inv.length>=2?(days>120?'Lapsed repeat':'Repeat'):days>120?'Lapsed one-time':'One-time'})).sort((a,b)=>b.spend-a.spend)}),{ch:'donut-seg',asOf:true});
rep(91,7,'Customer Lifetime Value','Value ranking with average ticket and frequency',x=>({cols:[T('name','Customer'),N('bills','Bills'),M('spend','CLV (to date)'),M('avg','Avg ticket',{nosum:true}),N('span','Customer for (days)',{nosum:true}),M('pred','12-mo projection',{nosum:true})],rows:CS().filter(r=>r.inv.length).map(({c,inv,spend})=>{const span=Math.max(30,V.diff(V.db.today,c.since));return {name:c.name,bills:inv.length,spend,avg:spend/inv.length,span,pred:spend/span*365}}).sort((a,b)=>b.spend-a.spend)}),{ch:'hbar',x:'name',y:'spend',limit:12,asOf:true});
rep(92,7,'Repeat vs New Customers','Monthly mix of first-time and returning buyers',x=>{const seen=new Set(),m={};V.db.invoices.slice().sort((a,b)=>a.date<b.date?-1:1).forEach(i=>{if(!i.cust)return;const k=i.date.slice(0,7),o=m[k]||(m[k]={k,new:0,rep:0});seen.has(i.cust)?o.rep++:(o.new++,seen.add(i.cust))});return {cols:[T('m','Month'),N('new','New customers'),N('rep','Repeat bills'),Pc('rp','Repeat %')],rows:ym().map(k=>{const o=m[k]||{new:0,rep:0};return {m:V.ml(k),new:o.new,rep:o.rep,rp:V.pct(o.rep,o.new+o.rep)}})}},{x:'m',y:'new',stack:['new','rep'],asOf:true});
rep(93,7,'Birthday · Anniversary · Festival Outreach','Customers to greet in the next 30 days',x=>{const t=V.db.today,y=+t.slice(0,4),rows=[];const nxt=(s)=>{if(!s)return 999;const md=s.slice(5);let d=`${y}-${md}`;if(d<t)d=`${y+1}-${md}`;return V.diff(d,t)};V.db.customers.forEach(c=>{[['Birthday',c.dob],['Anniversary',c.anniv]].forEach(([k,s])=>{const n=nxt(s);if(n<=30)rows.push({name:c.name,ev:k,on:s?s.slice(8)+'/'+s.slice(5,7):'',in:n,phone:c.phone,tier:c.tier,pref:V.m.weave[c.prefs.weaves[0]].name})})});[['Diwali',V.addDays(t,23)],['Navaratri / Dasara',V.addDays(t,6)]].forEach(([n,d])=>rows.push({name:'All Rani & Maharani customers',ev:'Festival: '+n,on:V.fd(d),in:V.diff(d,t),phone:'Broadcast',tier:'Rani+',pref:'Seasonal collection'}));return {cols:[T('name','Customer'),T('ev','Occasion'),T('on','Date'),N('in','In (days)',{nosum:true}),T('phone','Mobile'),T('tier','Tier'),T('pref','Likes')],rows:rows.sort((a,b)=>a.in-b.in)}},{ch:'none',nosum:true,asOf:true});
rep(94,7,'Customer Preference Profile','Weave and budget preferences across the base',x=>{const m={};V.db.customers.forEach(c=>c.prefs.weaves.forEach(w=>{const o=m[w]||(m[w]={k:V.m.weave[w].name,n:0,lo:[],hi:[]});o.n++;o.lo.push(c.prefs.budget[0]);o.hi.push(c.prefs.budget[1])}));return {cols:[T('k','Preferred weave'),N('n','Customers'),M('lo','Avg budget (low)',{nosum:true}),M('hi','Avg budget (high)',{nosum:true})],rows:Object.values(m).map(o=>({k:o.k,n:o.n,lo:S(o.lo)/o.lo.length,hi:S(o.hi)/o.hi.length})).sort((a,b)=>b.n-a.n)}},{y:'n',asOf:true});
rep(95,7,'Loyalty Points Ledger','Points earned, redeemed and balance',x=>({cols:[T('name','Customer'),T('tier','Tier'),N('earn','Points earned'),N('red','Redeemed'),N('bal','Balance'),M('val','Value @ ₹0.25/pt',{nosum:true})],rows:CS().filter(r=>r.spend).map(({c,spend})=>({name:c.name,tier:c.tier,earn:Math.floor(spend/100),red:0,bal:Math.floor(spend/100),val:Math.floor(spend/100)*.25})).sort((a,b)=>b.earn-a.earn)}),{ch:'hbar',x:'name',y:'earn',limit:12,asOf:true});
rep(96,7,'Customer Ageing','Time since last purchase',x=>({cols:[T('k','Bucket'),N('n','Customers'),M('spend','Lifetime spend'),Pc('sh','% of base')],rows:[['0–30 days',0,30],['31–90 days',31,90],['91–180 days',91,180],['180+ days',181,9000],['Never purchased',9999,9999]].map(b=>{const a=CS().filter(r=>r.days>=b[1]&&r.days<=b[2]);return {k:b[0],n:a.length,spend:S(a,r=>r.spend),sh:V.pct(a.length,V.db.customers.length)}})}),{ch:'donut',y:'n',asOf:true});
rep(97,7,'Wishlist & Enquiry vs Stock Match','Who is waiting for what — and what we can offer today',x=>({cols:[T('cust','Customer'),T('w','Looking for'),T('col','Colour'),M('bud','Budget'),D('date','Since'),N('m','Matching pieces in stock',{nosum:true}),T('best','Best match'),B('st','Action')],rows:V.db.wishlist.map(w=>{const ms=V.db.pieces.filter(p=>p.status==='in_stock'&&V.m.item[p.sku].weave===w.weave&&p.mrp<=w.budget*1.25),best=ms.find(p=>V.m.item[p.sku].colour===w.colour)||ms[0];return {cust:V.m.cust[w.cust].name,w:V.m.weave[w.weave].name,col:w.colour,bud:w.budget,date:w.date,m:ms.length,best:best?best.no+' · '+V.inr(best.mrp):'—',st:ms.length?'Call customer':'Source from vendor'}})}),{ch:'none',nosum:true,asOf:true});

// ================= FAMILY 8 — GST & Finance =================
rep(98,8,'GST Sales Register','Invoice-wise tax split',x=>({cols:[T('no','Invoice'),D('date','Date'),T('gstin','Seller GSTIN'),T('cust','Customer'),T('gst','Customer GSTIN'),M('tax','Taxable'),M('cgst','CGST'),M('sgst','SGST'),M('igst','IGST'),M('tot','Invoice value')],rows:x.INV.map(i=>({no:i.no,date:i.date,gstin:V.m.loc[i.loc].gstin,cust:i.cust?V.m.cust[i.cust].name:'Walk-in',gst:i.cust?V.m.cust[i.cust].gstin||'—':'—',tax:i.taxable,cgst:i.cgst,sgst:i.sgst,igst:i.igst,tot:i.net})).reverse()}),{ch:'none'});
rep(99,8,'HSN-wise Summary','GSTR-1 table 12',x=>({cols:[T('hsn','HSN'),Pc('rate','GST rate'),N('qty','Quantity'),M('tb','Taxable value'),M('tx','Tax amount'),M('tot','Invoice value')],rows:G(x.INV.flatMap(i=>i.lines),l=>l.hsn+'|'+l.gst,{qty:a=>S(a,l=>l.qty),tb:a=>S(a,l=>l.taxable),tx:a=>S(a,l=>l.tax),tot:a=>S(a,l=>l.net)}).map(r=>({hsn:r.k.split('|')[0],rate:+r.k.split('|')[1],qty:r.qty,tb:r.tb,tx:r.tx,tot:r.tot}))}),{x:'hsn',y:'tx'});
rep(100,8,'GSTR-1 Ready Data','B2B / B2C split by GSTIN and place of supply',x=>({cols:[T('gstin','Seller GSTIN'),T('t','Supply type'),N('n','Invoices'),M('tb','Taxable'),M('cg','CGST'),M('sg','SGST'),M('ig','IGST')],rows:G(x.INV,i=>V.m.loc[i.loc].gstin+'|'+(i.cust&&V.m.cust[i.cust].gstin?'B2B (registered)':'B2C (small / large)'),{n:a=>a.length,tb:a=>S(a,i=>i.taxable),cg:a=>S(a,i=>i.cgst),sg:a=>S(a,i=>i.sgst),ig:a=>S(a,i=>i.igst)}).map(r=>({gstin:r.k.split('|')[0],t:r.k.split('|')[1],...r})).sort((a,b)=>a.gstin<b.gstin?-1:1)}),{ch:'none'});
rep(101,8,'Purchase GST & ITC Register','Input tax credit from GRNs and local purchases',x=>{const r=[];V.db.grns.filter(g=>x.ok(g.date)&&!g.opening).forEach(g=>{const v=V.m.vendor[g.vendor];r.push({doc:g.no,date:g.date,v:v.name,gst:v.gstin||'Unregistered (RCM)',tb:g.value,itc:v.gstin?g.value*.05:0,type:'GRN'})});V.db.localPurchases.filter(l=>x.ok(l.date)).forEach(l=>{const v=V.m.vendor[l.vendor];r.push({doc:l.no,date:l.date,v:v.name,gst:v.gstin,tb:l.amt-l.gst,itc:l.gst,type:'Local purchase'})});return {cols:[T('doc','Document'),T('type','Type'),D('date','Date'),T('v','Vendor'),T('gst','Vendor GSTIN'),M('tb','Taxable value'),M('itc','ITC eligible')],rows:r.sort((a,b)=>a.date<b.date?1:-1)}},{ch:'none'});
rep(102,8,'E-way Bill Register','Inter-state stock movement documents',x=>({cols:[T('ewb','E-way bill'),T('no','Transfer'),D('date','Date'),T('route','Route'),M('val','Value'),T('exh','Exhibition'),B('st','Status')],rows:V.db.transfers.filter(t=>t.ewb&&x.ok(t.date)).map(t=>({ewb:t.ewb,no:t.no,date:t.date,route:V.m.loc[t.from].state+' → '+V.m.loc[t.to].state,val:t.value,exh:t.exh,st:t.status}))}),{ch:'none'});
rep(103,8,'Input vs Output Tax Summary','Monthly net GST position',x=>{const m=ym();return {cols:[T('m','Month'),M('out','Output GST'),M('inp','Input GST (ITC)'),M('net','Net payable')],rows:m.map(k=>{const out=S(V.db.invoices.filter(i=>i.date.startsWith(k)),i=>i.net-i.taxable),inp=S(V.db.grns.filter(g=>g.date.startsWith(k)&&!g.opening&&V.m.vendor[g.vendor].gstin),g=>g.value*.05)+S(V.db.localPurchases.filter(l=>l.date.startsWith(k)),l=>l.gst);return {m:V.ml(k),out,inp,net:out-inp}})}},{x:'m',y:'out',stack:null});
rep(104,8,'Daily Sales Journal (Accounting / Shopify export)','Double-entry journal per day',x=>({cols:[D('date','Date'),T('acc','Account'),M('dr','Debit'),M('cr','Credit')],rows:G(x.INV,i=>i.date,{cash:a=>S(a,V.L.cashNet),dig:a=>S(a,i=>i.net)-S(a,V.L.cashNet),tx:a=>S(a,i=>i.net-i.taxable),tb:a=>S(a,i=>i.taxable)}).sort((a,b)=>a.k<b.k?1:-1).slice(0,60).flatMap(r=>[{date:r.k,acc:'Cash in hand',dr:r.cash,cr:0},{date:r.k,acc:'Bank / UPI / Card clearing',dr:r.dig,cr:0},{date:r.k,acc:'Sales — Handloom Sarees',dr:0,cr:r.tb},{date:r.k,acc:'GST Output (CGST+SGST+IGST)',dr:0,cr:r.tx}])}),{ch:'none'});
rep(105,8,'Receivables & Payables Ageing','Money owed to us and by us',x=>{const t=V.db.today,r=[];V.db.bookings.filter(b=>b.status==='Open').forEach(b=>{const a=V.diff(t,b.date);r.push({side:'Receivable',party:V.m.cust[b.cust].name,doc:b.no,amt:V.m.piece[b.u].mrp-b.advance,age:a,bk:a<=30?'0–30':a<=60?'31–60':'60+'})});V.db.vendors.forEach(v=>{const b=V.vendorBal(v.id);if(b>0)r.push({side:'Payable',party:v.name,doc:'Open GRNs',amt:b,age:0,bk:'—'})});return {cols:[T('side','Type'),T('party','Party'),T('doc','Reference'),M('amt','Amount'),N('age','Age (days)',{nosum:true}),T('bk','Bucket')],rows:r}},{x:'party',y:'amt',asOf:true});

// ================= FAMILY 9 — Shopify =================
rep(106,9,'Sync Status Dashboard','Record counts by type and status',x=>({cols:[T('k','Type'),N('syn','Synced'),N('pen','Pending'),N('fail','Failed'),Pc('ok','Success %')],rows:G(V.db.sync,s=>s.type,{syn:a=>a.filter(s=>s.status==='Synced').length,pen:a=>a.filter(s=>s.status==='Pending').length,fail:a=>a.filter(s=>s.status==='Failed').length,ok:a=>V.pct(a.filter(s=>s.status==='Synced').length,a.length)})}),{y:'syn',stack:['syn','pen','fail'],asOf:true});
rep(107,9,'Order Sync Log','Order push history',x=>({cols:[T('id','ID'),T('t','Created'),T('ref','Invoice'),T('loc','Location'),M('amt','Amount'),T('sr','Shopify order'),B('st','Status'),T('err','Error')],rows:V.db.sync.filter(s=>s.type==='Order'&&x.ok(s.t.slice(0,10))&&x.lk(s.loc)).map(s=>({id:s.id,t:s.t,ref:s.ref,loc:V.m.loc[s.loc].city,amt:s.amt,sr:s.shopifyRef||'—',st:s.status,err:s.err})).reverse()}),{ch:'none'});
rep(108,9,'Inventory Sync Log','Stock level pushes to Shopify locations',x=>({cols:[T('id','ID'),T('t','Time'),T('ref','Snapshot'),T('loc','Location'),N('u','Units pushed'),B('st','Status')],rows:V.db.sync.filter(s=>s.type==='Inventory').map(s=>({id:s.id,t:s.t,ref:s.ref,loc:V.m.loc[s.loc].city,u:s.amt,st:s.status})).reverse()}),{ch:'none'});
rep(109,9,'App vs Shopify Sales Reconciliation','Daily sales in app vs sales that reached Shopify',x=>({cols:[D('date','Date'),M('app','App net sales'),M('shop','In Shopify'),M('diff','Difference'),N('open','Open records'),B('st','Status')],rows:G(x.INV,i=>i.date,{app:a=>S(a,i=>i.net),shop:a=>S(a.filter(i=>i.sync==='Synced'),i=>i.net),open:a=>a.filter(i=>i.sync!=='Synced').length}).map(r=>({date:r.k,app:r.app,shop:r.shop,diff:r.app-r.shop,open:r.open,st:r.open?'Differences':'Matched'})).sort((a,b)=>a.date<b.date?1:-1).slice(0,120)}),{ch:'line',x:'date',y:'diff'});
rep(110,9,'Customer Sync & Duplicate Match','Customer push status and duplicate detection',x=>({cols:[T('name','Customer'),T('phone','Mobile'),T('email','Email'),B('st','Shopify status'),B('dup','Duplicate check')],rows:V.db.customers.map(c=>{const s=V.db.sync.find(y=>y.type==='Customer'&&y.ref===c.id),d=V.db.customers.filter(o=>o.id!==c.id&&(o.phone===c.phone||o.email===c.email)).length;return {name:c.name,phone:c.phone,email:c.email,st:s?s.status:'Pending',dup:d?'Possible duplicate':'Unique'}})}),{ch:'none',nosum:true,asOf:true});
rep(111,9,'Unmapped SKU & Location Report','Master data blocking Shopify sync',x=>{const r=[];V.db.items.filter(i=>!i.shopify).forEach(i=>r.push({type:'Design',ref:i.sku,name:i.name,affected:V.db.sync.filter(s=>s.status==='Failed'&&s.err.includes(i.sku)).length,fix:'Create & map in Shopify tab'}));V.db.locations.filter(l=>!l.shopifyLoc&&l.status!=='Planned').forEach(l=>r.push({type:'Location',ref:l.id,name:l.name,affected:0,fix:'Map location'}));return {cols:[T('type','Type'),T('ref','Reference'),T('name','Name'),N('affected','Failed records'),T('fix','Fix')],rows:r}},{ch:'none',asOf:true});
rep(112,9,'Export File History','Files generated for manual upload to Shopify',x=>({cols:[T('t','When'),T('u','By'),T('kind','File type'),N('rows','Rows'),T('file','File name')],rows:V.db.exports.map(e=>({t:e.t,u:V.L.userName(e.user),kind:e.kind,rows:e.rows,file:e.file})).reverse()}),{ch:'none'});

// ================= FAMILY 10 — Audit & Control =================
rep(113,10,'User Activity / Audit Trail','Who did what, when',x=>({cols:[T('t','Timestamp'),T('u','User'),T('a','Action'),T('r','Reference')],rows:V.db.audit.filter(a=>x.ok(a.t.slice(0,10))).map(a=>({t:a.t,u:V.L.userName(a.user),a:a.act,r:a.ref})).reverse().slice(0,1500)}),{ch:'none'});
rep(114,10,'Price & Discount Override Log','Lines discounted above the cashier limit',x=>({cols:[T('no','Invoice'),D('date','Date'),T('cash','Cashier'),T('item','Item'),M('mrp','MRP'),M('disc','Discount'),Pc('pct','Discount %'),T('lim','Limit'),T('ap','Approved by')],rows:x.INV.flatMap(i=>i.lines.filter(l=>l.mrp&&l.disc/(l.mrp*l.qty)*100>V.m.user[i.cashier].disc).map(l=>({no:i.no,date:i.date,cash:V.L.userName(i.cashier),item:l.name,mrp:l.mrp,disc:l.disc,pct:l.disc/(l.mrp*l.qty)*100,lim:V.m.user[i.cashier].disc+'%',ap:'Manager (PIN)'}))).reverse()}),{ch:'none'});
rep(115,10,'Deleted / Voided Transactions','Integrity checks on transactional data',x=>({cols:[T('k','Check'),N('n','Exceptions',{nosum:true}),B('r','Result')],rows:[['Voided invoices',0],['Deleted GRNs',0],['Deleted stock moves',0],['Negative stock rows',V.db.pieces.filter(p=>p.qty<0).length],['Duplicate serial numbers',V.db.pieces.length-uq(V.db.pieces.map(p=>p.no))],['Day-ends re-opened',0]].map(r=>({k:r[0],n:r[1],r:r[1]?'Review':'Clean'}))}),{ch:'none',nosum:true});
rep(116,10,'Approval History','Decisions taken by approvers',x=>({cols:[T('id','ID'),D('date','Date'),T('type','Type'),T('ref','Reference'),T('by','Requested by'),M('amt','Amount'),B('st','Decision'),T('dec','Decided by')],rows:V.db.approvals.map(a=>({id:a.id,date:a.date,type:a.type,ref:a.ref,by:V.L.userName(a.by),amt:a.amt,st:a.status,dec:a.decidedBy?V.L.userName(a.decidedBy):'—'}))}),{ch:'none'});
rep(117,10,'Login & Session Report','Authentication events',x=>({cols:[T('t','Time'),T('u','User'),B('ev','Event'),T('ip','IP address'),T('dev','Device')],rows:V.db.sessions.map(s=>({t:s.t,u:V.L.userName(s.user),ev:s.ev==='Login'?'Active':'Failed',ip:s.ip,dev:s.dev}))}),{ch:'none'});

// Edition filter: Basic keeps only the essential reports
if(V.basic){for(let i=REP.length-1;i>=0;i--)if(!V.repAllowed(REP[i].n))REP.splice(i,1)}
REP.forEach((r,i)=>r.d=V.basic?i+1:r.n);
// ======================= Reports Hub UI =======================
const PRESETS=[['30','Last 30 days'],['90','Last 90 days'],['180','Last 6 months'],['mtd','Month to date'],['all','All data']];
V.run=(r)=>{const ctx=V.rctx();const x=Object.assign({ctxTo:ctx.to},V.rd(ctx));const o=r.fn(x);o.rows=o.rows||[];return o};
V.repChartCfg=(r,o)=>{const op=r.opts||{};if(op.ch==='none'||!o.rows.length)return null;let ch=op.ch||'bar';const x=op.x||o.cols[0].k,ys=op.stack===undefined?null:op.stack;
 const num=o.cols.filter(c=>c.fmt==='num'||c.fmt==='inr'||c.fmt==='pct'),y=op.y||(num[0]&&num[0].k);if(!y)return null;
 let rows=o.rows.slice(0,op.limit||(ch==='line'?400:ch==='donut'?8:20));if(ch==='donut-seg'){return {type:'doughnut',labels:uq(o.rows.map(r=>r.seg)).length?V.uniq(o.rows.map(r=>r.seg)):[],data:[{data:V.uniq(o.rows.map(r=>r.seg)).map(s=>o.rows.filter(r=>r.seg===s).length)}],fmt:V.num}}
 const col=o.cols.find(c=>c.k===y)||{},fmt=col.fmt==='inr'?V.short:col.fmt==='pct'?(v=>v.toFixed(0)+'%'):V.num;
 const labels=rows.map(r=>{const v=r[x];return col&&o.cols[0].fmt==='date'?V.fds(v):String(v)});
 if(ys){return {type:'bar',labels,stacked:true,data:ys.map((k,i)=>({label:(o.cols.find(c=>c.k===k)||{}).l||k,data:rows.map(r=>+r[k]||0),color:V.PAL[i]})),fmt:V.num}}
 if(ch==='donut')return {type:'doughnut',labels,data:[{data:rows.map(r=>+r[y]||0)}],tipFmt:fmt};
 return {type:ch==='line'?'line':'bar',horizontal:ch==='hbar',labels,data:[{label:col.l||y,data:rows.map(r=>+r[y]||0),color:V.PAL[Math.abs(r.n)%V.PAL.length]}],fmt,legend:false}};
V.repNum=o=>o.cols.filter(c=>(c.fmt==='num'||c.fmt==='inr')&&!c.nosum);
V.page('reports',{title:id=>id&&V.repById(id)?V.repById(id).title:'Reports Hub',crumb:'Insights',
render(id){const r=id&&V.repById(id);
 if(!r){const q=(V.S.rq||'').toLowerCase();
  return `<div class="hero" style="min-height:190px"><div class="txt"><div class="tag">${V.art.lotus(18,'#E3C57A')} Reports Hub</div><h1>${REP.length} reports. Every angle of your looms.</h1><p>Sales, stock, exhibitions, cash, GST, customers and Shopify — filter by period and location, drill into any table, export to Excel or print.</p><div class="search" style="max-width:420px;flex:none">${V.ic('search')}<input id="rq" placeholder="Search reports…" value="${V.esc(V.S.rq||'')}" aria-label="Search reports"></div></div><div class="art">${V.art.loom()}</div></div>
  <div class="g g3 mt">${FAM.map((f,i)=>{const rs=REP.filter(x=>x.fam===i&&(!q||(x.title+x.desc).toLowerCase().includes(q)));if(!rs.length)return '';return `<div class="card fam"><div class="fi" style="background:${f[2]}">${V.ic(f[1])}</div><span class="cnt">${rs.length}</span><h3>${f[0]}</h3><ul style="list-style:none;padding:0;margin:8px 0 0">${rs.map(x=>`<li><a href="#/reports/${x.id}" style="display:flex;gap:8px;padding:5px 0;text-decoration:none;color:var(--ink2)"><em style="font-style:normal;color:var(--mute);min-width:36px;font-size:12px">${x.d}</em><span>${x.title}</span></a></li>`).join('')}</ul></div>`}).join('')}</div>`}
 const f=V.S.rf=V.S.rf||{p:'180',loc:'ALL'};const o=V.run(r),nums=V.repNum(o).slice(0,4);
 const tot=c=>V.sum(o.rows,x=>+x[c.k]||0);
 return `<div class="rep-layout"><nav class="card rep-nav" aria-label="Report list"><a href="#/reports" style="font-weight:600;color:var(--ink)">‹ All reports</a>${FAM.map((fm,i)=>!REP.some(x=>x.fam===i)?'':`<h6>${fm[0]}</h6>${REP.filter(x=>x.fam===i).map(x=>`<a href="#/reports/${x.id}" class="${x.id===id?'on':''}"><em>${x.d}</em><span>${x.title}</span></a>`).join('')}`).join('')}</nav>
 <div><div class="head"><div><span class="badge gold">${FAM[r.fam][0]} · #${r.d}</span><h1 style="margin-top:6px">${r.title}</h1><p>${r.desc}${(r.opts||{}).asOf?` <span class="badge">As on ${V.fd(V.db.today)} — period filter not applicable</span>`:''}</p></div><div class="acts"><button class="btn" data-act="repX" data-t="csv">${V.ic('download')} CSV</button><button class="btn" data-act="repX" data-t="xlsx">${V.ic('file')} Excel</button><button class="btn" data-act="repX" data-t="print">${V.ic('print')} Print / PDF</button></div></div>
 <div class="card flat" style="margin-bottom:18px"><div class="row"><div class="seg" role="group" aria-label="Period">${PRESETS.map(p=>`<button class="${f.p===p[0]?'on':''}" data-act="repP" data-p="${p[0]}">${p[1]}</button>`).join('')}</div><label class="locsel">${V.ic('pin')}<select data-st="rf.loc" data-re="1" aria-label="Location filter"><option value="ALL">All locations</option>${V.opts(V.db.locations,f.loc,{v:l=>l.id,l:l=>l.name})}</select></label><span class="sm mute">${o.rows.length} rows</span></div></div>
 ${nums.length?`<div class="g g4" style="margin-bottom:18px">${nums.map((c,i)=>V.kpi({l:c.l,n:tot(c),f:c.fmt==='inr'?'short':'num',ic:['coins','chart','box','target'][i],c:V.PAL[i],sub:'total · selected scope'})).join('')}</div>`:''}
 ${V.repChartCfg(r,o)?V.card('','','<div class="cw" style="height:300px"><canvas id="c-rep" role="img" aria-label="Chart of '+V.esc(r.title)+'"></canvas></div>','mt'):''}
 <div class="mt">${V.card('','',V.table('rep',{rows:o.rows,cols:o.cols,pageSize:15,export:false,totals:nums.length&&o.rows.length&&!(r.opts||{}).nosum?o.cols.filter(c=>(c.fmt==='num'||c.fmt==='inr')&&!c.nosum).map(c=>c.k):undefined,empty:'No data for this period / location.'}))}</div></div></div>`},
mount(id){const q=V.$('#rq');if(q)q.addEventListener('input',()=>{V.S.rq=q.value;const p=q.selectionStart;V.refresh();const n=V.$('#rq');n.focus();n.setSelectionRange(p,p)});
 const r=id&&V.repById(id);if(!r)return;V.tbl.rep.keep=false;const o=V.run(r),cfg=V.repChartCfg(r,o);if(cfg)V.chart('c-rep',cfg)}});
V.acts.repP=el=>{V.S.rf.p=el.dataset.p;V.refresh()};
V.acts.repX=el=>{const id=(location.hash.split('/')[2]||''),r=V.repById(id),o=V.run(r),t=el.dataset.t,name=r.id+'_'+r.title.replace(/[^A-Za-z0-9]+/g,'_');
 if(t==='csv')V.dl(name+'.csv',V.csvOf(o.cols,o.rows));else if(t==='xlsx')V.xlsx(name+'.xlsx',o.cols,o.rows);
 else{const fm=(c,v)=>c.fmt==='inr'?V.inr(v):c.fmt==='num'?V.num(v):c.fmt==='pct'?(+v||0).toFixed(1)+'%':c.fmt==='date'?V.fd(v):V.esc(v);V.printHtml(`<h2>${r.title}</h2><p>${r.desc}<br>${V.brand.business} · ${V.fd(V.db.today)}</p><div class="temple"></div><table><thead><tr>${o.cols.map(c=>`<th>${c.l}</th>`).join('')}</tr></thead><tbody>${o.rows.slice(0,400).map(x=>`<tr>${o.cols.map(c=>`<td class="${['inr','num','pct'].includes(c.fmt)?'r':''}">${fm(c,x[c.k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`,r.title)}
 V.toast('Report exported')};
})();
